### ISSUE TITLE
'column.getCells()' only returns the cells visible 

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#2780] opened 2020-05-12 18:42 UTC
Hi there,

when using the **_column.getCells()_** that only returns the visible on the current page and not all the cells of column.
https://jsfiddle.net/JoaoDeOliveira/9jxzvm6b/12/

Is this a bug? or is normal due to the Virtual DOM? 

if normal behaviour, how can I get all cells of a column, independently if are visible or not?

Thanks for the attention, and for this great library

cheers
João

**Comment by olifolkerd** [comment] 2020-05-12 18:53
Why have you created a duplicate of the issue you raised not 10 mins ago, please post any comments on the original issue

**Closed by olifolkerd** 2020-05-12 18:53 UTC
Labels: Duplicate, Possible Bug

**Comment by Joao-deOliveira** [comment] 2020-05-12 18:54
> 
> 
> Why have you created a duplicate of the issue you raised not 10 mins ago, please post any comments on the original issue

Yep, look like.. I though so but 'cause haven't found the initial one .. :-(  
sorry about that.

**Comment by olifolkerd** [comment] 2020-05-12 18:55
#2780
