### ISSUE TITLE
Multiselect for headerFilter

### ISSUE THREAD

**Issue by blockcraftteam** [olifolkerd/tabulator#3041] opened 2020-10-18 01:35 UTC
Problem:
Trying to use multiselect in a headerFilter for a column with the select editor but it filters by the multiselect array joined with commas so none of the column values match. Instead, any of the items selected in the multiselect dropdown should be shown by the column filter.

Solution:
There's probably a better way to do it but here's my work-around that you might consider for your next update.

Change the "keywords" code under Filter.prototype.filters to:
```
      "keywords": function keywords(filterVal, rowVal, rowData, filterParams) {

        // added to avoid repeating code
        var separator = typeof filterParams.separator === "undefined" ? " " : filterParams.separator;

        // check to see if filterVal is an array and if so convert it to a string joining with filterParams.separator
        if (Array.isArray(filterVal)) {
          filterVal = filterVal.join(separator);
        }
        
        var keywords = filterVal.toLowerCase().split(separator),
          value = String(rowVal === null || typeof rowVal === "undefined" ? "" : rowVal).toLowerCase(),
          matches = [];

        keywords.forEach(function (keyword) {
          if (value.includes(keyword)) {
            matches.push(true);
          }
        });

        return filterParams.matchAll ? matches.length === keywords.length : !!matches.length;
      },
```
And then use a select headerFilter in combination with a keywords headerFilterFunc like this example when setting up the columns:
```
{title: 'Status', field: 'Status', width: 190, headerFilter: 'select', headerFilterLiveFilter: false, headerFilterFunc: 'keywords',
        headerFilterParams: {values: invoiceStatusOptions, multiselect: true, separator: ','}, editor: 'select', editorParams: {values: invoiceStatusOptions}}
```

**Comment by olifolkerd** [comment] 2020-10-18 11:48
Hey @blockcraftteam 

This is a duplicate of #2904

If you want to filter by multiple options then you need to set the ***headerFilterFunc*** to use the "in" function, which uses array comparison rather than string comparison

```js
{title:"Type", field:"type",  headerFilter:"select", headerFilterParams:{values:true,  multiselect:true}, headerFilterFunc:"in"},
```

The list of available built in filter functions can be found in the [Filter Documentation](http://tabulator.info/docs/4.7/filter#func-builtin)

Cheers

Oli :)

**Closed by olifolkerd** 2020-10-18 11:48 UTC
Labels: Duplicate
