### ISSUE TITLE
Custom Sorter Parameter aRow and bRow are undefined

### ISSUE THREAD

**Issue by ZiggiZagga** [olifolkerd/tabulator#3111] opened 2020-12-02 12:51 UTC
**Describe the bug**
const getSorter =()=>{
      return function(a, b, aRow, bRow, column, dir, sorterParams){
          console.log('aRow',aRow,'bRow',bRow)
     }
}
Parameters aRow and bRow for a customSorter, are always undefined, I need to Access the Data of the aRow and bRow, in order to make some sort decisions.

**Tabulator Info**
- Which version of Tabulator are you using?
4.9.1
**Working Example**
Version 4.8.3 works as expected

**Comment by EdwinVanRooij** [comment] 2020-12-03 11:00
Duplicate of #3092.

**Closed** 2020-12-13 16:18 UTC
Labels: Duplicate
