### ISSUE TITLE
resizable=false for column still shows resizable handles

### ISSUE THREAD

**Issue by mikexmagic** [olifolkerd/tabulator#1373] opened 2018-08-27 09:47 UTC
Hi community,

in my table config I set the main setting resizableColumns to 'header' and for each column the default for resizable is true. But if I set it to false for one column, it still shows me the resize handles and also the mouse appears as a resize pointer. Resizing itself wont work, okay. But it looks like for the user that resizing should be possible...

Is there something I missed in my configuration?

Mike

**Comment by olifolkerd** [comment] 2018-08-27 16:26
Hey @mikexmagic 

Could you include the table constructor object so we can see how you have the table setup.

Cheers

Oli :)

**Comment by mikexmagic** [comment] 2018-08-28 06:59
hey @olifolkerd 

I dont use any special stuff. Just try a basic config and you will see: there are still resize handles...

`$('#test').tabulator({
   columns: [
      {title: 'Col1',resizable: false}, //this col still have handles, but unable to resize
      {title: 'Col2'} // handles AND resizable. As expected ;-)
]
})`

Mike

**Comment by olifolkerd** [comment] 2018-09-01 15:01
Hey @mikexmagic 

The handles are currently added regardless of the ***resizable*** property and only the functionality is removed.

I do agree with you that this will make things unclear for the user and will look at adding it to the roadmap for improvement.

Thanks for the feedback.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2022-02-16 09:24
Hey @dbaranec 

If the issue is still open it means that this hasnt been actioned yet.

Cheers

Oli

**Comment by olifolkerd** [comment] 2022-04-04 19:48
An update has been pushed to the 5.2 branch that resolves this.

It will be included in the 5.2 release later this month.

Cheers

Oli :)

**Closed by olifolkerd** 2022-04-04 19:48 UTC
Labels: Enhancement
