### ISSUE TITLE
Tabulator 4.6.3 setPage("first" | "prev" | "next" | "last") not working

### ISSUE THREAD

**Issue by R0lin** [olifolkerd/tabulator#2824] opened 2020-06-02 12:05 UTC
Hi every one,

I'm using Tabular v4.6.3 and in Tabulator definition types:

`setPage: (page: number | 'first' | 'prev' | 'next' | 'last') => Promise<void>;`

but inside tabulator.js

```
Page.prototype.setPage = function (page) {
  var _this64 = this;
  var self = this;
  return new Promise(function (resolve, reject) {
     page = parseInt(page); <---------------------------------- Problem
     if (page > 0 && page <= _this64.max) {
       _this64.page = page;
       _this64.trigger().then(function () {
         resolve();
       }).catch(function () {
         reject();
       });
      if (self.table.options.persistence && self.table.modExists("persistence", true) && self.table.modules.persistence.config.page) {
        self.table.modules.persistence.save("page");
      }
    } else {
      console.warn("Pagination Error - Requested page is out of range of 1 - " + _this64.max + ":", page);
      reject(); <------------ Ends here!!!
   }
  });
};
```

Method is only trying to parseInt from page parameter. But in this case its no Number type is String type.

tabulator pagination config:

```
{
  ...
  pagination:"local",
  paginationSize: 20,
  paginationSizeSelector:[10, 20, 40, 80],
  addRowPos:"bottom",
  paginationAddRow: "table",
 ...
}
```

**Comment by olifolkerd** [comment] 2020-06-07 15:28
Hey @R0lin 

Thanks for the info,

That is definitely a regression you have found there, in one of the previous version updates that functionality looks like it was accidentally removed, i will put it on the list to fix for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-06-20 13:24
Hey @R0lin 

I have pushed a fix for this to the master branch that will be released tomorrow

Cheers

Oli :)

**Closed** 2020-06-21 16:00 UTC
Labels: Bug
