### ISSUE TITLE
Navigation features broken

### ISSUE THREAD

**Issue by bhanson-techempower** [olifolkerd/tabulator#2163] opened 2019-06-19 18:03 UTC
**Describe the bug**

`Uncaught ReferenceError: e is not defined`

Using navigation features causes `ReferenceError` and it also seems broken in general.

**Tabulator Info**

- Which version of Tabulator are you using? 4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup. See jsfiddle

**Working Example**

https://jsfiddle.net/bhanson_techempower/5wb4kyjv/

**To Reproduce**

1. Run jsfiddle
2. Click to edit "Backstreet Boy"
3. See `ReferenceError` in console

**Expected behavior**

Editor focus will be moved down one cell.

**Desktop (please complete the following information):**

 - OS: Windows 10 Version 1809 (Build 17763.557)
 - Browser: Chrome 75.0.3770.100

**Additional context**

https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L9014

`e` seems to be undefined in all of the surrounding functions as well.

In `Tabulator.prototype.navigateDown` on line 9016 there is an undefined function `dpwn`.

This entire group of functions does not seem to work. `Tabulator.prototype.navigateNext` does not have the problems listed above and still does not work. Calling this function seems to put the edit cell in a permanent state of being edited. Calling `.nav().*` on `CellComponent` also displays this behavior.

**Comment by aklaver** [comment] 2019-06-20 17:46
It seems the issue is isolated to the spelling error. The keybinding version:

```
navDown: function navDown(e) {
			var cell = false;

			if (this.table.modExists("edit")) {
				cell = this.table.modules.edit.currentCell;

				if (cell) {
					e.preventDefault();
					cell.nav().down();
				}
			}
},
```
which is the same minus the spelling works correctly. Changing the spelling on my local copy solves the issue. When I get a chance I will do a PR.

**Comment by aklaver** [comment] 2019-06-20 20:09
Create PR:
https://github.com/olifolkerd/tabulator/pull/2169

**Comment by bhanson-techempower** [comment] 2019-06-20 21:00
> Changing the spelling on my local copy solves the issue. When I get a chance I will do a PR.

If you have time could you provide a jsfiddle with a working example? I am unable to replicate this.

**Comment by aklaver** [comment] 2019-06-20 22:12
Hmm, I'm going to have to figure out how to pass in a custom version of tabulator.js.  Thinking this might have to be on CodePen where you can link to another CodePen that contains js.

**Comment by aklaver** [comment] 2019-06-21 17:04
Take a look at:

https://codepen.io/aklaver/pen/PrpJYL

The cellEditing callback does not work, I'm guessing because the value is changing. That will need more digging. I changed it to a cellEdited callback and that works.

**Comment by bhanson-techempower** [comment] 2019-06-21 17:16
Ahh yeah, that kind of works (at least in CellEdited).

The `dpwn` error was in `Tabulator.prototype.navigateDown`, so if you change the navigation reference to use that instead of the cell reference it should bring up the other errors I had mentioned.

**Comment by aklaver** [comment] 2019-06-21 20:05
I revised the above CodePen. It does not error, it does move down either. Something to do with this(more below):
```
Tabulator.prototype.navigateDown = function () {

		var cell = false;

		if (this.modExists("edit", true)) {
                        console.log("mod");

			cell = this.modules.edit.currentCell;

			if (cell) {

				e.preventDefault();

				return cell.nav().down();
			}
		}
                console.log(cell);
		return false;
	};
```

It is  seeing the edit mod, but not finding the currentCell so it bypasses the navigation code. This means digging into edit.js for how currentCell is set and when. That is going to be a later project. Calling directly on the cell works though.

**Comment by olifolkerd** [comment] 2019-07-17 20:46
Thanks for the headsup and the pull request, i will get the fix merged in at the weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2019-07-20 16:56
The pull request has been merged in and will be included in tomorrows release

Cheers

Oli :)

**Closed by olifolkerd** 2019-07-20 16:56 UTC
Labels: bug
