### ISSUE TITLE
updateOrAddRow : works but on new row throws strange TypeError exception

### ISSUE THREAD

**Issue by answerquest** [olifolkerd/tabulator#914] opened 2018-02-22 16:59 UTC
Code:
```
$("#stops-table").tabulator("updateOrAddRow", stop_id, {stop_id:stop_id, stop_lat:latlng[0], stop_lon:latlng[1], stop_name:stop_name, zone_id:zone_id, wheelchair_boarding:wheelchair_boarding  } );
```
The variables are all checked to be working.
`stop_id` is the key. The function does the job; I see the new row added in the table, but my browser console shows this error:
```
Uncaught TypeError: o.getComponent is not a function
    at t.(anonymous function).(anonymous function).updateOrAddRow (.../tabulator.min.js:4:354)
    at t.(anonymous function).(anonymous function).updateOrAddRow (.../jquery-ui.min.js:6:4499)
    at HTMLDivElement.<anonymous> (.../jquery-ui.min.js:6:5474)
    at Function.each (.../jquery-3.3.1.min.js:2:2573)
    at w.fn.init.each (.../jquery-3.3.1.min.js:2:1240)
    at w.fn.init.t.fn.(anonymous function) [as tabulator] (.../jquery-ui.min.js:6:5357)
    at updateTable (.../stops.js:179:20)
    at HTMLButtonElement.onclick (.../stops.html:92:77)
updateOrAddRow @ tabulator.min.js:4
(anonymous) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
t.fn.(anonymous function) @ jquery-ui.min.js:6
updateTable @ stops.js:179
onclick @ stops.html:92
```
* This happens when it's a new row being inserted. This error doesn't come if it's an existing row being updated.
* If this is to do with JQuery, then pls share which version is best to use for compatibility.. there currently isn't any version specified.
* Explanation of last lines in error: The function is called on clicking a button in the .html, and that executes a function `updateTable()` in the .js.
* System info: I'm on Chromium browser Version 64.0.3282.140 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (32-bit). I also checked on Firefox Quantum 59.0b10.. yikes the whole table is disappearing there, and something more; will have to file a different bug for it.

**Comment by olifolkerd** [comment] 2018-02-22 22:59
Hey @answerquest 

Iit looks like you have found a regression in v3.4 i have just pushed a fix for this to the master branch and will include it in this weekends patch release.

Thanks for your detailed post, it really helped get to the root of the problem quickly

Let me know if you have any other issues.

Cheers

Oli :)

**Closed by olifolkerd** 2018-02-22 22:59 UTC
Labels: bug
