### ISSUE TITLE
Tabulator with vue 3 failing to load

### ISSUE THREAD

**Issue by rigogsilva** [olifolkerd/tabulator#3504] opened 2021-12-13 23:11 UTC
Hi, 

I am trying to use tabulator with vue 3 and it seems to be having issues loading it? Any ideas what I need to do to fix this? 

## Error Message

```bash
./node_modules/tabulator-tables/dist/js/tabulator_esm.js 6428:90
Module parse failed: Unexpected token (6428:90)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 	min = typeof editorParams.min === "undefined" ? ( element.getElementsByTagName("div")[0]?.getAttribute("min") || 0) : editorParams.min,
| 	percent = (max - min) / 100,
> 	value = cell.getValue() || 0,
| 	handle = document.createElement("div"),
| 	bar = document.createElement("div"),
```

## Code

```js
import { TabulatorFull as Tabulator } from 'tabulator-tables';


const tabledata = [
  {
    id: 1, name: 'Oli Bob', age: '12', col: 'red', dob: '',
  },
  {
    id: 2, name: 'Mary May', age: '1', col: 'blue', dob: '14/05/1982',
  },
  {
    id: 3, name: 'Christine Lobowski', age: '42', col: 'green', dob: '22/05/1982',
  },
  {
    id: 4, name: 'Brendon Philips', age: '125', col: 'orange', dob: '01/08/1980',
  },
  {
    id: 5, name: 'Margret Marmajuke', age: '16', col: 'yellow', dob: '31/01/1999',
  },
];

const table = new Tabulator(this.$refs.table, {
  height: 205, // set height of table (in CSS or here), this enables th
  data: tabledata, // assign data to table
  layout: 'fitColumns', // fit columns to width of table (optional)
  columns: [ // Define Table Columns
    { title: 'Name', field: 'name', width: 150 },
    {
      title: 'Age', field: 'age', hozAlign: 'left', formatter: 'progress',
    },
    { title: 'Favourite Color', field: 'col' },
    {
      title: 'Date Of Birth', field: 'dob', sorter: 'date', hozAlign: 'center',
    },
  ],
  rowClick(e, row) { // trigger an alert message when the row is clicked
    alert(`Row ${row.getData().id} Clicked!!!!`);
  },
});
table.setData(tabledata);
```

**Comment by DevVahlok** [comment] 2021-12-16 18:49
I'm having the same issue using Angular.

**Comment by olifolkerd** [comment] 2021-12-19 16:51
This is a duplicate of #3194

**Closed by olifolkerd** 2021-12-19 16:51 UTC

**Comment by olifolkerd** [comment] 2021-12-30 08:22
i have updated the syntaxt to be compatible with older build tools so you should no longer see this error

**Comment by rigogsilva** [comment] 2021-12-30 12:11
Thanks @olifolkerd!!!!
