### ISSUE TITLE
Collapsing/Expanding tree elements causes scroll position to move unexpectedly.

### ISSUE THREAD

**Issue by MatthewAry** [olifolkerd/tabulator#2215] opened 2019-07-18 17:50 UTC
**Describe the bug**
In using Tabulator with dataTree rows that have non-uniform heights, it seems that tabulator handles the scroll position incorrectly when rows are expanded and collapsed. 

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup
Please see example.

**Working Example**
https://codepen.io/MatthewAry/pen/aebXWe

**To Reproduce**
1: Scroll Down
2: Collapse leaf child row
3: Observe change in table row positions above and below row with hidden leaf.

**Expected behavior**
The scroll position from the top of the Tabluator instance should not change when tree rows are toggled; when the sum height of the table rows is not less than the height applied to the tabulator instance.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser: Chrome
 - Version 75

**Additional context**
This cannot be fixed by turning virtual DOM off because of #1478 
Could this be caused by the fact that the table rows don't have a fixed height?

**Comment by olifolkerd** [comment] 2019-07-20 18:22
Hey @MatthewAry 

This is a duplicate of #1835

As i explained in that issue this is because you are using the table in classic mode, when you collapse or expand the tree it triggers a redraw of the table, which results it it having no height during the redraw so your scroll position moves.

I am looking into adding a less drastic redraw for table collapse/expansion in a future release.

Cheers

Oli :)

**Closed by olifolkerd** 2019-07-20 18:22 UTC
Labels: duplicate
