### ISSUE TITLE
Column groups does not auto size correctly

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1776] opened 2019-02-05 13:13 UTC
**Describe the bug**
Hey Oli,

When hiding a column part of a column group, it seems that the given column group does not auto size correctly to match child column widths.
When making a column visible, the column group sizes up correctly to match child column widths.
When hiding a column, the column group does not size down.

From inspecting the code, i can see that **Column.prototype.fitToData** can only upsize a column width, but not downsize, and that this method is only called when showing a column, but not when hiding it.

I thought i could manually call **Column.prototype.matchChildWidths** on the column group to resize it correctly, however this method does not take child column visibility into account and sums the width for hidden columns as well.

For now i have fixed the issue using this method:

```
matchVisibleChildWidths(column.parent);

..

function matchVisibleChildWidths(columnGroup) {
	var childWidth = 0;

	if (columnGroup.contentElement && columnGroup.columns.length) {
		columnGroup.columns.forEach(function (column) {
			if (column.visible) {
				childWidth += column.getWidth();
			}
		});

		columnGroup.contentElement.style.maxWidth = childWidth - 1 + "px";
	}
}

```
**Tabulator Info**
- 4.1.5

**Desktop:**
 - OS: Win 10
 - Browser Chrome

**Comment by olifolkerd** [comment] 2019-02-10 17:18
Hey @adamxi 

In most cases it does work correctly, i think this is referring to a specific instance where the text in the column group header title exceeds the length of the columns below it there should be no need for the level of computation described above.

Could you create a working JS fiddle or Code Pen that demonstrates the issue as it is hard to determine what is going on without seeing how your table is configured.

Cheers

Oli :)

**Comment by adamxi** [comment] 2019-02-12 09:27
Hey Oli,

I made this jsfiddle: https://jsfiddle.net/5epav16u/1/
The data in the table has been obfuscated for privacy reasons so dont be alarmed by the long hash values.
The problem remains the same however. If you press the hide and show buttons, the last column in the second column group will be hidden/shown. You'll notice that because of the long name in the column group, the width of the group is not shrinked down to mach the remaining child columns of that group.

Hope it helps :)

**Comment by olifolkerd** [comment] 2019-02-12 09:48
Hey @adamxi 

Thanks for the fiddle that is very helpful. As i mentioned above this issue is caused by having a long title for the column group which the column wont automatically shrink beyond.

I will look at including a fix for this in the weekends patch release.

Cheers

Oli :)

**Comment by adamxi** [comment] 2019-02-26 10:46
This still appears to be an issue in 4.2.1.
Updated fiddle: https://jsfiddle.net/adamxi86/u6qhs0b2/1/

**Comment by olifolkerd** [comment] 2019-02-28 20:39
hey @adamxi 

Yes this is very much still an issue, when i close this issue i will have considered the bug to be fixed.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2019-03-03 13:09
Hey @adamxi 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2019-03-03 13:09 UTC
Labels: bug
