### ISSUE TITLE
selectRow is undefined when using clipboardCopyRowRange: 'selected'

### ISSUE THREAD

**Issue by acdavis121** [olifolkerd/tabulator#2754] opened 2020-05-02 21:22 UTC
**Describe the bug**
`Cannot read property 'selectRow' of undefined` when using `clipboardCopyRowRange: 'selected'`

**Tabulator Info**
4.6.2

**Working Example**
[https://codepen.io/skeezy/pen/WNQXQwQ](https://codepen.io/skeezy/pen/WNQXQwQ)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. click on row(s) to select
2. ctrl+c
3. check console for error

**Expected behavior**
row(s) are copied to clipboard

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Additional context**
Error:
`tabulator.js:15733 Uncaught TypeError: Cannot read property 'selectRow' of undefined)`

node_modules/tabulator-tables/dist/js/tabulator.js
line 15733

`rows = this.modules.selectRow.selectedRows;`

I believe it should be: `rows = this.table.modules.selectRow.selectedRows;`

**Comment by olifolkerd** [comment] 2020-05-08 11:22
Hey @acdavis121 

Looks like a regression in the last release. i will get that fixed in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-05-09 09:24
Hey @acdavis121 

I have pushed a fix for this to the master branch and will include it in Sundays patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2020-05-09 09:24 UTC
Labels: Bug
