### ISSUE TITLE
Problem with updating paritial data when another column has mutator.

### ISSUE THREAD

**Issue by danke02** [olifolkerd/tabulator#1239] opened 2018-07-02 04:06 UTC
Hello.
I'm trying to update only few columns of data with "updateData" function.
When I call updateData function with data which contains fields of id and only to-be-updated values,
Tabulator tries to mutate every column which has a mutator on table options.
Problem happens here, when some column has a mutator but its value is not update and of course not exists in data for update.
So after updateData is called data is ruined with undefined value due to mutator is called with undefined value.
I think tabulator should try to mutate fields only when argument of updateData function call has that field.
Thank you.

**Comment by olifolkerd** [comment] 2018-07-03 21:51
Hey @danke02 

Thanks for getting in touch,

Sorry to hear you are having issues,

Could you include an example of your table constructor, a row of data and an example of the update command you are using so i can replicated the issue?

Cheers

Oli :)

**Comment by flamingwitch** [comment] 2018-08-08 12:42
I had the same problem, I had a mutator that converts nulls to empty strings but when I did an "updateData" it'd blank out all the column data that had values in it that weren't being updated.  I think it was because when the mutator was applied to the data being updated it'd go through each field in the row, not each field in the updateData data, and would then add an empty value for the other fields.   I hope that makes sense.  I added a check in the Mutator.prototype.transformRow to make sure the incoming data had the property being updated:

```
          if (mutator && data.hasOwnProperty(column.field)) {

            column.setFieldValue(data, mutator.mutator(column.getFieldValue(data), data, type, mutator.params, column.getComponent()));
          }
```

**Comment by olifolkerd** [comment] 2018-08-10 20:39
Hey @flamingwitch 

Thanks for the additional data there, i will ensure that is resolved on the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2018-09-01 10:39
i have just pushed a fix for this to the 4.0 branch.

Thanks for the input.

Cheers

Oli :)

**Closed by olifolkerd** 2018-09-01 10:39 UTC
Labels: bug

**Comment by germanfr** [comment] 2022-05-26 13:54
Hi Oli.

I'm experiencing this issue again in version 5.1.0. The issue may have popped up again after the recent rewrites of modules.
When I call `updateData` with partial data, the cells that have a mutator go blank. Their mutators receive `undefined` as a value.

I think I solved it by checking if the field has been updated before calling the mutator by adding this to the Mutator module:

```diff
 this.table.columnManager.traverse((column) => {
 	var mutator, params, component;
 	
+	// Check if updatedData is defined because the clipboard module, for example, does not pass it
+	if (updatedData && !updatedData.hasOwnProperty(column.field)) {
+		return; // continue
+	}
+
 	if(column.modules.mutate){
 		mutator = column.modules.mutate[key] || column.modules.mutate.mutator || false;
```

This is the method where I added it: `transformRow`
https://github.com/olifolkerd/tabulator/blob/f3f5a08cb21cabe79123b7b5b181de1f88c115dd/src/js/modules/Mutator/Mutator.js#L86-L112

Please consider reopening this issue and take a look at my piece of code, because I don't know if it could break any other part of the library. Feel free to use it for a patch if you think it's ok.

Thanks!

**Comment by olifolkerd** [comment] 2022-05-26 14:13
Hey @germanfr 

Thanks for getting in touch, sorry to hear you are having issues,

If you are having issues, the first port of call would be to raise an issue of your own using the issue template, as it is very likely due to a configuration issue, there are many types of mutator option but without a JS fiddle showing how your table is configured it is impossible to offer advice.

If you do feel you have a solution, then you will still need to create an issue so that we can track the problem, have a JS fiddle that reproduces the issue so we can test against it and includes the info outlined above. or better yet raise a PR that fixes the issue.  Checkout the [Community Guidelines](http://tabulator.info/community/bug) for more info

Please don't post on issues that are over 4 years old, Tabulator has been rebuilt several times since this issue was raised and almost certainly will be unrelated to this issue. and given the issue is closed there is no way of tracking that this issue has been resolved or not.

Cheers

Oli :)
