### ISSUE TITLE
Columns with Complex Header Not displayed when setting responsiveLayout to Collapse

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#1928] opened 2019-03-24 15:56 UTC
Hi Tabulator Team,

I have a Table with columns upto 20. In which few columns have column grouping set. By setting the responsiveLayout option to "collapse", few columns are not displayed permanently. Am I missing anything? Here is the image 

normal:
![image](https://user-images.githubusercontent.com/43729469/54881905-21812380-4e12-11e9-8a24-418397a10645.png)

after collapse, last few columns are not displayed.
![image](https://user-images.githubusercontent.com/43729469/54881966-a409e300-4e12-11e9-86cf-398aa4ff45d3.png)

Any help would be highly appreciated. Thanks

**Comment by olifolkerd** [comment] 2019-03-25 20:48
Hey @fingers10 

The ***collapse*** layout mode will collapse them to a list under the row (as appears to be the case in your second example image)

Cheers

Oli :)

**Comment by fingers10** [comment] 2019-03-26 00:46
@Hi olifolkerd,

I'm happy with the way collapse functions. As you can see in the above images, the columns under feedbacks group (the last four columns from the first image) is missing in the collapsed mode in the second image. Please could you hint on why this is happening?

**Comment by olifolkerd** [comment] 2019-04-03 18:33
Hey @fingers10 

Any chance you could create a JS Fiddle or Code Pen so i can see the issue in action.

Cheers

Oli :)

**Comment by fingers10** [comment] 2019-04-05 09:58
Hi @olifolkerd ,

Here is the CodePen Sample of the issue. [Columns Missing Sample](https://codepen.io/anon/pen/MRKNNY)

Thanks,
Abdul

**Comment by olifolkerd** [comment] 2019-04-05 18:00
Hey @fingers10 

In your example all the collapsed columns are showing correctly under the row, no collumns go missing when i use it on chrome.

The column group header is not show, but showing group column headers in collapsed columns is not currently a feature of Tabulator.

Is that what you are referring too?

Cheers

Oli :)

**Comment by fingers10** [comment] 2019-04-06 06:33
Hi @olifolkerd ,

No. I think this is related to responsiveness. Even in the example I have mentioned, If you open and try, everything looks fine in top layout. Here is the screen print.

![image](https://user-images.githubusercontent.com/43729469/55665856-da5c4f00-5863-11e9-9d8e-5684ac990f0f.png)


But if you change the pen layout to right or left and have a closer look, you can still notice that the last two columns in second column group are missing. Here is the screen print.

![image](https://user-images.githubusercontent.com/43729469/55665835-8e110f00-5863-11e9-999f-4d61edfc509e.png)


As you can see the last two columns in second column group "test2" is missing. This missing number of columns increases if we increase the number of columns in the table as I have mentioned in my original question.

Thanks,
Abdul

**Comment by olifolkerd** [comment] 2019-04-06 08:35
Hey @fingers10 

I now see what you are talking about, the issue isn't that they have gone missing, it is that the row is now so tall it is bigger than the height of the table so they are now below the end of the table.

I will have a look into the redraw maths to see why a scroll bar hasn't appeared, but this shouldn't really affect a real life example as when there are multiple rows in your table it should have a scroll bar anyway.

Cheers

Oli :)

**Comment by fingers10** [comment] 2019-04-06 10:13
Hi @olifolkerd,

No this happens when I have multiple rows as well. Please refer the first screenshot in this thread. That contains multiple rows and last few columns are not displayed for all the rows.

Thanks,
Abdul

**Comment by olifolkerd** [comment] 2019-04-07 11:24
Hey @fingers10 

The issue was that the formatter couldn't handle columns with the same title so in your case as you have columns with the same title the second one to collapse was overwriting the first.

I have changed the way this part of the system works and pushed a fix to master.

It will be included in this evenings patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2019-04-07 11:24 UTC
Labels: bug

**Comment by fingers10** [comment] 2019-04-08 07:09
Dear @olifolkerd ,

Perfect. It's working fine now. Thanks for the fix. 

Making the column group title also to be displayed in the collapse mode will make this even better. Looking forward that you will implement the feature in future releases.

Thanks,
Abdul
