### ISSUE TITLE
editor: 'select' crashes when setting values using editorParams function

### ISSUE THREAD

**Issue by nirhu** [olifolkerd/tabulator#2856] opened 2020-06-24 11:04 UTC
**Describe the bug**
Setting options for editor: 'select' cell using function crashes. 

**Tabulator Info**
4.7.0. (works on 4.6.3)

**Working Example**
https://codepen.io/nirhu/pen/PoZjYPW

**To Reproduce**
1. Click on the cell to edit
2. Options do not show up, and there is an error in chrome console

If you change tabulator version to 4.6.3, it works

**Expected behavior**
Options show up

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.106

**Comment by mill1000** [comment] 2020-06-27 06:21
Also seeing this issue.

Firefox 77.0.1

Here's the console output I see:
> TypeError: o is nulltabulator.min.js:7:20033
    r https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7
    forEach self-hosted:225
    r https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7
    b https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7
    select https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7
    select https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7
    edit https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7
    bindEditor https://unpkg.com/tabulator-tables@4.7.0/dist/js/tabulator.min.js:7

**Comment by mill1000** [comment] 2020-06-27 14:07
Clearer head this morning. 

The issue appears to be caused by having a value of `null` for the field in the table data source. Replacing null with an empty string will make the select work in both examples. As long as you can write the rest of your logic around `""` instead of `null` this should be a decent workaround (could even be desired behavior)

Fixed fiddle: https://jsfiddle.net/40gc8zbf/8/

**Comment by olifolkerd** [comment] 2020-06-27 17:13
Hey @nirhu 

Thanks for bringing that to my attention, the updated select editor was not correctly parsing the initial cell value when it was initialized.

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2020-06-27 17:13 UTC
Labels: Possible Bug
