### ISSUE TITLE
New version 4.2.6 using webpack 4.30.0 ... about frozen column error ?

### ISSUE THREAD

**Issue by jgorene** [olifolkerd/tabulator#2027] opened 2019-04-29 15:17 UTC
Hello,
First, thanks a lot for your awesome and very handly library... I like it a lot and still more :two_hearts: ;)

So, I use "frozen column" with grouped columns freezing the 1st column which is independent and itself a group in fact.
It worked very well until version 4.2.5 using "frozen: true" in options but maybe have to need to put another option to freeze a column or it sounds like a bug ?
Below message error...

I went back to version 4.2.5 to see what was going on. No error and it works like a charm
An idea about this, thank you in advance ;)

```
VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:16333 Uncaught TypeError: row.getCell is not a function
    at VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:16333
    at Array.forEach (<anonymous>)
    at FrozenColumns.layoutRow (VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:16332)
    at VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:16307
    at Array.forEach (<anonymous>)
    at FrozenColumns.layout (VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:16306)
    at ColumnManager.redraw (VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:1101)
    at Tabulator.redraw (VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:8570)
    at ResizeObserver.<anonymous> (VM35 npm.tabulator-tables-2322f94d11b3a626b3a8.js:20501)
```

**Comment by olifolkerd** [comment] 2019-04-29 17:55
Hey @jgorene 

Sorry i dont quite follow, are you saying you had an issue in 4.2.5 or 4.2.6?

It is very hard to diagnose your issue as you have not used the bug issue template, please resubmit this issue by filling in the bug issue template and providing the definition for your table so we can understand how your configuration may be interacting with the tabulator source.

Cheers

Oli :)

**Comment by tentus** [comment] 2019-04-29 19:14
Pretty sure the root of the problem is that the `groupBy` feature doesn't mesh well with the `FrozenColumns.prototype.layoutRow` changes: check out this fiddle, which throws the error mentioned:

https://jsfiddle.net/4593jq1h/2/

**Comment by olifolkerd** [comment] 2019-04-29 20:43
Hey @jgorene 

Thanks for the headsup, that is definitely a bug, i have just pushed a fix to the master branch and will release a new patch release later this evening.

Cheers

Oli :)

**Closed by olifolkerd** 2019-04-29 20:43 UTC

**Comment by jgorene** [comment] 2019-04-30 05:24
Hey Oli,

Sorry, the next time I use the bug issue template, it will probably be clearer ;)
@tentus  Thanks for the details +1

Besides, I'll probably open another ticket because it seems there's a problem with the type ">=" and "<=" with the decimal numbers on a table's "general filter".
That being said, I may not be using the filter properly and I'll take the time to check that.

Anyway, thank you again for making yourselve available ;)
