### ISSUE TITLE
IE Scroll issue

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1774] opened 2019-02-05 09:21 UTC
**Describe the bug**
Hey Oli,
In IE i have noticed a scroll issue when scrolling using the mouse wheel.
The issue only occurs having the virtual dom enabled and using the scroll wheel.

I have a table of 300 pixels high with about 50 rows in the table. Most of the rows are therefore not visible. When scrolling down fast, the table (and scrollbar) moves a bit down, then suddenly jumps up almost back to position 0, and then back again to where the table was supposed to be. This happens mostly when scrolling fast, and not very often when doing a single scroll step at the time. The behavior is the same when scrolling up.
The issue does not occur in Chrome.

**Tabulator Info**
- v4.1.5

**Desktop:**
 - OS: Win 10
 - Browser: IE
 - Version: 11.904.16299.0

**Table construct**

```
var table = new Tabulator("#fooTable", {
	dataTree: true,
	dataTreeStartExpanded: true,
	dataTreeChildField: "Children",
	height: "300px",
	columns: source.columns,
	data: source.data,
}
```

**Comment by olifolkerd** [comment] 2019-02-08 17:52
This is a general scrolling issue that affects all browsers, but is just more prevelant on IE, it is a duplicate of #1741

and is the result of a know issue in the virtual DOM that is being resolved in this mondays 4.2 release.

Cheers

oli :)

**Closed** 2019-02-08 17:52 UTC
Labels: duplicate
