### ISSUE TITLE
removeFilter for custom filters

### ISSUE THREAD

**Issue by 3iMichael** [olifolkerd/tabulator#1401] opened 2018-09-13 08:40 UTC
Unless I'm missing something, it seems like I can't remove a custom filter with "removeFilter".

To reproduce: 
- add a custom filter: 
`function customFilter(data, filterParams){`
`    return true;`
`}`
`$("#example-table").tabulator("addFilter", customFilter, {value: 1});`

- then try to remove it again:
`$("#example-table").tabulator("removeFilter", customFilter, {value: 1});`

Results in:

> Filter Error - No matching filter type found, ignoring: {value: 1}

**Comment by Rodbjartson** [comment] 2018-09-13 09:19
What happens when you omit `{value: 1}` when removing the filter?
`$("#example-table").tabulator("removeFilter", customFilter);`

**Comment by olifolkerd** [comment] 2018-09-13 18:17
Hey @3iMichael 

That definitily looks like a bug there, i will make sure it is fixed in next weeks 4.0 release.

in the mean time have you tried passing the function in an array?

```js
$("#example-table").tabulator("removeFilter", [customFilter]);
```

That might work,

Cheers

Oli :)

**Comment by 3iMichael** [comment] 2018-09-14 05:34
> in the mean time have you tried passing the function in an array?

Same result: 
> Filter Error - No matching filter type found, ignoring:  undefined

Looking forward to version 4.0, thanks for tue quick response :)

**Comment by olifolkerd** [comment] 2018-09-15 15:13
Hey @3iMichael 

Looking into it the removeFilter function, it is working correctly, the issue is that you are passing in a different object for the params into the ***addFilter*** and ***removeFilter*** functions.

It must be the exact same object, so you will need to put the params into a variable and reference in both functions:

```js
function customFilter(data, filterParams){
return true;
}

var params = {value: 1};
$("#example-table").tabulator("addFilter", customFilter, params);
$("#example-table").tabulator("removeFilter", customFilter, params);
```

This is because the filter function that the removeFilter function uses, uses a strict comparison on the values, as objects are compared by reference in JS it must be exactly the same object.

I hope that helps,

Cheers

Oli :)

**Closed by olifolkerd** 2018-09-15 15:13 UTC
Labels: bug, question

**Comment by ademcskn** [comment] 2023-06-22 06:07
Hello, in tabulator 5.4 version, this error appears: $(...).tabulator is not a function
