### ISSUE TITLE
Pagination unwanted scroll to top of page

### ISSUE THREAD

**Issue by jguitarz** [olifolkerd/tabulator#1172] opened 2018-06-01 20:26 UTC
First of all, great plugin! Very useful so far.

I am having an issue with the pagination scrolling to the top of the window whenever clicked.  Can't figure out why it is doing that.  I added this click event to remedy most of the problem:

    $(document).on('click','.tabulator-page',function(){
        console.log($(this).attr("data-page"));
        $(window).scrollTop($(".tabulator").offset().top);
    });

Only problem with that remedy is this event only works on the numbers and not the "First, Prev, Next, Last" buttons, yet they have the same selector.  By the way, I have already tried e.preventDefault(); and return false; in hopes it would stop scrolling to the top of the page.

Any solutions?

**Comment by olifolkerd** [comment] 2018-06-07 20:56
Hey @jguitarz 

Sorry for the delay in getting back to you,

What do you mean by "on click", clicking where? if you are talking about clicking on the pagination buttons then that is expected behaviour

Cheers

Oli :)

**Comment by jguitarz** [comment] 2018-06-07 22:05
Do you mean you expect the table itself to scroll to the top row? In my case it is scrolling the entire window to the top putting part of the table out of view which requires me to scroll down every time I would like to change the page.  It appears to work fine in your examples.  I actually asked this question on stackoverflow after doing more digging. Here's the link to that: [https://stackoverflow.com/questions/50726890/stop-tabulator-ajax-calls-from-scrolling-window-to-top-of-page](https://stackoverflow.com/questions/50726890/stop-tabulator-ajax-calls-from-scrolling-window-to-top-of-page)

It seems whenever the data is refreshed on the table via ajax that it causes the window to jump back to the top of the page.  I can't seem to find out what is causing that.

If you intended the pagination buttons to scroll the window to the top of the page then is there anyway I can override that?

**Comment by olifolkerd** [comment] 2018-06-08 07:06
Hey @jguitarz 

Tabulator definitely shouldn't affect anything outside the table element.

Could you post a copy of your constructor object here, i might then be able to offer some advice on why that is happening on your table.

Cheers

Oli :)

**Comment by jguitarz** [comment] 2018-06-08 15:06
I'm using coldfusion to build out the columns and set variables. Here's a simplified version of the constructor.
 
   <div id="#tabulator"></div>

    <script>
    $("#tabulator").tabulator({
        movableColumns: true,
        layout: "fitColumns",
        pagination: "remote",
        paginationSize: 10,
        ajaxURL: "rosterusers_tabulator_data-json.cfm",
        ajaxParams: {/* url params here */},
        columns: [/* columns set here*/]
    });
    </script>

Here's an example of what the json output looks like in the rosterusers_tabulator_data-json.cfm page

    /*example json data*/
    "last_page": 54,
    "data": [
        {id:1234, 
        user: "<div class='name'>LastName, FirstName</div><div class='email'>name@email.com</div>",
        demo1: "<a class='editDemo' data-demo_id='1'>Demographic Value</a>"}
    ]

Here's an example of the modal dialog call and update:

    $(document).on("click",".editDemo",function(){
        var update = function(){
           /*Send results to another cfm page to update data, then call setPage to update tabulator with new data*/
           $("#tabulator").tabulator("setPage",3);
        }
        /*openModal() loads a cfm page with ajax into a modal dialog box then calls the update function on submit*/
        openModal("editDemoValue.cfm", /*ajax params go here*/,  update);
    });

And the reason why I'm not using the cellClick native tabulator function is because I want to separate as much of the javascript from the page as I can, The reason I use $(document).on("click"); vs $(element).click() is because the element might not have been created yet from the many ajax updates going on.

I hope this can help point you in the direction of why it's jumping to the top of the page. The `<a>` tag doesn't have an href and the page scroll isn't happening until after tabulator data is updated so I'm confident that is not the issue.

**Comment by olifolkerd** [comment] 2018-06-24 08:53
Hey @jguitarz 

This turns out to be an issue with the pagination buttons when the table is included inside a form.

This issue has now been fixed and will be included in the patch release this evening.

Cheers

Oli :)

**Closed by olifolkerd** 2018-06-24 08:53 UTC
Labels: question

**Comment by Bonerserk** [comment] 2019-08-22 14:17
I have the same issue also when sorting fields.
I'm using 4.4.1 version.

This is my configuration

`var table = new Tabulator("#example-table", {
	data: data, //set initial table data
	layout: "fitDataFill",
	responsiveLayout: "collapse",
	columns:[
		{title:"Articolo", field:"sku", cellClick: artDrillDown, formatter:artFormatter},
		{title:"Descrizione", field:"description"},
		{title:"Colore", field:"color"},
		{title:"Size", field:"size"},
		{title:"Gender", field:"gender", visible:false},
		{title:"Dept", field:"dept", visible:false},
		{title:"Customer", field:"customer", visible:false},
		{title:"Price", field:"price", formatter:"money"},
		{title:"PromoPrice", field:"promoPrice", formatter:"money"},
		{title:"AvailabilityQta", field:"availabilityQta"},
		{title:"TransitQta", field:"transitQta"}
	],
	pagination: "local",
	paginationSize: 10,
	groupBy: function (data) {
		return data.gender + " - " + data.dept + " - " + data.customer; 
	}
	
});`

What could be the problem?

Thanks!

**Comment by tejasuplenchwar44** [comment] 2019-10-18 17:46
Hi @Olifolkerd 
We are using jquery.tabulator 3.5 version and we are facing scroll to top issue after updating/replacing  data.
Could you please help me to stop scroll after replacing data

**Comment by kufdaw** [comment] 2019-12-23 10:36
Hi,

unfortunately have the same problem. Whenever do any action on "cell edited" event it gets me to the top of the table. So if you have thousands of records it almost impossible to stay calm.

**Comment by olifolkerd** [comment] 2019-12-23 16:34
@tejasuplenchwar44 

Tabulator 3.5 is a year and a half old and out of support now. im afraid i can only support the latest version of Tabulator.

It is not the table scrolling that is the issue, this happens because in classic render mode when the table is redrawn the table div is momentarily emptied so the table has no height so the browser scrolls to the top.

This is a known issue and the easiest resolution is to use the virtual DOM by setting a height on the table.

All these issues will be resolved with the update to classic render mode in a future update

Cheers

Oli :)
