### ISSUE TITLE
Multigrouping breaks the table when some groups are collapsed and the user scrolls to bottom

### ISSUE THREAD

**Issue by skilltik** [olifolkerd/tabulator#1214] opened 2018-06-22 17:50 UTC
Hi, 
I have an issue when I set two levels of grouping and the user collapses one or more groups(first level group) and then scrolls to the bottom of the table.

the white area is the problem here, looks like the method in charge of calculate the padding-bottom is wrong.

![tabulator_bug](https://user-images.githubusercontent.com/4129453/41790842-3e9b7aa8-762a-11e8-8888-1e0d071a06d1.png)

regards,
Henry

**Comment by olifolkerd** [comment] 2018-06-24 12:32
Hey @skilltik 

Thanks for getting in touch, 

Sorry to hear you are having issues, the root cause of this is the same as #1126 and will be fixed in the upcoming 4.0 release.

Cheers

Oli :)

**Closed by olifolkerd** 2018-06-24 12:32 UTC
Labels: duplicate

**Comment by skilltik** [comment] 2018-06-25 14:23
@olifolkerd thanks for answer!

I have a workaround for this issue, but is pretty ugly.
Do you have an estimate date to the release of the 4.0 version ?

Regards,
Henry

**Comment by olifolkerd** [comment] 2018-06-27 15:41
Hey @skilltik 

I began work on 4.0 last weekend, im aiming to have it ready for the end of July hopefully.

Cheers

Oli :)

**Comment by skilltik** [comment] 2018-06-28 17:31
@olifolkerd I will be waiting, thanks!
