### ISSUE TITLE
Textarea formatter cell height bug in Firefox

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [olifolkerd/tabulator#1908] opened 2019-03-18 08:24 UTC
**Describe the bug**
When define the columns property to have 2 columns with "progress" and "textarea" formatters, then resize the column with the"textarea" formatter smaller to make its text wrapped into more lines and to increase row height, then resize it back. At here, the row height should scale back to fit the text, but in Firefox this isn't the case.

**Tabulator Info**
- Version: 4.2

**Working Examples**
- http://tabulator.info/examples/4.2 (At "Formatters" Section);
- https://codepen.io/meigyoku-thmn/pen/LarLOq

**Expected behavior**
Cell/Row height should resize to fit its content in all case.

**Screenshots**
- https://imgur.com/a/skysFu7 (For 1st Example);
- https://imgur.com/a/KGsEzAS (For 2nd Example);

**Desktop Info:**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 65.0.2

**Comment by tentus** [comment] 2019-03-18 20:43
I can confirm this is happening on Firefox 65 on Mac as well.

**Comment by olifolkerd** [comment] 2019-03-25 19:38
Hey @Meigyoku-Thmn 

Sorry to hear you are having issues,

That certainly looks like a bug, firefox is certainly full of a lot of quirks these days.

I will look into getting a fix for this into the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2019-04-07 16:53
Hey @Meigyoku-Thmn 

I think you might have exposed (yet another) inconsistent behaviour issue on the firefox browser.

when clearing the fixed height of the cell element firefox is not resizing the height of the child elements as it should be.

I will contact firefox and look into this further

Cheers

Oli :)

**Comment by laedit** [comment] 2019-05-05 08:00
Sorry to bother you, have you any news on this issue?

**Comment by olifolkerd** [comment] 2020-04-13 09:19
This appears to be resolved as of 4.6

**Closed by olifolkerd** 2020-04-13 09:19 UTC
Labels: Waiting on Firefox Browser Fix
