### ISSUE TITLE
Memory/Performance issue with clearHeaderFilter

### ISSUE THREAD

**Issue by dcanning** [olifolkerd/tabulator#2107] opened 2019-05-29 18:18 UTC
**Describe the bug**
Leak when calling clearHeaderFilter() or clearFilter(true)  when headerfilter is enabled for columns

**Tabulator Info**
-4.2.7
- https://plnkr.co/edit/Bf1mZKA312YdSZQiLHmO?p=preview

**Working Example**
https://plnkr.co/edit/Bf1mZKA312YdSZQiLHmO?p=preview

**To Reproduce**
click the filter button on the pnkr example.
After 6-8 clicks if you have developer tools console open you will start seeing warnings for event handler times
After 10-12 clicks the browser will stop responding
**Expected behavior**
no performance issue/memory leak

looks similar to #1709

**Desktop (please complete the following information):**
 - Win 10
 - chrome 74.0.3729.169/brave 0.64.77/firefox 67

**Comment by tentus** [comment] 2019-05-30 12:44
Can reproduce, firefox and chrome. From looking at the performance graph there's definitely something tripping up the garbage collector, after a dozen clicks the dom event handler is held up by repeated GC calls.

**Comment by olifolkerd** [comment] 2019-07-21 19:00
Thanks for the headsup, i will investigate this further.

Cheers

Oli :)

**Comment by richard-slabbert94** [comment] 2019-09-05 12:16
Hi Oli,

Once again thank you for your great component.

Any news on the memory leak? I am using 4.4.1 and am running into this issue with `.clearHeaderFilter()`.

Richard

**Comment by richard-slabbert94** [comment] 2019-09-06 06:59
Hi Oli, 

I did some research into the tabulator code and it seems that both clearHeaderFilter() and clearFilter(true) use the Filter.prototype.clearHeaderFilter method which seems to be the issue.

Each time clearHeaderFilter() is called it regenerates the header filter elements using Filter.prototype.generateHeaderFilterElement() and **appends** them each time to the arrays of header filters: this.headerFilterColumns and this.headerFilterElements (see lines 15438 and 15439). 

Since there is a forEach on this.headerFilterColumns in clearHeaderFilter(), this.headerFilterColumns and this.headerFilterElements arrays grow by a factor of two each time clearHeaderFilter() is called.

I hope this helps.

Richard

**Comment by olifolkerd** [comment] 2019-11-09 18:36
I have merged in the PR to fix this issue, it will be included in the 4.5 release in a few weeks.

Cheers

Oli :)

**Closed by olifolkerd** 2019-11-09 18:36 UTC
Labels: bug
