### ISSUE TITLE
clipboardCopyConfig not working

### ISSUE THREAD

**Issue by WhiteWind** [olifolkerd/tabulator#3013] opened 2020-09-30 08:45 UTC
**Describe the bug**
clipboardCopyConfig option is not honoured

**Tabulator Info**
4.8.2
```
clipboardCopyConfig: {
                    columnHeaders: false,
                    columnGroups: false, 
                    rowGroups: false, 
                    columnCalcs: false,
                    dataTree: false, 
                    formatCells: false, 
                }
```

**Working Example**
https://jsfiddle.net/hxdty3qL/

**To Reproduce**
Use Ctrl+C to copy data from tabulator table, then Ctrl+V to paste into MS Excel/LO Calc.
Table headers and columnCalc present in pasted data

**Expected behavior**
According to config, neither headers nor columnCalcs should be pasted

**Desktop**
 - Arch Linux
 - Browser Vivaldi 3.0.1874.38 (Chromium 81.0.4044.142)

**Comment by h4kst3r** [comment] 2020-10-13 15:45
Hi @olifolkerd,
Actually working with your awesome lib, like @WhiteWind found some inconsistencies in `clipboard` module.

https://github.com/olifolkerd/tabulator/blob/69af0e1ab646adada9cae9390fbc39ec1dc67d84/src/js/modules/clipboard.js#L32-L35

You can see **line 32** that `generateExportList` method from `export` module signature is not as expected and may be mixed up with `getHtml` method from the same module. This may be the cause of the weird behaviour described by @WhiteWind.

There is also a little glitch in the `blocked` property used to block triggering the listener if called **_browser side_** (logic, menu or keybinding).

https://github.com/olifolkerd/tabulator/blob/69af0e1ab646adada9cae9390fbc39ec1dc67d84/src/js/modules/clipboard.js#L74-L77

The actual behavior is consistent until the first call to the `copy` method then it can be triggered **_browser side_**. I think `this.blocked`should be set to `true`.
There is also `originalSelectionText` property which maybe had been replaced by `customSelection` property then it should be set here to `false` and no need to set it to `false` into `copy` method. 

Now still having some question about this part : 
https://github.com/olifolkerd/tabulator/blob/69af0e1ab646adada9cae9390fbc39ec1dc67d84/src/js/modules/clipboard.js#L131-L148

Is this necessary to modify `window`'s `Selection` object by adding table's node contents to perform the copy into clipboard ? And same about IE part. Maybe i'm missing something. 😅

Thank you for your awesome work on this library and your effort to have this impressive documentation so well organised and pretty exhaustive. 😁👍 

H.

**Comment by olifolkerd** [comment] 2020-10-25 13:36
Hey @WhiteWind 

I have pushed a fix to the master branch for this and will include it in the next patch release.

@h4kst3r  the issue was imply that the arguments in the ***generateExportList*** function were being passed in the wrong order, a regression from when that functionality was updated in the last minor release.

@h4kst3r thanks for the pointer on the blocked property, good spot there. Could i ask though that in future you raise points like that in a separate issue as it is unrelated to the purpose of this issue and tracking which issues have be resolved becomes really hard when people try and add multiple things to one issue.

and yes it is necessary to update the selection object like that for cross browser compatibility otherwise things start behaving very inconsistently between browsers. 

Cheers

Oli :)

**Closed by olifolkerd** 2020-10-25 13:36 UTC
Labels: Possible Bug

**Comment by h4kst3r** [comment] 2020-10-26 07:34
Hi @olifolkerd,
Thx for your answer. 

> @h4kst3r thanks for the pointer on the blocked property, good spot there. Could i ask though that in future you raise points like that in a separate issue as it is unrelated to the purpose of this issue and tracking which issues have be resolved becomes really hard when people try and add multiple things to one issue.

No problem you're right.

> and yes it is necessary to update the selection object like that for cross browser compatibility otherwise things start behaving very inconsistently between browsers.

I re-read this part. I finally got what you tried to do. I confused row selection (`range`related) with simple text selection. 😅

Cheers

H.
