### ISSUE TITLE
replaceData with empty array remove horizontal scroll when using ajax

### ISSUE THREAD

**Issue by wallsoferico** [olifolkerd/tabulator#3158] opened 2021-01-13 20:20 UTC
**Describe the bug**
The placeholder is removed causing the horizontal scroll to disappear when the filtered data is empty and you are using ajax. This means that if you set a filter on a column that isn't visible in the first few columns you cannot clear that filter. Reloading the page does fix the issue

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/mL9708ru/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click either the button or set any header filter

**Expected behavior**
Placeholder should and horizontal scrolling should be available

**Screenshots**
![tabulator-bug](https://user-images.githubusercontent.com/1250881/104505434-dff6d500-55b1-11eb-9010-32dc05acb431.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
From debugging the code it seems like it calls RowManager.prototype._virtualRenderFill twice possibly because of the column calculations causing a table redraw?

**Comment by olifolkerd** [comment] 2021-01-20 14:51
Hey @wallsoferico 

That is definitely unintended behaviour, i will add that to the list to fix in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2021-12-29 14:19
Hey @wallsoferico 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2021-12-29 14:19 UTC
Labels: Bug
