### ISSUE TITLE
Change calc formatting behaviour to only use bottomCalcFormatter on columns without a defined calc

### ISSUE THREAD

**Issue by AadBr** [olifolkerd/tabulator#2999] opened 2020-09-22 15:45 UTC
**Describe the bug**
The table and/or group footer displays data from columns that should not display 'bottomcalc'.

**Tabulator Info**
4.8.1

**Working Example**
4.8.1: 
[https://jsfiddle.net/AadBr/5et2q6yx/1/](url)

4.7.2:
[https://jsfiddle.net/AadBr/fc6ytg74/1/](url)

**To Reproduce**
Fiddles show the differences.
The bug did not exist in 4.7.2

**Expected behavior**
Only 'bottomcalc' data should be displayed in table footer/group footer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  chrome]
 - Version: 85.0.4183.102 
![tmlLog481_error](https://user-images.githubusercontent.com/2004332/93905478-dc140f80-fcaf-11ea-9525-9935da16d6cd.PNG)
![tmlLog472_error](https://user-images.githubusercontent.com/2004332/93905515-e930fe80-fcaf-11ea-96ba-5d4645d9625a.PNG)

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by olifolkerd** [comment] 2020-09-23 18:32
Hey @AadBr 

Thanks for letting me know,

This is related to column calc cells now being generated for all cells in a row. i will get this fixed in this weekends patch release.

Cheers

Oli :)

**Comment by AadBr** [comment] 2020-09-23 19:23
Hi Oli,

Thanks for your quick response.

Cheers,

Aad Brugman

**Comment by olifolkerd** [comment] 2020-09-27 08:59
Hey @AadBr 

On further inspection this is not a bug as such but more unintended functionality .Essentially as part of the 4.8 release formatters are now called on all calculation columns, not just those with data, which is resulting in the issue you are experiencing.

Unfortunately this feature is required for a number of other use cases so i would be reluctant to remove it, as it was added to specifically meet some users need. though it has caused a few issues with other users in a similar situation to you.

To mitigate this i propose that columns without defined calculation function will only use the ***bottomCalcFormatter*** instead of the default ***formatter*** function, making it easier to specifically handle this special case.

Because this is a change of function and not a simple fix i cannot include it in a patch release, but will include it in the next minor release with a documentation update.

in the mean time as a workaround if you set the ***bottomCalcFormatter*** property to an empty function with no return on the columns causing you issue then they should no longer display the message.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-09-27 10:36
On further investigation i had misinterpreted your explanation. there was  indeed a bug in the formatting of the column calculations with the default formatter.

I have pushed a fix for this to the master branch and will include it i todays patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2020-09-27 10:36 UTC
Labels: Bug

**Comment by AadBr** [comment] 2020-09-27 13:32
Thanks Oli, it’s working again!
