### ISSUE TITLE
Tabulator only renders 20 rows in Safari and Firefox, but normal in Chrome.

### ISSUE THREAD

**Issue by jesstucker** [olifolkerd/tabulator#887] opened 2018-02-16 06:41 UTC
Hi @olifolkerd,

Using Tabulator 3.4.0
Love the library.  Been developing an application with it.

When using Safari(11.0) and Firefox(58.0.2), Tabulator only renders 20 rows of data.
In Chrome(64), it works as expected by rendering all rows.

A few notes:

While in Safari:
- I can trick tabulator into rendering the rest of the rows by opening up a console.

While in Firefox:
- I can trick tabulator into rendering the rest of the rows by opening up a console _sometimes_.
- Fiddling around in the DOM sometimes provokes it to render properly.

Edit: While in Chrome:
- Setting virtualDom:false in the constructor makes Chrome behave like Firefox and Safari–by only rendering 20 rows. Conversely, this setting makes Firefox and Safari render properly. 

Filtering/sorting seems to trigger some rerendering in the DOM, as I can see previously "hidden" rows update in the DOM replacing the old rows.

I have seen that you often request to view how we've configured our Tabulator constructor, so here it is:

```
<div id="bike-table" style="width:70%; display:inline-block;"></div>
<script>
    $("#bike-table").tabulator({
        placeholder:"Bikes",
        layout:"fitColumns",
        selectable: true,
        index:"pk",
        columns:[
            {title:"ID", field:"pk", headerFilter:true},
            {title:"Bike Type", field:"fields.bike_type", headerFilter:true},
            {title:"Nickname", field:"fields.nickname", headerFilter:true},
            {title:"Size", field:"fields.size", width:50, headerFilter:true},
            {title:"Standover", field:"fields.standover_size", headerFilter:true},
            {title:"Min Ft", field:"fields.min_height_ft", headerFilter:true},
            {title:"Min In", field:"fields.min_height_in", headerFilter:true},
            {title:"Max Ft", field:"fields.max_height_ft", headerFilter:true},
            {title:"Max In", field:"fields.max_height_in", headerFilter:true},
            {title:"Rack?", field:"fields.has_rack", formatter:"tickCross", headerFilter:true},
            {title:"Touring?", field:"fields.is_touring", formatter:"tickCross", headerFilter:true}
        ]
    })
    $("#bike-table").tabulator('setData', "{% url 'bike_list_to_json' %}")  
</script>
```

Thank you for the great library.  It has been a pleasure to use. 
 
I'm curious; I have another issue about wrapping the 'setData' function in a promise, to do some further initialization, but am experiencing what is maybe a race condition; I'm not quite sure. Should I submit a different ticket for that?

Kindest regards,
Jess

**Comment by olifolkerd** [comment] 2018-02-16 07:13
Hey @jesstucker,

Sorry to hear you are having issues.

Are you using 4.1 or 4.1.1? i caught a small rendering niggle on the first day of release which may be affecting your table.

Could you have a quick check with 4.1.1 and let me know if it is still an issue?

If you could raise your other question as a separate issue that would be great, and post a copy of the code you have used to wrap the promise.

Cheers


Oli :)

**Comment by olifolkerd** [comment] 2018-02-16 07:25
Just a thought, do you have a resize watcher on the window event to redraw your table?

If so Tabulator does this automatically now so try removing it if present.

**Comment by olifolkerd** [comment] 2018-02-16 07:31
Also just wanted to check, have you set a height anywhere on your table, in CSS, inline CSS or in the Tabulator Constructor.

That will be needed for the virtual DOM to work correctly.

**Comment by olifolkerd** [comment] 2018-02-16 14:00
Hey @jesstucker 

I have had a look into it an this a is a duplicate of the bug raised in #885 

I have found where the source of the issue is, it is being caused by the Virtual DOM trying to engage on tables without a height set which is messing up the calculations.

I will have a fix out in this weekends patch release.

Cheers

Oli

**Comment by jesstucker** [comment] 2018-02-16 17:26
Hey @olifolkerd,

Yes, correct, I have nothing set for height, as I wanted the full table rendered.  

Subsequently, I have set the height to 100%, which does not seem to affect rendering. 

I have also checked using version 3.4.1, but am currently using the CDN version where I do not see a 3.4.1.1 version.  Is this what you are referring to?  As a side note, reverting to v 3.3.1 seems to allow full table rendering.

I patiently await your patch, and thank you for looking into this so quickly. 👍 

Jess

**Comment by olifolkerd** [comment] 2018-02-17 10:53
Hey,

Try downloading the latest 3.4.2 release, it should hopefully fix the issues you were experiencing.

Cheers

Oli :)

**Closed by olifolkerd** 2018-02-17 10:53 UTC
Labels: duplicate

**Comment by aklaver** [comment] 2018-02-17 21:20
I was experiencing the same issue with 3.4.0, so I upgraded to 3.4.2 and I still see the issue. On Chromium(64.0.3282.167 (openSUSE Build) (64-bit)) the table renders correctly. On Firefox(52.6.0 (64-bit)) it only displays 20 out of 36 rows. Table code:

    ("#proj_table").tabulator({
        ajaxURL:"/proj_table/list",
        ajaxParams:{"p_item_no":$("#id_p_item_no").val(), "year_start":$("#id_year_start").val(), "year_end":$("#id_year_end").val()},
        height:"100%", // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
        layout:'fitColumns',
        index:"line_id",
        addRowPos:"top",
        columns:[
            {title:"Id", field:"line_id", visible:false},
            {title:"P_id", field:"p_item_no"},
            {title:"Year", field:"year"},
            {title:"C_id", field:"c_id"},
            {title:"Trial", field:"trial", formatter:"tick"},
            {title:"Method", field:"method"},
            {title:"Sub", field:"sub_method"},
            {title:"Qty", field:"qty"},
            {title:"Pot#", field:"pot_ct"},
            {title:"Link", field:"link_key"},
            {title:"Vendor", field:"v_number__v_s_name"}
        ],
        cellEdited:function(cell){alert("UPDATED");},
        rowClick:function(e, row){
            var pk = row.getData().line_id;
            $.get('/projection_entry/', {"line_id": pk, "year_start": $("#id_year_start").val(), "year_end": $("#id_year_end").val()})
            .done(function(data){
                var content = $( data ).find( "#proj_form" );
                $("#proj_content").html(content);
            });
        },
        tableBuilt:function(){
            var savedTab = localStorage.getItem('lastTab');
            if (savedTab) {
                $('[href="' + savedTab + '"]').tab('show');
            }
        },

    });

**Comment by olifolkerd** [comment] 2018-02-17 21:42
Hey @aklaver,

Sorry to hear you are still having trouble,

I have just used you exact code with 3.4.2 on an empty HTML page on firefox 52.6.0 and i see all 36 rows rendering correctly. 

Are you sure you are running the latest code and that the browser hasn't cached it (just have to check) as other users are reporting that the update has fixed their issues. If you have the table on a page with other content, could you try it in an empty HTML page with no other content just to see what could be causing the issue. Is the table visible when it is first created?

Could you try setting up a [Code Pen](https://codepen.io/) with a table that replicates the issue you are experiencing as i cant seem to replicate it here.

Cheers

Oli :)

**Comment by aklaver** [comment] 2018-02-17 22:00
Out of curiosity how did you generate the 36 rows?
Pretty sure caching is not the issue as when I  open the FF Web console and reload the page I see the following for the responses for the static files:
    'use strict';

    var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

    /* Tabulator v3.4.2 (c) Oliver Folkerd */

    /* Tabulator v3.4.2 (c) Oliver Folkerd */

    /*# sourceMappingURL=tabulator.min.css.map */


    /* Tabulator v3.4.2 (c) Oliver Folkerd */

    /*# sourceMappingURL=tabulator_bootstrap.min.css.map */

The table is visible when first created. I will try setting it up in an empty page.
I have never used  Code Pen, so that might not happen at this time.

**Comment by olifolkerd** [comment] 2018-02-17 22:15
I just had a PHP script that returned a JSON encoded array with 36 rows in.

Is anything showing up in your console log?

**Comment by aklaver** [comment] 2018-02-17 22:17
On 02/17/2018 02:15 PM, Oli Folkerd wrote:
> I just had a PHP script that returned a JSON encoded array with 36 rows in.
> 
> Is anything showing up in your console log?
> 

No, though if I open the console and close it the table displays all the 
rows.


-- 
Adrian Klaver
adrian.klaver@aklaver.com

**Comment by aklaver** [comment] 2018-02-17 22:58
On 02/17/2018 02:19 PM, Oli Folkerd wrote:
> that is because the window is being resized which is triggering the redraw.
> 
> have you tried it on a blank page where it is the only element?

Just did and I see the same issue.

In the console I see:

unreachable code after return statement[Learn More]  tabulator.js:15999:10
unreachable code after return statement[Learn More]  tabulator.js:16166:10

Where 15999:10 is:

   if (isNaN(b)) {

             return 0;
           }

and 16166:10 is

if (!Array.isArray(b)) {

             return 0;
           }


-- 
Adrian Klaver
adrian.klaver@aklaver.com

**Comment by olifolkerd** [comment] 2018-02-17 23:01
Hey @aklaver 

Those messages are due to an issue with ordering of code in the number sorter, but they dont cause an error so shouldn't be a problem, and arnt related to the render im afraid.

Is there any chance you could spin this up on [Code Pen](https://codepen.io/) that way you can be 100% sure that the code is setup like your site and i can then see if it loads the same in my browser.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2018-02-17 23:06
Thanks for pointing them out though, i have just pushed an update to the master branch to prevent that warning appearing up in the next patch release

**Comment by aklaver** [comment] 2018-02-17 23:57
On 02/17/2018 03:01 PM, Oli Folkerd wrote:
> Hey @aklaver <https://github.com/aklaver>
> 
> Those messages are due to an issue with ordering of code in the number 
> sorter, but they dont cause an error so shouldn't be a problem, and arnt 
> related to the render im afraid.
> 
> Is there any chance you could spin this up on Code Pen 
> <https://codepen.io/> that way you can be 100% sure that the code is 
> setup like your site and i can then see if it loads the same in my browser.

I am afraid life intervened, I will probably get to this tomorrow.

> 
> Cheers
> 
> Oli :)
> 



-- 
Adrian Klaver
adrian.klaver@aklaver.com

**Comment by aklaver** [comment] 2018-02-18 18:15
Turns out if I change the height from 100% to 500px then I see all the rows, albeit with a vertical slider.  This code is being run through Django, so I am still in process of converting to a truly stand alone example.

**Comment by olifolkerd** [comment] 2018-02-18 18:35
Hey @aklaver 

So by the sounds of it then the issue you are having is because you have set your Table to have a height of !00% inside of another div which has no height set.

That means when the table loads it has a height of 100% of 0, which is 0. When tabulator detects a table height of zero it will enter classic render mode which is where you may be experiencing problems.

Cheers

Oli

**Comment by aklaver** [comment] 2018-02-18 19:51
Stand alone example is here:

https://codepen.io/aklaver/pen/XZZbPr

Adding a height to the div did not change the rendering as long as I had height in table code set to 100%.

**Comment by olifolkerd** [comment] 2018-02-18 21:04
Awesome, thanks for that.

The good news is i am also seeing the row drawing issue now so i can see what the cause is tommorow and get that fixed :D

**Comment by olifolkerd** [comment] 2018-02-18 21:18
Hey @aklaver 

good news, i have gotten to the bottom of what is going on there.

The issue is because you have the table height set to 100% and the table element is directly in the body of the HTML document.

By default in firefox, the height of the HTML and body tags is not set at 100% of the height of the browser window which is causing tabulator to only render at the initial height of the body, which then firefox is resizing.

The solution to this would be to set a css height on the body and the html tags of 100%

Cheers

Oli :)

**Comment by aklaver** [comment] 2018-02-18 21:46
Thanks for digging down to the cause. Adding CSS heights to my stand alone case worked. My production case did not benefit though, so something else is getting in the way there. For me just specifying a set height in the table code actually works out better. Down the road I will be converting tables that will see big result sets to pagination anyway and that is working correctly for the tables that I have already done.  Again appreciate the time you spent helping me work through this.
