### ISSUE TITLE
Double clicking group header throws TypeError

### ISSUE THREAD

**Issue by bornova** [olifolkerd/tabulator#3634] opened 2022-03-02 06:21 UTC
**Describe the bug**
Double clicking group header throws following error:
- On Chrome: `TypeError: Cannot read properties of undefined (reading 'parentNode')`
- On Safari: `TypeError: undefined is not an object (evaluating 'targets["row"].parentNode')`

**Tabulator Info**
- v5.1.3

**Working Example**
https://codesandbox.io/s/kind-mountain-zyee90

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://codesandbox.io/s/kind-mountain-zyee90
2. In the example table, double click on any group header (group title or empty area, not the arrow)
3. Open console

**Comment by olifolkerd** [comment] 2022-03-05 14:14
Hey @bornova 

This had the same root cause as #3632, i have pushed a fix for it to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2022-03-05 14:14 UTC
Labels: Possible Bug
