### ISSUE TITLE
Sorting large tables causes them to be blank until scrolled

### ISSUE THREAD

**Issue by purxiz** [olifolkerd/tabulator#3586] opened 2022-02-09 03:03 UTC
**Describe the bug**
When sorting a table by clicking on a header/title, with enough rows (and a small enough height) that some aren't rendered (virtualDOM enabled), the table becomes blank.

**Tabulator Info**
- This occurs in both 5.0 and 5.1, though does not appear to happen in 4.9 and earlier.

**Working Example**
This can be re-created using the first example on the "examples" page, titled Virtual DOM.

**To Reproduce**
1. Go to [tabulator examples](http://tabulator.info/examples/5.1)
2. In the first table, Virtual DOM - Vertical, scroll down about halfway
3. Sort on any column by clicking on the header row
4. Table either becomes blank, or scrolls all the way to the bottom.
5. If table scrolls to the bottom, repeat from 2, and the table will become blank until scrolled again.

**Expected behavior**
Either table maintains position and correctly renders rows, or as in 4.9, table always scrolls to the top when sorted on a column.

**Screenshots**
![image](https://user-images.githubusercontent.com/1489052/153113966-c4d7bf1d-4e6a-40f4-80fe-20790b07337f.png)

**Desktop (please complete the following information):**
 - OS: Tested on Windows 10, 11, and arch linux
 - Browser: Edge and Firefox
 - Version: latest

**Comment by anthonyrobertson** [comment] 2022-02-09 17:26
I too see this happen with large tables.  If I scroll down from the top of the table and then sort on any row, there are rendering issues with the table.

It only takes several hundred rows, maybe less. Sometimes the table will partially render which caused me to notice that the padding values seem to be miscalculated. 

The workaround I'm using is to call a forced redraw() on the table when the `dataSorted` event happens which scrolls the table back to the top.  This works for the time being, but it prevents me from updating a single row and then re-sorting with setSort() because that causes the rendering bug.  Ideally I could update a single row, re-sort the table and have the user's scroll position preserved.

I am using 5.1 and also reproduced this on 5.0,  MacOS / Chrome

Thank you for all your hard work on this excellent library

**Comment by olifolkerd** [comment] 2022-02-19 15:43
Hey all,

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2022-02-19 15:43 UTC
Labels: Bug
