### ISSUE TITLE
Documentation: rendering bug?

### ISSUE THREAD

**Issue by E3V3A** [olifolkerd/tabulator#862] opened 2018-02-05 22:08 UTC
Sorry to spam you with new issues, but it seem that the documentation that we constantly refer to, need some TLC. This is how the [Theming section](http://tabulator.info/examples/3.3?#theming) currently reneders on both Firefox and Chrome: 

![firefox_2018-02-05_23-44-34](https://user-images.githubusercontent.com/194392/35831141-739a0022-0ad1-11e8-879b-ba0f688ea7a6.png)

----

Cheers! ❤️

**Comment by olifolkerd** [comment] 2018-02-05 22:39
Hey @E3V3A 

Thanks for pointing that out, there was a regression in the way it loaded the multiple theme tables, the issue is now fixed :)

No need for the sarcasm though, as i say, we are all happy to help.

Cheers

Oli

**Closed by olifolkerd** 2018-02-05 22:39 UTC
