### ISSUE TITLE
Select editor not hide when scrolling

### ISSUE THREAD

**Issue by bobchou** [olifolkerd/tabulator#2158] opened 2019-06-18 12:37 UTC
**Describe the bug**
When scrolling, the select drop-down box should be hide automatically, it works in previous version like 4.0, but it is not working at current version.

**Tabulator Info**
- Which version of Tabulator are you using?   4.2.7

**Working Example**
It happens on your demo page, when you clicking Gender column, then scroll page, you will found the options keep open.
http://tabulator.info/examples/4.2?#editable

**Expected behavior**
I think the drop-down menu should be close when scrolling, just as previous version.

**Comment by tentus** [comment] 2019-06-18 17:52
I can confirm this is the case across Chrome, Firefox, Safari, etc etc.

Looks like this cropped up with version 4.1, when the new select editor was implemented. I haven't got that much experience with javascript's scroll event but it seems like the root of the issue is that scrolling the parent doesn't count as losing focus, so edit module never realizes it needs to call `cancelItem()`

**Comment by olifolkerd** [comment] 2019-07-17 20:52
Hey @bobchou 

@tentus is correct, that should be a fixable issue, i will have a look into it at the weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2019-07-21 11:49
I have pushed a fix for this to the 4.3 branch and will include it in todays release.

Cheers

Oli

**Closed by olifolkerd** 2019-07-21 11:49 UTC
Labels: bug
