### ISSUE TITLE
Double click a text in a cell results in highlighting more than one cell

### ISSUE THREAD

**Issue by sarmad99** [olifolkerd/tabulator#2739] opened 2020-04-29 18:15 UTC
**Describe the bug**
when double clicking a text in a cell to highlight, the text from other cells get highlighted.

**Tabulator Info**
4.6.2
https://unpkg.com/tabulator-tables@4.6.2/dist/js/tabulator.min.js

**Working Example**
https://jsbin.com/pomehayoya/1/edit?html,js,output

**To Reproduce**
1. Go to the link above
2. double Click on any cell text (first words in the cells of first column doesn't reproduce the issue)
3. See error (text of more than one cell gets highlighted)

**Expected behavior**
double click text in a cell should highlight the text of that cell only.
Or the word we double clicked

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: multiple (81.0.4044.113 (Official Build) (64-bit))

**Additional context**
this issue was mentioned here:
https://github.com/olifolkerd/tabulator/issues/2217
solution was to use new version but now I am using 4.6.2 and same issue

**Comment by takuy** [comment] 2020-05-03 16:54
This is tied to a Chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=39795
https://bugs.chromium.org/p/chromium/issues/detail?id=850460

**Comment by 805bluebell** [comment] 2020-05-06 09:39
Well, @takuy is correct. I couldn't produce this on Firefox. Although, it was there in Chrome. A 10-year-old Chromium bug. Going on unfixed.

**Comment by olifolkerd** [comment] 2020-05-09 10:59
@sarmad99,

This is a regression from the previous release but has arisen because of another bug in chrome.

If i block this sort of selection, then it prevents triple click full cell contents selection. if i allow this, then the arbitrary row selection starts again. and i essentially end up bouncing between the two.

I think i will revert the previous commit to prevent this selection behaviour in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-05-09 14:55
Hey @sarmad99,

I have pushed a fix to the master branch that should prevent both the text selection issue you identified and the editor selection issue i identified.

It will be included in the patch release this Sunday.

Cheers

Oli :)

**Closed by olifolkerd** 2020-05-09 14:55 UTC
Labels: Bug
