### ISSUE TITLE
Add fitColumnsFill layout mode

### ISSUE THREAD

**Issue by brimimc** [olifolkerd/tabulator#2870] opened 2020-07-01 08:45 UTC
*Is your feature request related to a problem? Please describe.**
when using fitColumns layout, when you resize a column the rows do not fill the remaining space like they do using the fitDataFill layout - you just get a big white space
<img width="1466" alt="Screen Shot 2020-07-01 at 4 41 49 AM" src="https://user-images.githubusercontent.com/2230920/86223284-56237500-bb55-11ea-923c-e48810ee2699.png">
<img width="1465" alt="Screen Shot 2020-07-01 at 4 42 00 AM" src="https://user-images.githubusercontent.com/2230920/86223289-591e6580-bb55-11ea-829b-ca7b2e7b99a6.png">

**Describe the solution you'd like**
I would like a way to support the columns to initially layout like fitColumns (equally sized filling width) but also have the row filling functionality of fitDataFill. A new layout mode fitColumnsFill seems to be the ideal solution.

**Describe alternatives you've considered**
I'm looking into using fitDataFill but manually sizing the columns on load

**Additional context**

**Comment by olifolkerd** [comment] 2020-11-07 16:20
Hey @brimimc 

On second reading, this is a duplicate of #2609 

As they raise they idea first, i will close this issue and track updates on the original issue.

Cheers

Oli :)

**Closed by olifolkerd** 2020-11-07 16:20 UTC
Labels: Suggested Feature
