### ISSUE TITLE
Bug with drag and drop

### ISSUE THREAD

**Issue by davidbourrel** [olifolkerd/tabulator#3876] opened 2022-07-25 14:00 UTC
**Describe the bug**
I have a problem with drag and drop. I would use drag and drop feature into my project but in the tabulators exemples it doesn't work on firefox. No problem with Edge and Chrome.

**Tabulator Info**
5.3

**Working Example**
http://tabulator.info/examples/5.3#movable-between-tables

**To Reproduce**
Try to drag and drop row to another element / table.

**Expected behavior**
Row element should be in another element / table

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 91.11.0

**Comment by olifolkerd** [comment] 2022-07-25 14:58
This is a duplicate of #1184 we have been wating on firefox to fix an issue in their event management system for years now

**Closed by olifolkerd** 2022-07-25 14:58 UTC
Labels: Possible Bug
