### ISSUE TITLE
addRow() adds even/odd rows depending on the last row number

### ISSUE THREAD

**Issue by TI-AviBerko** [olifolkerd/tabulator#4105] opened 2023-01-30 00:03 UTC
**Describe the bug**
addRow() adds even/odd rows depending on the last row number
This can be seen when a theme that has alternating row colors is applied, and also by using the rownum formatter.
The color/number of the added row advances by 2 (e.g. 1,3,5... or 2,4,6...) instead of by 1, and the color of the new row(s) doesn't alternate.
Note: This happens in v5.4.3, but works fine in v5.4.2

**Tabulator Info**
v5.4.3

**Working Example**
Jsfiddle: https://jsfiddle.net/aviberko/4cmd9qap/13/

**To Reproduce**
1. Run the example in jsfiddle, the output window should show 2 tables, stacked vertically
2. Press a row on the upper table to append a new row, do this multiple times and see that the row number is always odd and the row color doesn't alternate
3. Repeat the last step with the bottom table, notice that this time the row number is always even and the color follows

**Expected behavior**
1. Row number is advanced correctly and the row color alternates

**Desktop (please complete the following information):**
 - OS: Win10/11
 - Browser: Electron, Firefox, Edge
 - Version Firefox 109, Edge 109

**Comment by olifolkerd** [comment] 2023-02-12 12:14
This is a duplicate of #4083

**Closed by olifolkerd** 2023-02-12 12:14 UTC
Labels: Duplicate

**Comment by TI-AviBerko** [comment] 2023-02-20 23:58
@olifolkerd it works fine now, thank you.
