### ISSUE TITLE
Header filter repeats

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1476] opened 2018-10-03 14:46 UTC
**Describe the bug**
When using a header filter it fires three times. The first time after the 300 msec timeout and then after 2-3 sec it fires two more times.

**Tabulator Info**
Tabulator v4.0.0
```
var table = new Tabulator("#complex_table", {
        ajaxURL: "/complex_table_data/list/",
        ajaxParams: {"year": 1999, "comp_op": "gte"},
        ajaxURLGenerator:function(url, config, params){
        //url - the url from the ajaxURL property or setData function
        //config - the request config onject from the ajaxConfig property
        //params - the params object from the ajaxParams property, this will also include any pagination, filter and sorting properties based on table setup

        //return request url
        return url + "?params=" +encodeURI(JSON.stringify(params)); //encode paramters as a json object
        },
        ajaxFiltering:true,
        index: "line_id",
        // ajaxProgressiveLoad: "scroll",
        pagination: "remote",
        paginationSize: 12,
        selectable: 1,
        height: "400px",
        layout:"fitColumns",
        columns:[
                {title: "", formatter: "handle", width: 10},
                {title:"Id", field:"line_id", sorter:"number", width:100},
                {title:"Geography", field:"geography_desc", sorter:"string", editor: true, headerFilter: true},
                {title:"Description", field:"commodity_desc", sorter:"string", editor:true},
                {title:"Type", field:"attribute_desc", width:200, editor: true},
                {title:"Unit", field:"unit_desc", sorter:"string", editor: true},
                {title:"Year", field:"year_id", sorter:"string", editor: true},
                {title:"Period", field:"timeperiod_id", sorter:"number", editor: true, headerFilter: true},
                {title:"Amount", field:"amount", sorter:"number", editor:true, validator: "numeric"},
                ],
        cellEdited:function(cell){
            pk_val = cell.getRow().getIndex();
            if (pk_val) {
                var fld = cell.getField(), val = cell.getValue();
                $.post("/complex_table_data/update/", {"pk_val": pk_val, "field": fld, "val": val});
                }
            },
        rowAdded:function(row){
            row.toggleSelect();
            setTimeout(function(){row.getCell("geography_desc").edit();}, 200);
        },
        tableBuilt: function(){
            jQ('#year_search').value = 1999;
            }
        });
```

**To Reproduce**
Enter a search string in the geography_desc header and wait 300 msec.

**Expected behavior**
There should be only one filter request.

**Screenshots**
```
{'params': ['{"year":"2010","comp_op":"eq","page":1,"size":12,"filters":[{"field":"geography_desc","type":"like","value":"tex"}]}']} args
127.0.0.1 - - [03/Oct/2018 07:40:35] "GET /complex_table_data/list/?params=%7B%22year%22:%222010%22,%22comp_op%22:%22eq%22,%22page%22:1,%22size%22:12,%22filters%22:%5B%7B%22field%22:%22geography_desc%22,%22type%22:%22like%22,%22value%22:%22tex%22%7D%5D%7D HTTP/1.1" 200 -
{'params': ['{"year":"2010","comp_op":"eq","page":1,"size":12,"filters":[{"field":"geography_desc","type":"like","value":"tex"}]}']} args
127.0.0.1 - - [03/Oct/2018 07:40:38] "GET /complex_table_data/list/?params=%7B%22year%22:%222010%22,%22comp_op%22:%22eq%22,%22page%22:1,%22size%22:12,%22filters%22:%5B%7B%22field%22:%22geography_desc%22,%22type%22:%22like%22,%22value%22:%22tex%22%7D%5D%7D HTTP/1.1" 200 -
{'params': ['{"year":"2010","comp_op":"eq","page":1,"size":12,"filters":[{"field":"geography_desc","type":"like","value":"tex"}]}']} args
127.0.0.1 - - [03/Oct/2018 07:40:38] "GET /complex_table_data/list/?params=%7B%22year%22:%222010%22,%22comp_op%22:%22eq%22,%22page%22:1,%22size%22:12,%22filters%22:%5B%7B%22field%22:%22geography_desc%22,%22type%22:%22like%22,%22value%22:%22tex%22%7D%5D%7D HTTP/1.1" 200 -
```

**Desktop (please complete the following information):**
 openSUSE Leap 42.3
 Firefox 60.2.1esr (64-bit)

**Additional context**
As of now I do not have anything on the view end doing anything with the filter information, because of the above.

**Comment by olifolkerd** [comment] 2018-10-03 17:38
Hey @aklaver 

Thanks for getting in touch, and thanks for the detailed post there that was very hepfull.

The issue is arrising because there are a number of event bindings on the header element that come from the editor that trigger on text change, on blur, on enter etc. when each of this is called it is treated as a successful edit and the resulting success function is called.

This is fine when it is a text editor because Tabulator only pays attention to the first trigger and ignores the others. it is slightly harder in a header filter as users will be continually editing it.

I will have a look over the weekend and see if there is a way to streamline the process to prevent multiple requests. in the mean time as a work around, you could use a custom editor for your filter element, if you base it off the input formatter and remove the bindings that call "success" you should be all good.

Cheers

Oli :)

**Comment by aklaver** [comment] 2018-10-04 13:29
Thanks for the feedback. I will take a look at the custom editor solution. This code is for a talk a I will be giving on Tabulator to me my local Linux User Group in November so I have time to work it out.

**Comment by olifolkerd** [comment] 2018-10-04 18:11
Hey @aklaver 

Great to hear, i hope the group enjoy hearing about Tabulator :)

Im doing a patch release this weekend so you wont have to wait that long for the update.

Let me know if there are any other things u need a hand with.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2018-10-07 10:44
Hey @aklaver 

I have pushed a fix for this to the master branch, im looking to do a 4.1 release in the next week or two so i will include it in that.

Cheers

Oli :)

**Comment by aklaver** [comment] 2018-10-08 13:56
Got a chance to try out the changes. They seem to work. The only thing I see that is a potential issue is that when you move focus off the header filter it fires again.

**Comment by olifolkerd** [comment] 2018-10-09 07:04
Hey @aklaver 

I have just pushed an update to the master branch to ensure that it is only fired again if the value of the header filter changes.

Cheers

Oli :)

**Comment by aklaver** [comment] 2018-10-09 12:53
That did it! Thanks

**Closed** 2018-10-14 12:38 UTC
Labels: bug

**Comment by lpilon** [comment] 2018-12-11 21:08
Hi @olifolkerd, am just testing Tabulator and running into this issue. Using v4.1.3 from unpkg, Chrome 71/ MacOS. 

Columns are duplicated after scrolling right (more columns than fit on screen). Duplication is only once.

**Comment by aklaver** [comment] 2018-12-11 21:17
I think that might be a different issue. What I was referring to was the header filter firing multiple times when doing an Ajax call. If I am reading your issue correctly you are referring to the actual column being duplicated on screen, correct?
