### ISSUE TITLE
Upgrading from 5.1 -> 5.3: Maximum call stack size exceeded when using a custom ajax function

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3889] opened 2022-08-01 15:06 UTC
I've seen this crop up for older versions, but I see this when upgrading from 5.1 to 5.3. I've gone through the documentation and I can't find any upgrade instructions that I've missed.

![image](https://user-images.githubusercontent.com/279769/182180142-da7265b5-64db-49a7-a339-345f1a9c8457.png)

This seems to happen to me regardless of the size of the data, so maybe I'm doing something wrong?

This is when using the AJAX loader with a custom function. In other places in the app large datasets work fine.

I'll investigate to see if I'm doing something wrong.

**Comment by rathboma** [comment] 2022-08-01 15:21
Update: Everything works in `5.2.x`, just to help isolate this to changes in `5.3`.

**Comment by olifolkerd** [comment] 2022-08-01 15:39
Nothing was changed in the ajax functionality in the 5.3 release, so that was interesting. do you have an example of what you are doing in that function, could you confirm the exact property you are using?

As a side note, i would say that the custom ajax promise was only really added in 4.x to allow for async functionality that hadn't been accounted and that was the only way to do it. In 5.x the best approach would be to use a custom module that subscribes to data events to the return the required data when needed, a full example of this can be found in the [Module Examples Documentation](http://tabulator.info/docs/5.3/module-examples#db) 

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2022-08-21 09:43
Hey @rathboma 

Do you have an example of this so i can see it in action, i cant replicate it my end?

Cheers

Oli :)

**Comment by rathboma** [comment] 2022-08-22 19:50
Hey! I've been on holiday, so haven't had the time yet, and now catching up with boring real-life stuff that was on hold while I was away. Hopefully I can try and replicate next week!

**Comment by olifolkerd** [comment] 2022-08-22 20:14
All good, I've just got back off holiday myself, catching up on all my Tabulating

**Comment by JLGarber** [comment] 2022-08-26 18:08
I think the Ajax functionality might be a red herring. I ran into this issue myself when upgrading 5.2.7 -> 5.3.X. On my end it appears to be related to the `editable` property in column definitions. Specifically, if a column definition's `editable` property attempts to chain `getRow().getCell('someColumn')`, it overflows.

Demonstration of non-overflowing behavior under Tabulator 5.2.7: https://jsfiddle.net/pmun9d1v/1/

Demonstration of overflowing behavior under Tabulator 5.3.2: https://jsfiddle.net/2Lvwn7b3/

Demonstration of non-overflowing behavior under Tabulator 5.3.2, when using `getData()` in the `editable` property instead: https://jsfiddle.net/2Lvwn7b3/1/

(Tested in Chrome 104.0.5112.81 and Firefox 104.)

I haven't dug through the commit history to see when precisely this behavior changed, but it definitely was between 5.2.7 and 5.3.0.

**Comment by rathboma** [comment] 2022-08-26 20:20
@JLGarber ++ Thanks for posting. I do a lot of that stuff in my editing functionality, so sounds like a promising lead!

**Comment by olifolkerd** [comment] 2022-09-04 13:10
Hey @JLGarber 

Great spot there, You are 100% spot on there, that is where the issue is.

This is happening because in the 5.3 release a new `tabulator-editable` class was added to cells that were editable, as a result of this it now calls the editor function when the cell is instantiated to work out weather to show the class.

The knock on side effect of this is that if you call the `cell.getRow().getCell("blah")' logic here, it may be trying to access a cell that doesn't not exist yet because the row is in the process of being built. When Tabulator detects this it tries to reinstatiate the row to generate the cell and the loop begins.

@rathboma  For now the correct approach would be to move to using the the `getData` approach proposed by @JLGarber  which avoids the need to lookup the cell component.

```js 
cell.getData().blah
```

The more i investigate the PR that added the new 'tabulator-editable' the more i can see that it could cause quite a few niche problems going forward. i will look to reevaluate this functionality in the 5.4 release as im not sure weather i will keep it in at this point or completely rebuild it to avoid these sorts of issues. But for now the above workaround should resolve your problems.

Cheers

Oli :)

**Comment by JLGarber** [comment] 2022-09-05 03:06
Thanks Oli. Glad the bug report was enough to track things down!

**Comment by rathboma** [comment] 2022-09-09 19:32
Late to the party, but @JLGarber++ for finding this. I made my changes and it worked great.

**Comment by olifolkerd** [comment] 2022-09-25 11:23
Hey Everyone,

I have pushed a fix for this to the 5.4 branch. it now waits for the row to be initialized before checking the editable function on the cell, preventing the issue.

This should be released in the next week or so.

Cheers

Oli :)

**Closed by olifolkerd** 2022-09-25 11:23 UTC
Labels: Possible Bug

**Comment by JLGarber** [comment] 2022-09-27 01:15
Awesome to hear, thanks so much for looking into it, Oli!
