### ISSUE TITLE
Column headers misaligned after page change

### ISSUE THREAD

**Issue by jstale** [olifolkerd/tabulator#1169] opened 2018-05-31 09:01 UTC
Hi Oli, 
first of all thank you for all the great work you've put into this project!

I have an issue with column header alignment on page change when using remote pagination.
This happens if a table has many columns and horizontal scroll bar is displayed. When I scroll to the right and then change the page, the headers become misaligned. I think I saw others mention the same issue.

I recreated the issue using jsonplaceholder as a data source:
![image](https://user-images.githubusercontent.com/7878828/40772567-98c45408-64c0-11e8-91f8-c0dc79288cc5.png)

https://jsfiddle.net/jstale/zh6t8vvv/

**Comment by jstale** [comment] 2018-05-31 09:05
Forgot to add, as soon as I touch the scroll the headers become aligned again.

**Comment by jstale** [comment] 2018-06-01 19:30
Hi, 
in the project I used 3.5.1 but it's also happening on 3.5.2
You can see an example fidle here https://jsfiddle.net/jstale/zh6t8vvv/

And here's the constructor:
	$("#example-table").tabulator({
		height:"calc( 100% - 50px)",
		layout:"fitData",
		pagination:"remote",
		paginationSize:5,
		movableColumns:true,
		ajaxURL:"https://jsonplaceholder.typicode.com/posts", //ajax URL
		ajaxParams:{ _start: 1, _limit:5}, //ajax parameters
		ajaxConfig:"GET", //ajax HTTP request type
		ajaxResponse:function(url, params, response){
			var res = {
				"last_page":15,
				"data":response
			}

			return res;
		},
		columns:[
			{title:"Name", field:"userId"},
			{title:"Age", field:"id"},
			{title:"Gender", field:"title"},
			{title:"Height", field:"body"},
			{title:"Name", field:"userId"},
			{title:"Age", field:"id"},
			{title:"Gender", field:"title"},
			{title:"Height", field:"body"},
			{title:"Name", field:"userId"},
			{title:"Age", field:"id"},
			{title:"Gender", field:"title"},
			{title:"Height", field:"body"}
		]
	});
	
	$("#example-table").tabulator("setData");

**Comment by maklja** [comment] 2018-06-06 11:41
Hi Oli,

I am facing the same issue as @jstale jstale. My columns get misaligned after sort operation on any column if horizontal scroll bar is present.

After some debugging of tabulator.js, which is a great table, inside our application I came to the next conclusions:

1. Header element that contains class with name "tabulator-header" is outside of table body that contains row data. Table body is element with class name "tabulator-tableHolder". Table body is the one that has horizontal scroll.

2. Table body(tabulator-tableHolder) is listening on scroll event, on each scroll it notifies other components that scroll is in progress and allows them to update their position. One of those components is columnManager that is responsible for updating header element(tabulator-header) to a new scroll position, as far as I understand. This part works fine and on each scroll headers move as same as table row data.

3. But when we do sort, one of the first things that occur is resetScroll, which sets values to 0. This happens in RowManager in function setData, after which both scrollLeft for header and body have 0 value. Reset scroll to zero:
```javascript
// tabulator.js line 2583
this.resetScroll();

this._setDataActual(data);
```

4. After this all rows are deleted and recreated and I'm sure that you know better what this part of code does then me. :D

5. At the end function _parseRemoteData inside Page instance is called and here you restore scroll value to the rowManager by calling next lines:

```javascript
// tabulator.js line 17020
left = this.table.rowManager.scrollLeft;

this.table.rowManager.setData(data[this.paginationDataReceivedNames.data]);

this.table.rowManager.scrollHorizontal(left); // here value of the scroll is restored to table body

this.table.options.pageLoaded(this.getPage());
```

My fix for this issue is adding one more call to the columnManager to "tell" him to set new scroll postion on headers too:

```javascript
// tabulator.js line 17020
left = this.table.rowManager.scrollLeft;

this.table.rowManager.setData(data[this.paginationDataReceivedNames.data]);

this.table.rowManager.scrollHorizontal(left);

this.table.columnManager.scrollHorizontal(left); // new line to restore header scroll position

this.table.options.pageLoaded(this.getPage());
```
I'm not sure if this is the right solution, but for our application this is currently hot fix to prevent clients from experiencing this bug in production.

I will leave you git patch so you can preview my changes.
Once again tabulator is great library that was very easy to integrate into our project. Keep up the great work. :)

Best regards,

[Issue_1169.zip](https://github.com/olifolkerd/tabulator/files/2075957/Issue_1169.zip)

**Comment by jguitarz** [comment] 2018-06-07 20:41
Thanks for figuring that out maklja. I can confirm his proposed solution has fixed the issue on my end as well.

**Comment by olifolkerd** [comment] 2018-06-07 21:33
Hey @maklja 

Thankyou for your detailed explanation and proposed fix. It looks good to me.

I will run some tests over the weekend and get a patch release out.

Cheers

Oli :)

**Comment by maklja** [comment] 2018-06-25 06:53
Hi @olifolkerd,

That's great news. I am glad I was able to help. :)
My team and me will update tabulator to new version today in our application.

Best regards from me and my team at Schneider Electric :)

**Comment by RyhillSibaprasad** [comment] 2018-11-14 10:03
Hi Oli,


Thank you for all the great work you've put into this project!

I have an issue with column header horizontal row alignment on page change when using button ascending and descending .
This happens if a table has many columns and horizontal scroll bar is displayed. When I scroll to the right and then click header button ascending and descending, the headers horizontal row become misaligned.

**Comment by RyhillSibaprasad** [comment] 2018-11-14 10:20
Hi Oli,
Thank you for all the great work you've put into this project!

I have an issue with column header horizontal row misaligned on page change when using button ascending and descending .
This happens if a table has many columns and horizontal scroll bar is displayed. When I scroll to the right and then click header button ascending and descending, the headers horizontal row become misaligned. 


And here's my code 



       {
            $timeout(function(){ 

                var layoutPlan = "fitData";
                if(columns_arr.length >= 10){
                    layoutPlan = "fitDataFill";
                }else{
                    layoutPlan = "fitColumns";
                }
                $("#example").tabulator({    
                    pagination:"local",
                    paginationSize:30,                
                    layout:layoutPlan,
                    resizableColumns:true,
                    tooltips:true,
                    selectable: true,
                    tooltipsHeader:true,
                    groupToggleElement:"header",
                    groupBy : grp_by_field,
                    initialSort : sort_arr,
                    groupClosedShowCalcs:true,
                    columns : columns_arr
                });
                
                if(angular.isDefined($scope.selected_rep_obj.filters)){
                    $("#example").tabulator("setFilter", $scope.customFilter, filters_arr);
                };
                $("#example").tabulator("setData", reformatData_matters(report_results, report_sub_categories));

            });
        };





![misalign](https://user-images.githubusercontent.com/37332145/48476356-d4b68c00-e824-11e8-81a2-38596bab3aa3.jpg)

**Comment by olifolkerd** [comment] 2018-11-14 19:36
Hey @RyhillSibaprasad 

Would you mind createing a new issue using the bug template, it will include all the info need to help you out there.

Cheers

Oli :)

**Closed** 2018-11-14 19:35 UTC
Labels: bug

**Comment by RyhillSibaprasad** [comment] 2018-12-17 10:11
hai Olli,
thanks to giving such a good answers in Tabulator

my issue is when i'm generating my Report in Tabulator version - 3.5.3. the column calculation is generating every page (Pagination) my requirement is it will show only in Last Page can u help this issue  ?
![page_2](https://user-images.githubusercontent.com/37332145/50080472-28483b00-0212-11e9-9ef7-522dd4e7bb14.jpg)
![page_3](https://user-images.githubusercontent.com/37332145/50080473-28483b00-0212-11e9-8b73-4617783c3071.jpg)
![page_1](https://user-images.githubusercontent.com/37332145/50080474-28e0d180-0212-11e9-9255-81d1e47d34c6.jpg)

**Comment by uaturk** [comment] 2021-10-31 10:58
Hello,
I had the same issue with tabulator.min.js v5.0.6 (https://github.com/olifolkerd/tabulator/issues/1169#issuecomment-395039313).
My fix is like that:
table.on( "headerClick", function(){
	table.columnManager.scrollHorizontal( 'left' ); // new line to restore header scroll position
} );
Thanks..

**Comment by olifolkerd** [comment] 2021-10-31 16:36
Hey @uaturk 

If you are having trouble, please raise a new issue, this issue was closed over 3 years ago and the codebase as been completely rebuilt twice since then, it is almost certainly completely unrelated to this issue.

Cheers

Oli :)
