### ISSUE TITLE
Changing reactive data incorrectly displays the rows in the group

### ISSUE THREAD

**Issue by smiheev** [olifolkerd/tabulator#3018] opened 2020-10-01 09:11 UTC
Hello!

**Describe the bug**
When insert row with splice method on Reactive Data Array in Tabulator with Data Grouping enabled I get incorrect result.

**Tabulator Info**
4.8.2

**Working Example**
https://jsfiddle.net/tf4ke3x8/8/

**To Reproduce**
A step by step guide to recreate the issue:
1. Go to https://jsfiddle.net/tf4ke3x8/8/
2. Type the value to the empty row in the 'Group 1'.
3. Press the Tab key or Enter.
4. Tabulator does not display the order of rows correctly (empty row is on top in the group).

**Expected behavior**
The order of displayed rows must match the array (tableData).

**Comment by olifolkerd** [comment] 2020-10-01 19:18
This is a duplicate of #2958

**Closed by olifolkerd** 2020-10-01 19:18 UTC
Labels: Duplicate
