### ISSUE TITLE
Horizontal scrollbar does not appear in the wide empty table

### ISSUE THREAD

**Issue by woxcab** [olifolkerd/tabulator#1608] opened 2018-11-27 22:03 UTC
**Describe the bug**
If a table is wide and empty then expectable horizontal scroll bar isn't shown.

**Tabulator Info**
- Tabulator 4.1.2
```javascript
let table = new Tabulator('#table', {
  columns: [{
    field: 'column1', 
    title: 'Column 1',
    width: 200
  }, {
    field: 'column2', 
    title: 'Column 2',
    width: 500
  }, {
    field: 'column3', 
    title: 'Column 3',
    width: 1000
  }]
})
```
https://jsfiddle.net/dveb5Lhr/

**To Reproduce**
1. Define table without rows that's wider than outer block.
2. See on the result table in the browser.
3. Table header is wider than outer block but horizontal scrollbar doesn't appear in the table holder.

**Expected behavior**
Horizontal scrollbar should be shown in the table holder in order to scroll table header.

**Screenshots**
Empty table without expected scrollbar: 
![screenshot_20181128_005700](https://user-images.githubusercontent.com/16160665/49114225-bb8fef80-f2a8-11e8-9225-a5416ebf2b82.png)

Same table with rows:
![screenshot_20181128_005734](https://user-images.githubusercontent.com/16160665/49114224-baf75900-f2a8-11e8-81f5-ec4c5eba54a1.png)

**Desktop:**
 - OS: LinuxMint 18.3
 - Browsers: Chromium 58.0.3029.110, Firefox 63.0.3

**Comment by olifolkerd** [comment] 2018-11-27 22:09
Hey @woxcab 

Sorry to hear you are having issues, could you confirm that the issue is present in the latest 4.1.3 release, as you seem to be running on the 4.1.2 code in your example.

If it is still present i will happily look at fixing that one ASAP.

Cheers

Oli :)

**Comment by woxcab** [comment] 2018-11-27 22:34
Hey @olifolkerd 
Yes, it's reproducible in 4.1.3: https://jsfiddle.net/dveb5Lhr/1/

**Comment by olifolkerd** [comment] 2018-11-27 22:35
Thanks for checking, i will add that to the fix list for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2018-12-16 14:45
Hey @woxcab 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2018-12-16 14:45 UTC
Labels: bug

**Comment by woxcab** [comment] 2018-12-16 14:59
Thank you!
Updated JsFiddle: https://jsfiddle.net/dveb5Lhr/4/  
Commit link for history: https://github.com/olifolkerd/tabulator/commit/4d2f303e6798aa184a0704ac77491c9ce8443066

**Comment by OksanaRomaniv** [comment] 2018-12-24 18:01
Hello,

I'm having the related issue I think with tabulator-tables 4.1.4. I have a wide table (native width approximately 5000px). When I call the constructor with the next code:

```
new Tabulator('.es-table-paginate', {
	pagination: 'local',
	paginationSize: ESPRO_settings.tabulator_front_paginate,
	responsiveLayout: true,
});
```

The table fits the content width only when I see it's initial width via JS before initializing and the horizontal scrollbar never appears. Could you please advice what I can do to create wide scrollable tables?

Thank you!
