### ISSUE TITLE
cellTap on small tablets not working

### ISSUE THREAD

**Issue by LloydNicholson** [olifolkerd/tabulator#1783] opened 2019-02-08 11:35 UTC
**Tabulator information**
Tabulator version - 4.1.4

**Copy of Constructor object**
`let cashReceiptsJournalTable = new Tabulator("#CashReceiptsJournalAnswerArea", {
    data: crjAnswerData, //array i use to create the empty table
    layout:"fitColumns",      //fit columns to width of table
    tooltips:true,            //show tool tips on cells
    addRowPos:"top",          //when adding a new row, add it to the top of the table
    history:true,             //allow undo and redo actions on the table
    columnVertAlign:"bottom",
    headerSort:false,
    columns:[                 //define the table columns
        {title: "Doc", field: "document", cellEdited: checkCRJDocument, width:65, editor:"input", validator: ["string"], headerSort:false},
        {title:"Date", field:"date", cellEdited: checkCRJDate, width:75, editor: "input", validator: ["integer", "min:1", "max:31"], headerSort:false},
        {title:"Details", field:"details", cellEdited: checkCRJDetails, width:150, editor:"input", validator: ["string"], headerSort:false},
        {title:"Fol", field:"folio", width:60, editor:"input", validator: ["string"], headerSort:false},
        {title:"Analysis of <br>Receipts", field:"analysisOfReceipts", width:120, editor:"input", validator: ["integer", "min:1"], headerSort:false},
        {title:"Bank", field:"bankValue", cellEdited: checkCRJBank, width:80, editor:"input", validator: ["integer", "min:1"], headerSort:false},
        {title:"Current income", field:"currentIncome", cellEdited: checkCRJCI, width:140, editor:"input", validator: ["integer", "min:1"], headerSort:false},
        {title:"Sundry", field:"sundry",columns: [
                {title:"Account", field:"account", cellEdited: checkCRJSundryAccount, align: "left", editor:"input", validator: ["string"], headerSort:false},
                {title:"Amount", cellEdited: checkCRJSundryAmount, field:"amount", align:"right", editor:"input", validator: ["integer", "min:1"], headerSort:false}
            ],
        },
    ],
});`

**To Reproduce**
1. Go to 'www.kidcon.co.za'
2. Click on 'journals or accounting equation'
3. Scroll down to 'CRJ or any journal or the accounting equation'
4. When I use a small tablet, specifically a Lenovo Tab 3 the `cellEdited` function doesn't work as a callback. It keeps jumping back out of the cell and won't allow it to be edited.

**Expected behavior**
I want to edit the cell on tablets the size of a Lenovo Tab 3.

**Tablet:**
 - Device: Lenovo Tab 3
 - OS: Android version 5.0.0
 - Browser: Chrome
 - Version: 72

**Smartphone:**
 - Device: Huawei P20 lite
 - OS: Android version 8.0
 - Browser: Chrome
 - Version: 70

**Comment by olifolkerd** [comment] 2019-02-08 17:46
This is a duplicate of #1732 and will be fixed in the 4.2 release on monday

**Closed by olifolkerd** 2019-02-08 17:46 UTC
Labels: duplicate

**Comment by LloydNicholson** [comment] 2019-02-08 20:18
Thanks and great work on your library. It’s aweosme.
