### ISSUE TITLE
Row selection is not persistent when sorting or filtering

### ISSUE THREAD

**Issue by nvanderburg** [olifolkerd/tabulator#3456] opened 2021-11-05 10:51 UTC
**Describe the bug**
Selection is not persistent when sorting or filtering,  however [documentation](http://tabulator.info/docs/5.0/select#setup-persistent) states: "By default Tabulator will maintain selected rows when the table is filtered, sorted or paginated" 

**Tabulator Info**
Version 5.0.7

**Working Example**
https://jsfiddle.net/4py7s68j/2/

**To Reproduce**
Select some rows
Sort any field

**Expected behavior**
Previously selected rows should remain selected, however selection is lost

Version 4.9.3 of Tabulator doesn't have this issue:
https://jsfiddle.net/qe1vd0Lg/2/

**Comment by rain01** [comment] 2021-12-17 21:36
Related/same: https://github.com/olifolkerd/tabulator/issues/3495

**Comment by olifolkerd** [comment] 2021-12-19 14:25
Hey @nvanderburg 

Looks like there was a regression in the 5.0 release that prevented the default value being taken into account. I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2021-12-19 14:25 UTC
Labels: Possible Bug
