### ISSUE TITLE
double-click on column heading to fit-to-contents should make smaller

### ISSUE THREAD

**Issue by gillez** [olifolkerd/tabulator#1616] opened 2018-12-03 11:31 UTC
#771 requests a feature to fit-to-contents on double-click of column heading border.  This was implemented in v3.4 and works fine when the column width needs to be increased.  However, it doesnt make the column widths smaller if the maximum data width is less than the contents.  

Is there a reason why it works in this way?  If not, can it be changed to do this?  I am happy to look into it myself and submit a push request (if I can fix it) if it's not already on the road map.

Thanks,
Giles

**Comment by gillez** [comment] 2018-12-05 10:43
Thanks for the update Oli.  It's great that this will be fixed so quicky.  I appreciate your good work.

Whilst you're in that area, one other minor thing that we noticed is that the area that you can press or double-click to resize columns covers a few pixels either side of the line but if the mouse is over the actual line itself, the cursor changes back to the pointer and you can't resize.  As you move the mouse over, you see the cursor change to the resize, flicker back to the pointer, then back to the resize again.  If you (by chance) stop on the middle, you can't resize and have to move it.  It's a very minor point but it's slightly disconcerting, so if there's an easy fix it would be appreciated.

Just looking at the elements in the developer console, I would guess it's because the mousemove events are being triggered on the tabulator-col-content div rather than the tabulator-col div so an easy fix might be just to move the element that these events are triggered on.  I haven't tried this yet so don't know whether it would work or whether there are any other implications/side-effects of this.  If it causes any problems, please ignore.

Cheers,
Giles

**Comment by olifolkerd** [comment] 2018-12-16 10:05
Hey @gillez 

I have pushed a fix to master for the column shrinking issue and will include it in this evenings patch release. Looks like it was a regression caused in the 3.0 to 4.0 conversion.

As for the second issue you raise, that one is actually a lot more complicated because it is handled in rows as well as headers and columns can be moved about on the table. It is certainly on my list to resolve but probably wont be done for a couple of releases yet.

Cheers

Oli :)

**Closed by olifolkerd** 2018-12-16 10:05 UTC
Labels: bug

**Comment by gillez** [comment] 2018-12-17 14:44
Thanks for this fix Oli.  I thought the second point may not be that easy to fix, but wanted to bring it to your attention just in case you could do something about it.
