### ISSUE TITLE
tabulator-frozen-rows-holder width

### ISSUE THREAD

**Issue by python3Berg** [olifolkerd/tabulator#4046] opened 2022-11-30 13:11 UTC
Just upgrading from 4.9 to 5.4. So far love it...so many things more clear and so many past limits enhanced. One issue I've noticed...

When freezing rows and columns, there is an edge condition when scrolling horizontally. Both table-headers and table-holder are rendered with an explicit width of x. Element tabulator-frozen-rows-holder is defined only with a min-width of 600%. For very wide tables, this ultimately leads to a breakdown of column freezing where it is overwritten when scrolling past the 600% limit.

To address this, I explicitly set tabulator-frozen-rows-holder.width = tabulator-headers.width on tableBuiilt.

Just FYI. I have everything apparently working with this work-around

**Comment by Alex-Github-Account** [comment] 2022-12-01 05:46
This is a free open source project, you need to be realistic in your expectations for when things will be actioned. We all have things going on outside Tabulator and will respond when practical.

There will be a patch release in early December and it may get reviewed then.

Please can you use the issue template and provide a js fiddle, without seing how your table is setup it is impossible to offer advice on where the issue may lie. If you fill in the template you may find that your issues get responses a lot faster as it is far easier to get to the heart of the problem

Cheers

Oil

**Comment by olifolkerd** [comment] 2022-12-01 08:04
Hey @python3Berg 

Thanks for getting in touch, and thanks for the kind words about Tabulator, it is great to hear you are enjoying things.

Im a bit confused by your description, it sounds like your are using a lot of frozen columns there, once you have more frozen columns than the width of the table it would become non-functional anyway. so i think i might have got the wrong end of the stick there.

Could you put together a JS Fiddle that demonstrates the issue, it would be great to see this in action so i could understand the issue you are facing better.

Cheers

Oli :)

**Comment by python3Berg** [comment] 2022-12-01 15:44
I will try to put fiddle together.

To clarify, I have one frozen column and one frozen row.  Its a wide table with many columns outside initial view. When querying tabulator components:
.tabulator-header.width = 1522
.tabulator-headers.width = 30,000
.tabulator-tableHolder.width = 1522
.tabulator-table.width = 30000
.tabulator-frozen-rows-holder.width = 9500.

Most of this makes sense...the visible containers are at visible screen width wihile the content is larger. The quirk is frozen rows holder. It is content so arguably should be the same width as other content elements. Because it is not, the frozen column of the frozen row is scrolled away once we get to its specified minimum width. 

It seems the default css for this element is min-width: 600%. This will work for most tables but not ones with wide content. I have made work by simply setting this width explicitly to match other content elements.

I have no urgent bug. This is simply something I discovered and I though heads-up could be helpful

**Comment by olifolkerd** [comment] 2023-02-18 17:37
Hey @python3Berg 

Is there any chance you can put togeather a JS Fiddle for this, i really need to see your table in operation to understand the issue,

It doesnt need to match your production environment, it just has to be a minimal example that demos the issue.

Cheers

Oli :)

**Comment by python3Berg** [comment] 2023-02-18 17:39
Just posted...Thanks

**Comment by python3Berg** [comment] 2023-02-18 17:41
To be clear, I am using a scroll wheel. Of course pulling the scroll bar 
works fine

**Comment by olifolkerd** [comment] 2023-02-18 17:42
is this a duplicate of #4061?

**Comment by python3Berg** [comment] 2023-02-18 17:47
Different issue. With respect to horizontal scrolling when frozen 
columns, there is a fixed max width in your css on 
tabulator--frozen-rows-holder that causes the frozen column to 
eventually scroll off screen for very wide tables. I address it by 
setting this on tableBuilt to the actual width of my data.

**Comment by olifolkerd** [comment] 2023-02-18 17:50
@python3Berg  Then do you have a fiddle of this please, i have used some extremely wide tables and not run across this issue so i relly need to see a fiddle of this in action to get it resolved.

You mentioned above that you posed a fiddle, but there was no link, and the fiddle in the other issue does not demonstrate this problem.

Cheers

Oli :)

**Comment by python3Berg** [comment] 2023-02-18 17:56
Signals crossed. Fiddle addressing different niche problem :).
https://jsfiddle.net/vp5Lf27j/3/

scroll to right...

**Comment by olifolkerd** [comment] 2023-02-19 13:09
Hey @python3Berg 

Thankyou, that was very helpful.

I have pushed a fix for that to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2023-02-19 13:09 UTC
Labels: Possible Bug
