### ISSUE TITLE
android editor not working

### ISSUE THREAD

**Issue by yasukame** [olifolkerd/tabulator#1455] opened 2018-09-26 08:13 UTC
When "editor" is used in android, it will be displayed immediately with a soft keyboard, but it will disappear and can not be entered.
It seems that focus can not be entered by moving to soft keyboard.
Is there a solution?

$("#table").tabulator({
    layout: "fitColumns",
    columns: [
      { title: "name", field: "name", editor: "input" },
    ]
});

**Comment by olifolkerd** [comment] 2018-09-26 17:40
Hey @yasukame 

Thanks for getting in touch, 

Could i ask that when you raise future issues you use the template provided as it will prompt  you for the information needed to resolve a bug, The reason i ask is that in order to resolve an issue it is often necessary to know more about your setup, such as the browser you are using (not just the OS), the version of Tabulator you are using etc.

In answer to your question, If you click in the input field a second time you should be able to type.

I will have a look into what is going on over the weekend and see if i can improve the experience.

Cheers

Oli :)

**Comment by yasukame** [comment] 2018-09-27 00:07
Hi, thanks for your prompt response.

tabulator version 3.5
tabulator version 4.0

android version 4.4.4
android chrome version 68.0.3440.91

thanks.

**Comment by yasukame** [comment] 2018-09-29 07:13
Hi, My problem has been solved.

tabulator ver 3.5
tabulator.js 17800 line

table.element.tabulator("redraw");
to
// table.element.tabulator("redraw");
I made a comment.

android worked.
thanks!

**Comment by olifolkerd** [comment] 2018-09-29 10:16
Hey @yasukame 

Thanks for the pointer to the source of the issue that was very helpful,

That is actually part of the resize binding that helps prevent visual corruption when the page is resized. simply removing it will certainly fix your problem, but will sadly break the table on screens that can be resized.

But now that you have found where the source of the issue is it will be really easy for me to fix it, i will release a fix for this in this weekends patch release.

Thanks for the investigative work!

Cheers

Oli :)

**Closed** 2018-09-30 12:48 UTC
Labels: bug, question
