### ISSUE TITLE
tabulator("destroy") not remove the old table and columns

### ISSUE THREAD

**Issue by rri195** [olifolkerd/tabulator#777] opened 2017-12-18 00:59 UTC
I have 2 tables, after destroy the 1st table and initialize the 2nd table, the columns in 1st table shows in the 2nd table

please see example here.

**Thanks for the reply, but I tried to wait the 1st table is build then destroy it, still not work. see link below**

https://jsfiddle.net/odmg2wnd/6/

**Comment by olifolkerd** [comment] 2017-12-26 11:03
This looks like you have found a bug in the HTML parsing system, i will look to fix this in the next release

**Comment by olifolkerd** [comment] 2017-12-26 12:19
This is a duplicate of #774

**Closed by olifolkerd** 2017-12-26 12:19 UTC
Labels: duplicate
