### ISSUE TITLE
Various issues with column resizing

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#2505] opened 2019-11-27 19:56 UTC
Hi @olifolkerd,

I've starting using the column resizing functionality in Tabulator, and in doing so I've encountered several issues.  Let me know how you would like to track these.  For now I'm filing as one issue, so as not to flood your system with many issues.  All of these are demonstrated with a single JS Fiddle on Tabulator 4.5.1.  If you'd prefer, I can close this and file individual issues on the ones that you agree are bugs or worthwhile enhancements.  Just let me know!

**Tabulator Info**
Tabulator 4.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 78

**Working Example**
https://jsfiddle.net/blankbadge/9ctf3xhe/

**To Reproduce**
All issues are reproducible as described below using the provided JS Fiddle.  It has two variables defined at the top of the .js file that are relevant to reproducing these issues.  The variable 'groupColumns' enables or disables column groups (grouping every five columns).  The variable 'resizeFirstColOnly' allows resizing of all columns when false, but only enables resizing on the first column ('Col 0') when true.

**Describe the bug**
Five separate issues related to column resizing:

(1) When using column groups, the right-side of the column resize handle is missing in the first group only.  To reproduce, set groupColumns=true and resizeFirstColOnly=false.  You should observe that Col 0 through Col 3 only have a resize handle on the left-side of the column separator, but not the right-side.  The cause seems to be that div.tabulator-col-resize-handle.prev is set to display:none only for those columns.  The issue does not affect the last column in the first group (Col 4), nor does it affect any columns from the other groups (Col 5 - Col 99).  Expected behavior is that the column handles behave the same for all columns in all column groups, with a handle on both sides of the column boundary.

(2) Setting 'resizable' on individual columns does not work correctly with column groups.  To reproduce, first run with groupColumns=false and resizeFirstColOnly=true.  You should observe that only Col 0 can be resized, as expected.  Then, change groupColumns to true.  Now, you should observe that Col 0 can still be resized as expected.  But Col 1 through Col 99 can also be resized.  Expected behavior in both scenarios is that only Col 0 should be resizable.

The remaining three items are smaller UI issues related to the display of the ew-resize cursor icon when hovering over column boundaries or actively resizing columns.  All can be demonstrated by setting groupColumns=false and resizeFirstColOnly=true.

(3) The ew-resize cursor icon is used even for non-resizable columns.  With the variable settings from above, only the first column is resizable, but you should observe that hovering the mouse over the other non-resizable column boundaries still shows that ew-resize cursor icon, as though they are resizable.  Clicking on them will show that indeed they cannot be resized, but the icon displayed is misleading.  Expected behavior would be that non-resizable columns do not show the ew-resize cursor icon when hovering over the column boundary.

(4) There seem to be two handles for resizing on the column boundary, one on the left side and one on the right side.  But they are non-overlapping and do not fully connect.  If you very slowly move your mouse pointer from left to right on a resizable column, you should observe the cursor change to ew-resize when it first hits the left handle.  Then at the very center point of the column separator line, there is a pixel where you cannot resize, and the mouse icon reverts to the pointer icon.  Then as you keep moving the mouse, it switches back to the ew-resize icon again when the right-side handle is encountered.  It is a small issue, but would be a little cleaner if the handles overlapped in such a way that the column is resizable even when the mouse is dead-center on the column boundary.

(5) When actively resizing a column (i.e. left-click and hold on the column boundary), the ew-resize icon is only shown when the mouse is still over the column boundary.  If you click and drag quickly, the mouse movement gets ahead of the screen rendering for a fraction of a second, and you can see the mouse icon revert to the pointer icon briefly.  Then when the column boundary rendering catches up to the mouse pointer, it switches back to the ew-resize icon.  In most applications, when you click and drag like this, it maintains that ew-resize icon while you are holding down the left-click on the mouse, even if the mouse movement momentarily gets ahead of the column boundary rendered to the screen.  

**Expected behavior**
Expected behavior is described above for each of the five items.

Thanks!
James

**Comment by 805bluebell** [comment] 2019-11-29 10:10
1. Could not reproduce the bug. It's working as expected. [Demo here.](https://jsfiddle.net/opankajkumar/bz8w47yc/4/)
2. It is surely a bug when you think of the group as a whole. It's obvious to expect that behavior out of column of columns. But it doesn't works like that. Each column requires setting `resizable` variable to be set explicitly. So, you can set `resizable: false` for every fourth column to get an effect.  [Demo here.](https://jsfiddle.net/opankajkumar/bz8w47yc/23/)

**Comment by olifolkerd** [comment] 2019-12-08 15:26
Hey @blankbadge 

Thanks for getting in touch. I wouldnt consider any of these bugs as such, but i agree there is room for enhancement of the features and in fact most of the issues you discuss are already on the roadmap for future inclusion, most likely in the v5 release.

In response to your comments:

1.  I agree with @805bluebell i am unable to reproduce the discribed bug
2. I agree with @805bluebell on this, i  think this is more down to a misunderstanding of how the column resizing works.
3. I agree this is poor UI, it is basically the result in a way the columns are currently built and makes it easier to handle movable columns. It will be fixed when the render system is rebuilt in the v5 release
4. This is absolutely correct as the resize handles are added to the inside edges of the cell. there are a few complicated legacy reasons for why this is. but it is also scheduled for being updated in the v5 renederer update.
5. This is directly related to point 4. it only shows the icon when the mouse is hovering over the handles.

Thanks for your feedback

Cheers

Oli :)

**Comment by 805bluebell** [comment] 2019-12-08 17:32
@olifolkerd 
Where do we keep roadmap for next versions? I would to volunteer some work there.

**Comment by blankbadge** [comment] 2019-12-08 21:07
Hi @olifolkerd and @805bluebell,

Thanks very much for your feedback!  Regarding items 3-5 on the UI of the column resizing handles/icons, I'm very glad to hear you are targeting such improvements for v5.  I am looking forward to that release.

Regarding item 2, I'm sorry for wasting your time on this one... I discovered a bug in my JSFiddle that caused the issue I was seeing.  There is no problem in column-based resizing when I correct my bug, it works exactly as I would expect.  

On item 1, that is strange that you both cannot reproduce it.  I did some more investigation, because I thought it must be specific to my configuration.  But I still consistently see it happening, on three different machines in Chrome, two versions of Firefox, Edge, and Safari.  I observe the behavior with the following browser/OS:

Chrome 78 / Windows 10 Enterprise v1803
Firefox 70 / Windows 10 Enterprise v1803
Edge 42 / Windows 10 Enterprise v1803

Chrome 78 / Windows 10 Home v1903
Firefox 56 / Windows 10 Home v1903

Safari 11.0.3 / macOS 10.13.3

It's still the same behavior as I described above: that with groupColumns=true, "Col 0" through "Col 3" in the first column group "Group 0" don't have a visible right-side resize handle.  There is a "display: none" style coming in from CSS selector ".tabulator .tabulator-header .tabulator-col:first-child .tabulator-col-resize-handle.prev" for just those first four columns.  Here is what I see for the column border to the right of "Col 0":

![image](https://user-images.githubusercontent.com/57735852/70395986-184cdc80-19ca-11ea-8d91-20e41697e8ef.png)

By contrast, if I look at the column border to the right of "Col 5", I see the expected behavior of a clickable right-side resize handle, because that CSS selector isn't applied and it has "display: block":

![image](https://user-images.githubusercontent.com/57735852/70396011-6366ef80-19ca-11ea-99fe-2574133034fe.png)

I can see this on my original JSFiddle:

https://jsfiddle.net/blankbadge/9ctf3xhe/

As well as @805bluebell's (which is a fork of mine above):

https://jsfiddle.net/opankajkumar/bz8w47yc/4/

Can you take one more look and see if you can reproduce, maybe on a different machine or browser?

Thanks very much!
@blankbadge

**Comment by olifolkerd** [comment] 2022-04-03 14:29
I have just pushed an update to the 5.2 branch that completely rebuilds the `ResizeColumns` module.

It now uses a single resize handle that is positioned outside the cell to prevent any boundary issues. This should resolve all items outlined in this issue.

I will be included in the 5.2 release later this month.

Cheers

Oli :)

**Closed by olifolkerd** 2022-04-03 14:29 UTC
Labels: Enhancement

**Comment by blankbadge** [comment] 2022-04-06 14:42
Thanks very much, Oli, I'm looking forward to trying it out :)

-james
