### ISSUE TITLE
Cannot edit cells from mobile devices

### ISSUE THREAD

**Issue by niddu85** [olifolkerd/tabulator#1732] opened 2019-01-16 23:00 UTC
When editing cells on mobile devices (in my case Android) it is impossible to get focus on the wanted cell.
Replicable using the online demo available www.tabulator.info and Chrome for Android
version 71.0.3578.99
Android 8.0
![img_20190116_235553](https://user-images.githubusercontent.com/28997550/51284169-e49c4900-19ea-11e9-8292-fcd3899aa2cb.jpg)

**Comment by olifolkerd** [comment] 2019-01-16 23:05
It is working fine for me. I have just tried it on two separate Android
devices without issue.

What happens when you click on the cell?

Cheers

Oli

**Comment by niddu85** [comment] 2019-01-16 23:14
The cursor enters for a while in the cell, the keyboard appears and then disappears and the focus is lost.
Which are your devices/browsers?

**Comment by niddu85** [comment] 2019-01-17 06:39
Same issue on 2 xiaomi devices (mi5 and redmi note 4) and Amazon kindle fire using gboard and SwiftKey

**Comment by niddu85** [comment] 2019-01-17 09:35
Here attached the screen recording of the issue

[Screenrecorder-2019-01-17-10-21-24-779.zip](https://github.com/olifolkerd/tabulator/files/2767968/Screenrecorder-2019-01-17-10-21-24-779.zip)

**Comment by Fab-atka** [comment] 2019-01-17 13:46
Hi Oli,
Congratulations on this excellent tool.
I can confirm this issue on android phone and android tablets using chrome and firefox.
I am using Tabulator v4.1.5
For me it seems to be the same issue as #1455 was. The keyboard appears for half a sec and then disappears. I could not change the fields that require a keyboard on tabulator.info either.

**Comment by Iocere** [comment] 2019-01-19 12:54
Same issue for me on multiple devices/browsers.

Keyboard appearing for a short time and disappering. Somtimes stays open but closing on a key press like its losing focus.

**Comment by olifolkerd** [comment] 2019-01-20 22:46
Hey All,

I have gotten to the bottom of what is going on here. fixing this bug causes another bug, so for the last couple of releases it looks like i have been toggling the fix on and off lol.

The 4.2 release should be out in a couple of weeks, i will make sure a fix for this is included then.

Cheers

Oli :)

**Comment by niddu85** [comment] 2019-01-21 06:55
Great!! Thanks so much!

**Comment by olifolkerd** [comment] 2019-02-09 15:08
It turns out this wasnt a bug as such, it was a handover from version 3.5.

I was confused because i was testing on the examples pages which work fine, it was only the home screen that was affected.

On the page that held the Tabulator there was a ***table.redraw()*** function bound to the window redraw event which was triggering a redraw of the table when the keyboard opened, ending the select.

The binding wasn't needed because as of version 4,0 Tabulator manages that for you.

I have removed the erroneous line in on the homescreen for the new version of the website i will be launching with version 4.2 on monday.

Thanks for the feedback.

Cheers

Oli :)

**Comment by niddu85** [comment] 2019-02-10 20:59
i tested it and it works great!
thanks for your help

**Comment by endoram** [comment] 2019-02-23 06:59
I have a basic table set up to allow editing and I'm having the problem with keyboard flashing while trying to edit on mobile. However on the main [site](http://tabulator.info/) I can edit the table with no flashing keyboard.

Using Android version 9 with web browser chrome Version 72.0.3626.105 with Tabulator 4.2.1

I'm I missing something? If so what?
Thanks

**Comment by endoram** [comment] 2019-02-23 18:36
Ok got it working just needed to give the table a height

**Comment by adryx92** [comment] 2019-04-12 13:15
Hi, I'm testing editing on mobile and it only seems to work on Blink-based browsers (I've tested it on Opera), while on Firefox it still shows the same issue.
[See demo here](https://www.dropbox.com/sh/czgbkddq66xgony/AABb6mg6_YUyJL66In0eSX8Ua?dl=0)

**Comment by olifolkerd** [comment] 2019-04-13 09:30
Hey @adryx92 

Which version of Tabulator are you using?

**Comment by adryx92** [comment] 2019-04-15 06:43
> 
> 
> Hey @adryx92
> 
> Which version of Tabulator are you using?

I'm using the last version (4.2.5). Could you reproduce the issue?

**Comment by W00ler** [comment] 2019-04-15 11:52
@adryx92 I had the same issue on Chrome for Android and latest tabulator, but option `autoResize: false` fixed it.

**Comment by rtman** [comment] 2019-04-18 18:41
@olifolkerd I'm also facing this issue in the latest tabulator version 4.2.5, while testing on chrome v73.0.3683.90) on a Redmi Note 4 running android 7.0

**Comment by rtman** [comment] 2019-04-18 20:44
After tweaking the settings I have mobile keyboard working with 

```
                resizableColumns: false,
                layout: 'fitColumns',
                autoResize: false
```

Seems like `autoResize `is what did it. However it doesn't go full width on desktop anymore, so I'd like to be able to get that back. Similarly the headers row isn't frozen, any ideas?

Here's my tabulator css

```
.formContainer {
    /*padding: 16px;*/
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    /*height: 100%;*/
}
.tabulator {
    box-sizing: border-box;
    max-height: 100%;
    position: relative;
    border: 1px solid #333;
    background-color: #222;
    overflow: auto;
    font-size: 14px;
    text-align: left;
    -ms-transform: translatez(0);
    transform: translatez(0);
    background-color: var(--darkGray);
    /* background: none; */
    box-shadow: 0px 2px 10px 0px var(--black);
    border-radius: 8px;
    border: none;
}
```

Here's how I'm calling the tabulator

```
            <div className={'formContainer'}>
                <input
                    className={'formInput'}
                    name="filterValue"
                    value={filterValue}
                    onChange={this.onChangeFilter}
                    // onBlur={() => this.validateUserName(userName)}
                    type="text"
                    placeholder="Search ..."
                />
                <ReactTabulator
                    ref={this.reactTabulatorRef}
                    rows={rows}
                    columns={columns}
                    options={tabulatorOptions}
                />
            </div>
```

(this is with manually creating a tabulator instance in react via the docs btw)

**Comment by adryx92** [comment] 2019-04-19 07:32
It seems that <code>autoResize: false</code> does the trick.

**Comment by rtman** [comment] 2019-04-25 01:19
Just to update, I got the frozen header working by putting `height: 100%` on the tabulator instance and removing `max-height:100%` from my css

**Closed** 2019-07-21 18:14 UTC
Labels: Website

**Comment by JaumeAG** [comment] 2023-09-27 14:31
Hi, I am using version 5.4 and I still have the error, the "resize" does not correct the error

**Comment by atorres16** [comment] 2025-02-13 02:41
Still happens in Feb 2025
https://stackoverflow.com/questions/79434892/android-keyboards-disappear-in-dropdown-editor-field-in-tabulator

**Comment by atorres16** [comment] 2025-02-19 16:30
Just to let you know that this Post has been answered in StackOverflow

https://stackoverflow.com/a/79449486/3596441
