### ISSUE TITLE
Bad rendering when coupling between Frozen & headerFilter in a column

### ISSUE THREAD

**Issue by ErgoOne** [olifolkerd/tabulator#1311] opened 2018-07-31 12:45 UTC
Hi,
When i use a simple **headerFilter** in a column that i wish to be **frozen** also, the tab header is not taking in consideration in height of the filter box.
Please refere to the Fiddle below which is the standard Tabulator example with the two options added.
https://jsfiddle.net/Ergo0ne/72Lrqa8y/
If someone could give it a shot with some css modifications that's would be great.
Thanks.

**Comment by Ulric19** [comment] 2018-08-23 19:51
How did this issue resolve? I would like to have both **headerFilter** and **frozen** enabled as well, but this functionality does not work without style changes. 
I would believe this to be a bug given that there is no clear indication in the docs that these two features are not supported together, but perhaps I'm not looking in the right place.
Any update regarding this would be greatly appreciated.

**Comment by ErgoOne** [comment] 2018-08-24 07:02
Hi @Ulric19, 
I did close it alone since i found the 'css solution'. If we can call it a solution.
I should have posted the solution. My bad.
Just add a specific height in your css for the desired tabulator div for the tabulator column.
`#tdb_table .tabulator-col{
  height: 50px;
}`
This will do the job untill a bult in solution shows up :)

**Comment by Ulric19** [comment] 2018-08-24 13:14
Hi @ErgoOne,

Thank you for the fast response - your solution works great for me. Thanks again!

**Comment by ErgoOne** [comment] 2018-08-24 15:47
Np :) 
I am re openning the issue since it's may be a bug that can be resolved in next versions :)

**Comment by olifolkerd** [comment] 2018-08-27 15:48
Hey @ErgoOne 

this is a duplicate of #1232

I will have a resolution out for this in the 4.0 release.

Cheers

Oli

**Closed** 2018-09-01 10:06 UTC
Labels: duplicate
