### ISSUE TITLE
Errors using setData

### ISSUE THREAD

**Issue by rkarlberg** [olifolkerd/tabulator#1612] opened 2018-11-29 21:49 UTC
I'm getting an error on this line of code using version 4.1:

portfolio_table.setData(url); 

In 3.5 it was working fine:

$("#portfolio").tabulator("setData", url);

The error is:

_Access to fetch at '(url)' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'._

If I try to add some ajaxConfig options, I get a different error:

 **tabulator.min.js:5 Ajax Load Error - Connection Error:  TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
    at tabulator.min.js:5
    at new Promise (<anonymous>)
    at f.defaultLoaderPromise (tabulator.min.js:5)
    at tabulator.min.js:5
    at new Promise (<anonymous>)
    at f.sendRequest (tabulator.min.js:5)
    at tabulator.min.js:5
    at new Promise (<anonymous>)
    at f._loadDataStandard (tabulator.min.js:5)
    at f.loadData (tabulator.min.js:5)** 

**Tabulator Info**
- Which version of Tabulator are you using? - 4.1
- Post a copy of your construct object if possible so we can see how your table is setup:

        **var portfolio_table = new Tabulator("#portfolio", {
            ajaxConfig: {
                mode: "no-cors", // no-cors, cors, *same-origin
                credentials: "omit", // include, *same-origin, omit
                headers: {
                    "Content-type": 'application/json; charset=utf-8'
                }
            },
            height: 500,
            layout: "fitDataFill",
            movableRows: true,
            movableColumns: true,
            initialSort: [{
                    column: "session_age",
                    dir: "asc"
                }, //sort by this first
            ],...**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version

**Comment by Rodbjartson** [comment] 2018-11-30 08:51
Inside your ajaxconfig you should make it POST perhaps?

**Comment by olifolkerd** [comment] 2018-11-30 11:02
what type of request are you making, POST GET ETC?

**Comment by rkarlberg** [comment] 2018-11-30 15:40
It's a GET - I am trying to retrieve data from the API on my other server.  Yes, I control it, these are my header settings:

router.use(function (req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    res.header('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS');
    next();
});

**Comment by olifolkerd** [comment] 2018-12-01 14:58
Hey @rkarlberg 

Sorry, i missed this in your first message, looking at the error i would say you are passing a value of *null* in your url variable

**Comment by rkarlberg** [comment] 2018-12-02 15:35
Well, I tried using a hardcoded string instead of a variable, and still get the same error.  This was working in 3.5, so something must have changed?

**Comment by olifolkerd** [comment] 2019-02-10 14:34
Hey,

This is definitely not a bug, i have managed to get requests working to the sites outlined above using the correct fetch configurations *(a bit of light googling and reading the docs is all it took)*.

The OPTIONS request is actually how CORS works, it sends an OPTIONS request first to check that it can request things from the server, then if it succeeds it then makes the GET request.

The reason that you have run into issues is that the old ajax system used the jQuery ajax functionality that did the hard work of CORS for you, where as the fetch API expects you to do it yourselfs.

That being said, it is clear that CORS configuration is not the simplest of things, so in version 4.2 which is being released on monday I have added some additional logic to the Ajax system to try and configure the CORS headers for you so that for most sites it should now work automatically.

I have also updated the documentation on the website *(released on monday also)* to give some more specific advice on resolving any CORS issues in future.

Thanks for the feedback, especially the URLs for the ajax data sources you were stuggling with that was very helpful.

Cheers

Oli :)

**Closed by olifolkerd** 2019-02-10 14:34 UTC
Labels: question

**Comment by rkarlberg** [comment] 2019-03-16 02:54
Well, thanks for trying, but it still doesn't work.  I've spent hours googling and reading docs, but still get errors such as "Access to fetch at 'https://www.mta-data.com/api/v1/fum/getview/annual/NONE' from origin 'null' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response."

I guess I'll have to find another way.

**Comment by kjgarza** [comment] 2019-03-17 08:16
My workaround this problem was to create my own ajax callback.

setup:
https://github.com/datacite/stats-portal/blob/045b4249593345d478f6faf60b3b1da2e4cd018b/source/javascripts/stats/tabulator.js.erb#L120

callback:
https://github.com/datacite/stats-portal/blob/045b4249593345d478f6faf60b3b1da2e4cd018b/source/javascripts/stats/tabulator.js.erb#L71

**Comment by rkarlberg** [comment] 2019-03-18 18:55
Thanks Kristian, I will try that!

**Comment by microbug** [comment] 2019-06-25 20:41
@olifolkerd As far as I can tell this is still a bug with 4.2. Either that or I can't figure it out. I've tried following the instructions for CORS requests on <tabulator.info> and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), the request looks alright (`Access-Control-Allow-Origin` set to `*`) in the web inspector but it's being blocked 'due to access control checks'.

A workaround is disabling CORS restrictions for development and making sure the API and app are on the same domain for production.

**Comment by answerquest** [comment] 2020-05-27 13:11
After spending time on this for a while I reverted to old-school making API call with a separate `fetch()` function and then `tabulator1.setData(data);`, and it worked fine. Will avoid using tabulator's own ajax loader when fetching from another domain from now on. 
I'm suspecting that the pre-flight request has something weird in it that's causing this issue for so many folks - would be worth digging into the source code some day.  
Wondering if we can manually trigger and end the ajaxLoader ?
