### ISSUE TITLE
How to use with VueJS 3 and Composition API

### ISSUE THREAD

**Issue by djcaesar9114** [olifolkerd/tabulator#3469] opened 2021-11-13 10:26 UTC
**Website Page**
[A link to the page with the issue](http://tabulator.info/docs/4.0/frameworks#vue)

**Describe the issue**

First of all thanks for your work, the results are impressive!

Well, the issue is that I don't know how to use Tabulator, which seems a very good tool, in my VueJS3 app.
I suppose I have to import the library in my `main.js`:

```
import Tabulator from 'tabulator';
```

Then in the same `main.js` I have to use tabulator:

```
app.use(tabulator).mount('#app');
```

And in any component (for example `MyData.vue`) I have to inject it:

```
  setup(props) {
    const tabulator = inject('$tabulator');
```

But of course What I wrote doesn't work. I haven't gone deep enough in Tabulator to understand how I could use it properly.

**Comment by LilDevil** [comment] 2021-11-13 17:14
Have you seen this? http://tabulator.info/docs/5.0/frameworks#vue

**Comment by djcaesar9114** [comment] 2021-11-14 22:06
Yes, I did :)
This is clearly not working with VueJS3 composition API, or I misinterpret how it should work.

**Comment by olifolkerd** [comment] 2021-12-19 16:51
This is a duplicate of #3194

**Closed by olifolkerd** 2021-12-19 16:51 UTC

**Comment by olifolkerd** [comment] 2021-12-30 08:23
Hey @djcaesar9114 

Can you provide a link to the console errors you are seeing?

Cheers

Oli :)

**Comment by djcaesar9114** [comment] 2022-01-11 13:08
Actually it comes from the fact that vue-tabulator doesn't support Vue3: https://github.com/angeliski/vue-tabulator/issues/109
Also, it doesn't work with Tabulator 5: https://github.com/angeliski/vue-tabulator/issues/116

It's a shame because tabulator seems great. I'll have to look for another solution :(
