### ISSUE TITLE
Can not move row to the top of group

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1635] opened 2018-12-08 09:58 UTC
**Describe the bug**
When data grouping is enabled: http://tabulator.info/examples/4.1#grouping
I try to make 'Margret Marmajuke' as first row of the group (put this row in place of 'Mary May')
But I can move that row only out of this group

**Tabulator Info**
- Which version of Tabulator are you using? latest

**To Reproduce**
see video
[Kazam_screencast_00003.mp4.zip](https://github.com/olifolkerd/tabulator/files/2659581/Kazam_screencast_00003.mp4.zip)

**Additional context**
It seems tabulator should react when we are move over 50% of row width (not the top/bottom of row)

**Comment by olifolkerd** [comment] 2018-12-12 20:08
Hey @KES777 

Thanks for the headsup, That is definitely a regression introduced in 4.0

i will get that fixed in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2018-12-16 14:31
Looking into it further, the issue is only intermittent depending on a variety of factors, and will be resolved in the next minor release when i add extra capabilities to allow dragging of rows into empty groups, so i shall schedule it for then (jan)

**Comment by olifolkerd** [comment] 2019-02-08 17:37
This has been resolved on the 4.2 branch which will be release on monday

Thanks for the info.

Cheers

Oli :)

**Closed by olifolkerd** 2019-02-08 17:37 UTC
Labels: bug

**Comment by KES777** [comment] 2019-03-02 14:13
works fine after upgrading to 4.2.1. 
Thank you.
