### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pH4Lk0n** [olifolkerd/tabulator#2978] opened 2020-09-09 15:43 UTC
**Describe the bug**
On some of our users data is not displayed in Tabulator. Main problem is that I cannot reproduce on testing machines, but after analyzing code I found a place that produces problem. So please don't close right away.

Error in console is:
`Uncaught RangeError: Maximum call stack size exceeded`

Code is looping between:
`RowManager.prototype.redraw()`
which calls on the start:
`this.adjustTableSize();`

which in the end on certain condition loops again to:
`this.redraw();`

On latest versions of Chrome on some users this loops to critical error and Tabulator is not displayed at all.
Don't know why it only affect some users but when it does it happens all the time.

**Tabulator Info**
Tested on 4.7.2 and 4.8

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 84 85.0.4183.83 85.0.4183.102

**Comment by olifolkerd** [comment] 2020-09-09 16:05
Hey @pH4Lk0n 

Please provide a link to a JS Fiddle or CodePen that replicates the issue. It is likely an unusual interaction between your table setup and the site it is embedded in.

Without a JS Fiddle that shows the issue happening and how your table is configured it is impossible for us to find out what is causing it

Cheers

Oli :)

**Comment by h-tendy** [comment] 2020-09-09 16:48
Hey @pH4Lk0n

Funnily enough, I think I reported the same issue here just a couple of days ago. Please see if your stack looks like the same as in here: 
https://github.com/olifolkerd/tabulator/issues/2974

**Comment by olifolkerd** [comment] 2020-09-09 17:03
Hey @pH4Lk0n 

That is possible, but without a JS Fiddle or Code Pen i have no where to start looking for a solution.

If someone could put togeather a Minimum test case then i can likely fix it in this weekends patch release, but without one i cant make any progress as i have no idea how your tables are configured and i don't see the issue in any of my test setups.

Cheers

Oli :)

**Comment by pH4Lk0n** [comment] 2020-09-09 18:04
Hey @h-tendy 

That's the same stack trace. I'm investing this for same quite time now.
Problem was and still is that some clients reports this and when I use same browser and OS and log into theirs account it all works fine. But on their machine it does not. So the problem is more complicated

@h-tendy did you managed to reproduce this problem on your machine?

**Comment by h-tendy** [comment] 2020-09-09 18:09
Hey @pH4Lk0n  - Yes, I reproduced and suggested a fix also as documented above. But I'm unable to get a minimal testcase for Oli to see it on jfiddle...

**Comment by olifolkerd** [comment] 2020-09-09 19:59
If you can't see it on a fiddle it is likely due to the rest of the site that Tabulator is embedded in.

Have you setup your table on a div that is either part of a grid or flex layout? That can often cause render loops.

Oli

**Comment by h-tendy** [comment] 2020-09-11 04:26
I am using `react-bootstrap` and the table is on a `<Row>` by itself. Could that cause it? (it is still a rare occurrence). Not using `react-bootstrap` or `<Row>` will be a problem...

**Comment by olifolkerd** [comment] 2020-09-12 18:37
Hey All,

As this is a duplicate im gonna close this one and focus all convo onto the original issue. #2974 

The issue will definitely be the result of no height being set, as there is a loop used in that instance but has anyone isolated any other setup that triggers this issue. Is everyone with the issue using react?

I would love to get it fixed for you, but i really need a repeatable example before i can release a patch so that i have something to test against to know that it works.

Cheers

Oli :)

**Closed by olifolkerd** 2020-09-12 18:37 UTC
Labels: Duplicate

**Comment by pmendis** [comment] 2021-06-09 05:23
Got this error when I tried to use two tables with different ids in a single page with 'bottomCalc' in both. Version 4.8. When u remove bottomCalc from one table, the error disapears. topCalc works fine.

**Comment by muhyilmaz** [comment] 2024-10-10 08:17
> Hey All,
> 
> As this is a duplicate im gonna close this one and focus all convo onto the original issue. #2974
> 
> The issue will definitely be the result of no height being set, as there is a loop used in that instance but has anyone isolated any other setup that triggers this issue. Is everyone with the issue using react?
> 
> I would love to get it fixed for you, but i really need a repeatable example before i can release a patch so that i have something to test against to know that it works.
> 
> Cheers
> 
> Oli :)

Yes it is, when I set height, it resolved. Thanks.

**Comment by sanriodev** [comment] 2025-04-24 14:31
I still have this issue on tabulator-tables `6.3.1`

**Comment by muhyilmaz** [comment] 2025-09-03 05:54
> Same problem. Vanilla JS. Opera One(versión: 120.0.5543.161) (not in Edge, Firefox nor Brave)

Did you set height?
