### ISSUE TITLE
json file to tabulator

### ISSUE THREAD

**Issue by powelldw** [olifolkerd/tabulator#1195] opened 2018-06-11 21:03 UTC
I read an earlier issue from 2 years ago where the user was trying to using a locally stored json file to populate the data for their page.  I used exactly the same syntax and was unable to get the table filled in with the data-note the table shows up, but empty.  I know the json file is correctly formatted, since the same file is used for other applications.  I am using a Mac and the file is in the top level of the project folder for the page.  I also put a copy at the top level for me as a user.
Ideas?
$("#dataset").tabulator("setData", "/PAR.json");

**Comment by olifolkerd** [comment] 2018-06-11 21:51
Hey @powelldw 

Are you serving the page from a webserver or just loading the file from a directory on your computer. if you are just opening the file on your computer it will need to be a path relative to the file your loading, if they are in the same directory it would be "./PAR.json"

I hope that helps.

Cheers

Oli :)

**Comment by powelldw** [comment] 2018-06-12 00:32
Hey Oli,
Thanks for the feedback.  I am running the web server directly from my Mac.  The file is local to my Mac.  I tried your path suggestion and it had no desired affect.  
Here is the script I have set up.  As I noted before, the table shows up, it is just blank except for the titles.
$("#dataset").tabulator({
  height:"300px",
  fitColumns:true,
  columns:[
    {title:"Marked", field:"Marked",  sortable:true, width:50},
    {title:"Bio ID", field:"Bio ID", sortable:true, width:100,sorter:"number"},
    {title:"Test ID", field:"Test ID", sortable:true, width:100},
    {title:"Test Name", field:"Test Name", sortable:false, width:200},
    {title:"Result Type", field:"Result Type"},
    {title:"Result Value", field:"Result Value"},
    {title:"Cond Names", field:"Cond Names"},
    {title:"Cond Values", field:"Cond Values"},
  ],
});

$("#dataset").tabulator("setData", "./PAR.json");

**Comment by powelldw** [comment] 2018-06-12 00:49
Seems like the debugger is seeing a data loading error:

Data Loading Error - Unable to process data due to invalid data type Expecting: array Received: object Data: Object

**Comment by olifolkerd** [comment] 2018-06-12 20:57
Hey @powelldw 

That error message is because you are trying to pass an object in, rather than an array of objects. it is likely that the JSON file is not formatted as Tabulator expects.

Tabulator can accept, an array of objects, a JSON string representing an array of objects or an HTML table. full details can be found in the [Set Table Data Documentation](http://tabulator.info/docs/3.5#set-data)

I hope that helps.

Cheers

Oli :)

**Comment by powelldw** [comment] 2018-06-13 00:09
Hey Oli,
Thanks again for your feedback.  The file I have is a valid JSON (string) file, easily interpreted by multiple applications.  Funny enough, you can't attach a JSON file to the message...  Could it be a problem with Tabulator reading a file in as opposed to getting from a server via Ajax?

Here is the text of the JSON:
{"dataset":{"title":"no title"},"columns":[{"column_id":1, "name":"Marked"},{"column_id":2, "name":"Bio Id"},{"column_id":3, "name":"Test ID"},{"column_id":4, "name":"Test Name"},{"column_id":5, "name":"Result Type"},{"column_id":6, "name":"Result Value"},{"column_id":7, "name":"Cond Names"},{"column_id":8, "name":"Cond Values"}],"rows":[{"row_id":1, "data":["UNMARKED",2710153,"T0123","X205485514","Activity Flag","\u0000Y","",""]}]}

**Comment by powelldw** [comment] 2018-06-13 01:38
Fixed all the field names, works if the data is put in the js via a var.  Still fails if you point to an external file with a JSON string because tabulator is expecting an array and not a JSON string.

**Comment by Rodbjartson** [comment] 2018-06-13 08:49
Add this in your table object:

` ajaxResponse: function (url, params, response) {
                        
                        
                        //url - the URL of the request
                        //params - the parameters passed with the request
                        //response - the JSON object returned in the body of the response.

                        return response.d; //Return the d Property Of a response json Object
                    },`

**Comment by olifolkerd** [comment] 2018-06-13 21:49
Hey @powelldw 

Thanks for posting the contents of your JSON file, that shows exactly what the issue is.

It isnt that your JSON is invalid, it is perfectly valid JSON, it is just that your data not in the format that Tabulator requires. Tabulator is expecting an array of row data objects and you are passing in a whole lot of additional information that it isnt expecting and it doesnt know how to interpret.

As explained in the [Set Table Data Documnetation](http://tabulator.info/docs/3.5#set-data), tabulator expects the following as the input to the ***setData*** function:

```js
[
    {id:1, name:"Billy Bob", age:"12", gender:"male", height:1, col:"red", dob:"", cheese:1},  //one row
    {id:2, name:"Mary May", age:"1", gender:"female", height:2, col:"blue", dob:"14/05/1982", cheese:true}, //another row
]
```

@Rodbjartson is correct in saying you should use the ***ajaxResponse*** callback to fix you issue. you can use this function to take the object your are parsing in, which will be in the ***response*** argument passed into the callback, and transform it into the format that Tabulator is expecting, and then return that from the function.

I hope that makes sense.

Cheers

Oli

**Closed** 2018-06-24 09:03 UTC
Labels: question

**Comment by powelldw** [comment] 2018-07-03 00:35
Oli,
I have worked very hard to try and get the JSON string I mentioned in the now closed issue into a form that tabulator can use, since I really like the tabulator presentation of data.  However even if I parse the data (JSON.parse (or the query equivalent) I can’t get tabulator to ready it.  I tried to insert the ajaxResponse function also to no avail, though perhaps I am not using the function appropriately.
Thoughts?
Dennis

**Comment by olifolkerd** [comment] 2018-07-03 22:06
Hey @powelldw 

Sorry to hear you are still having trouble,

here is a rough idea of what you should be putting in the ***ajaxResponse*** callback, i havnt tested it so i cant guarantee it will work, but it should put you on the right track:

```js
ajaxResponse: function (url, params, response) {

	var tableData = []; //hold array of table data

	//itterate over the rows
	response.rows.forEach(function(row){

		var rowData = {}; //create row data object

		//assign value to columns
		row.data.forEach(function(value, index){

			//assign value to column
			rowData[response.columns[index].name] = value;
		});

		//add row to table
		tableData.push(rowData);

	});
	
	//return correctly formatted table data to tTbulator
	return tableData;
},
```

I hope that helps,

Cheers

Oli :)

**Comment by powelldw** [comment] 2018-07-06 15:05
Oli,
I got it all to work via some hand holding with a JS mentor and some code from a developer in house (which looks in general form like what you show-THANKS!).  In essence I did end up using JSON.parse an iterated through the string to produce the array.  Tabulator then accepted the input and I got the web page output as desired.  I am now playing around with all the tabulator options [say, not sure how to get the column header to be 2 sub rows deep in order to handle long column names].  The real challenge will be in insert my REST calls into my page along with authorization, etc, but that will be fun.

Just a minor note about your web pages, there are a couple of typos here and there throughout the pages.  Would it be of any value to send you feedback about those?

Cheers,
Dennis

**Comment by pbothra** [comment] 2020-03-17 10:26
Hi Oli,

I am getting following error response always , when I am creating table with pagination using ajax call .

Please review my code and let me know if I made mistake .

Error :
--------

Ajax Load Error:  TypeError: Cannot read property 'call' of undefined
    at tabulator.js:11227
    at new ZoneAwarePromise (zone.js:910)
    at Ajax.defaultLoaderPromise (tabulator.js:11207)
    at tabulator.js:11105
    at new ZoneAwarePromise (zone.js:910)
    at Ajax.sendRequest (tabulator.js:11096)
    at tabulator.js:21287
    at new ZoneAwarePromise (zone.js:910)
    at Page._getRemotePage (tabulator.js:21250)
    at tabulator.js:21229

event-view-item-details.component.ts:73 error = TypeError: Cannot read property 'call' of undefined

Note :
-------

API called and returns data successfully but I am unable to get API response in ajaxResponse function , getting the above error . Plesae help me


this.itemTableinEventDetails = new Tabulator("#event-item-tabulator", {
      layout: "fitColumns",
      columns: this.itemDetailscolumnsinEvent,
      placeholder: "No Record Available",
      virtualDomBuffer: 400,
      dataTree: true,
      dataTreeStartExpanded: false,
      pagination:"remote", //enable remote pagination     
      ajaxURL:"/rts/rest/event/getEventItemDetails", 
      ajaxParams:{'eventId':'14545454545',limit:25}, 
      ajaxConfig:{
          method:"POST",      
      },
      ajaxContentType:{
          'Content-type': 'application/json; charset=utf-8', 
      },

      ajaxResponse:function(url, params, response) {
        console.log('reponse = ' + response);
        return response;  
      },
      ajaxError:function(error){
        console.log('error = ' + error);
      },       
      paginationDataSent:{
        "page":"offset", //change page request parameter to "pageNo"
     },
    });

**Comment by pbothra** [comment] 2020-03-17 10:27
Hi Oli,

I am getting following error response always , when I am creating table with pagination using ajax call .

Please review my code and let me know if I made mistake .

Error :
--------

Ajax Load Error:  TypeError: Cannot read property 'call' of undefined
    at tabulator.js:11227
    at new ZoneAwarePromise (zone.js:910)
    at Ajax.defaultLoaderPromise (tabulator.js:11207)
    at tabulator.js:11105
    at new ZoneAwarePromise (zone.js:910)
    at Ajax.sendRequest (tabulator.js:11096)
    at tabulator.js:21287
    at new ZoneAwarePromise (zone.js:910)
    at Page._getRemotePage (tabulator.js:21250)
    at tabulator.js:21229

event-view-item-details.component.ts:73 error = TypeError: Cannot read property 'call' of undefined

Note :
-------

API called and returns data successfully but I am unable to get API response in ajaxResponse function , getting the above error . Plesae help me


this.itemTableinEventDetails = new Tabulator("#event-item-tabulator", {
      layout: "fitColumns",
      columns: this.itemDetailscolumnsinEvent,
      placeholder: "No Record Available",
      virtualDomBuffer: 400,
      dataTree: true,
      dataTreeStartExpanded: false,
      pagination:"remote", //enable remote pagination     
      ajaxURL:"/rts/rest/event/getEventItemDetails", //set url for ajax request
      ajaxParams:{'eventId':'14545454545',limit:25}, //set any standard parameters to pass with the request
      ajaxConfig:{
          method:"POST",
      
      },
      ajaxContentType:{
          'Content-type': 'application/json; charset=utf-8', //set the character encoding of the request
      },

      ajaxResponse:function(url, params, response) {
        console.log('reponse = ' + response);
        return response;  
      },
      ajaxError:function(error){
        console.log('error = ' + error);
      },       
      paginationDataSent:{
        "page":"offset", //change page request parameter to "pageNo"
     },
    });
