### ISSUE TITLE
Horizontal header scrolling broken

### ISSUE THREAD

**Issue by mike-lischke** [olifolkerd/tabulator#3979] opened 2022-10-10 08:56 UTC
Hi Oli,

I know I'm supposed to provide a link to a reproducible test case, but even though I tried hard, I cannot. All the simple tables in JSFiddle and Codepen work as intended. 

But before you close this issue, please read on and you will see that this is an edge case which is not well covered by your strict Github issue policies.

**Summary**: upgrading tabulator-tables from 5.3.4 to 5.4 broke horizontal scrolling of the table header in my application. I have not changed a single character in my code base. Just upgrading breaks this functionality.

This is a video when using 5.3.4:

https://user-images.githubusercontent.com/2398704/194852170-37bde205-3cb7-4498-a8c3-1fa1181f52f4.mov

and here 5.4.0:

https://user-images.githubusercontent.com/2398704/194852217-13707f9c-eca6-4ef0-b9cc-1e230443328a.mov

Because simple tables work as expected, I assume there's a clash of CSS styles. I see patches of you were you rename CSS names (which is btw. also a problem on its own if applications rely on those names), so this is entirely possible.

I tried to figure out what's going on but the inner structure of the code makes this very difficult. Keep in mind I have to debug using my application and stepping into the release code of tabulator-tables.

So, I'm not even sure this is a bug or just a bad coincidence, but I would need your help to figure this out. Hence I would have to ask for example how (and where) the horizontal scrolling of the header is implemented, but questions are auto-closed here and asking tabulator internals on Stackoverflow is very likely not getting any attention, let alone an answer.

I'm willing to dig into the tabulator code to figure out what changed, but without some guidance this is impossible for me. Can you please provide some?

Thanks, Mike

**Comment by olifolkerd** [comment] 2022-10-10 09:40
Hey @mike-lischke 

The structure of the table header was changed in 5.4 so it is possible that if you have some custom CSS on your site that this has resulted in things being broken.

The reason that I ask people to create a JS Fiddle is that is easily demonstrates where the issue is, and shows that most of the time it is due to an interaction with some customisation on their site and not the Tabulator code itself.

While I am open to helping you, I hope you can see that a description of "broken header scrolling", without any code, demo, detailed description or video of the issue doesn't really give me much to go on, especially when everything is working in the examples on the Tabulator site and the JS Fiddle. Have you made sure you aren't running on old cached CSS?

There was an issue raised on 5.4.0 about the tab focus on header filters causing horizontal scroll issues, which was resolved in yesterdays 5.4.1 release, which may be related.

I am happy to keep this open for a few days while you investigate further, maybe post a video of what you are experiencing. But without more details I couldn't even begin to point you at the right place to look, there were a large number of updates to the system across a number of modules that this might be related to.

Cheers

Oli :)

**Comment by mike-lischke** [comment] 2022-10-10 11:11
> The structure of the table header was changed in 5.4 so it is possible that if you have some custom CSS on your site that this has resulted in things being broken.

Aha, that's what I thought. Is this work done in a single patch or multiple patches? Can you point me to them, so I can scan the code to see any smoking gun there?

> The reason that I ask people to create a JS Fiddle is that is easily demonstrates where the issue is, and helps isolate when the issue due to an interaction with some customisation on their site and not the Tabulator code itself.

Absolutely understandable! I was often confronted with misbehaviour, but could not reproduce it, and hence not fix it. However, it's a fact that things often not so simple to reproduce, especially when such bad things happen only in complex applications.

> While I am open to helping you, I hope you can see that a description of "broken header scrolling", without any code, demo, detailed description or video of the issue doesn't really give me much to go on, especially when everything is working in the examples on the Tabulator site and the JS Fiddle. Have you made sure you aren't running on old cached CSS?

Glad you still consider finding the problem, even though I failed the Github issue criteria :-)

I updated my posting with two videos, one showing good behaviour, the other the wrong one. All I did was to change tabulator-tables in my package.json to 5.4 (from 5.3) and ran `npm i`. Then rebuilt my app and there you go.

> There was an issue raised on 5.4.0 about the tab focus on header filters causing horizontal scroll issues, which was resolved in yesterdays 5.4.1 release, which may be related.

Of course, before I posted my issue I searched the issue list here to see if someone else brought up a similar problem. I also tested 5.4.1, but it didn't change things. 

> I am happy to keep this open for a few days while you investigate further, maybe post a video of what you are experiencing. But without more details I couldn't even begin to point you at the right place to look, there were a large number of updates to the system across a number of modules that this might be related to.

Thanks, much appreciated!

**Comment by jgwconsulting** [comment] 2022-10-12 15:20
Hey :) We're seeing the same issue here and we've eliminated any potential issues with our own CSS.

To demonstrate, this is a fork of an existing demo sandbox I found, using v5.3.4, and the scrolling works fine: 
[v5.3.4 - heading scrolling works](https://codesandbox.io/s/test-tabulator-heading-scrolling-v5-3-4-working-g030rd)

Forking again and switching to v5.4.1 (or 5.4.0) demonstrates the issue - the table data scrolls but the headings above don't move accordingly:
[v5.4.1 - heading scrolling broken](https://codesandbox.io/s/test-tabulator-heading-scrolling-v5-4-1-broken-3ip3wx)

**Comment by olifolkerd** [comment] 2022-10-13 05:28
Hey @jgwconsulting 

if you have a look at your CSS import at the bottom of your `App.vue`  you will see you are importing the CSS for an old version of tabulator.

If you update that to import the correct version then everything works as expected.

Cheers

Oli :)

**Closed by olifolkerd** 2022-10-13 05:28 UTC
Labels: Possible Bug

**Comment by mike-lischke** [comment] 2022-10-13 07:02
@olifolkerd Does this mean importing one of the tabulator CSS files is mandatory? I wasn't aware of that and created my own CSS.

But thanks, importing `tabulator_simple.min.css` solved my problem too.

**Comment by olifolkerd** [comment] 2022-10-13 07:07
Yes, you have to use a Tabulator CSS file otherwise the table has no instructions for how to be laid out. That is standard practice for a front end library 

If you need to customize it then you should include an override file after the import to add any tweaks you want.

You are of course welcome to build out your own file instead but then you will have issues when there are changes to the table layout and your code doesn't update with the JS.

Cheers

Oli

**Comment by jgwconsulting** [comment] 2022-10-13 08:59
@olifolkerd Duh! Sorry, schoolboy error 😳  Thanks for all your hard work :)
