### ISSUE TITLE
ScrollToRow does not work for the last few rows

### ISSUE THREAD

**Issue by alainfrisch** [olifolkerd/tabulator#1864] opened 2019-03-05 17:27 UTC
**Describe the bug**

If passed one of the last rows, ScrollToRow fails to make it visible, be it with "center" or "bottom" position.

**Tabulator Info**
- Which version of Tabulator are you using: 4.2.2

**Working Example**
````html
<html>
  <head>
    <link href="https://unpkg.com/tabulator-tables@4.2.2/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.2.2/dist/js/tabulator.min.js"></script>
  </head>
  <body>
    <div id="example-table"></div>
    <input id="row-id"/>
    <button onclick="scroll_to_row('bottom')">Scroll to row (bottom)</button>
    <button onclick="scroll_to_row('center')">Scroll to row (center)</button>
    <button onclick="scroll_to_row('top')">Scroll to row (top)</button>
    <script type="text/javascript" src="test.js"></script>
  </body>
</html>
````

````js
var tabledata = [];
for (i = 1; i < 100; i++) {
  tabledata.push({id:i, name:i});
}
var table = new Tabulator("#example-table", {
  height:205,
  data:tabledata,
  layout:"fitColumns",
  columns:[
    {title:"Name", field:"name", width:150},
  ],
});
function scroll_to_row(kind) {
  table.scrollToRow(document.getElementById("row-id").value, kind, true);
}
````

**Expected behavior**

When typing "98" in the field and click on "Scroll to row (bottom/center)", I would expect row 98 to become visible, but Tabulator does not scroll enough.

**Screenshots**

The movie below illustrates to scrolling to row 50 works fine with any of the three modes; but 98 works only with top, not bottom nor center.

![tabulator_bug](https://user-images.githubusercontent.com/3305274/53824401-26ba2380-3f74-11e9-88ee-b3cfb5001bd6.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 72.0.3626.119

**Comment by olifolkerd** [comment] 2019-03-05 21:59
Hey @alainfrisch 

At the moment the way the virtual DOM is constructed dosnt permit scrolling beyond the last row in the table.

there is a note in the documentation specifically about this:

> In order to scroll to the top or center a row must have enough rows underneath it in the table to allow it to reach that position. Tabulator does not allow for empty space beneath rows, so if a row does not have enough rows underneath it to reach the desired position it will scroll as high as it can without leaving empty space at the bottom of the table.

In time this may change, but it isnt on the roadmap for active development yet.

Thanks for your feedback

Cheers

Oli :)

**Comment by alainfrisch** [comment] 2019-03-05 23:20
> At the moment the way the virtual DOM is constructed dosnt permit scrolling beyond the last row in the table.

I know, but this is not what this report is about.  When typing "98" and clicking "Scroll to row (bottom)" (or "center"), I would expect row 98 to become visible (it's not even the last row of the table).

>  it will scroll as high as it can without leaving empty space at the bottom of the table.

This is exactly what I'd expect, but this is not what I observe.

I really believe this is a bug, and that this ticket should be reopened.

**Comment by olifolkerd** [comment] 2019-03-06 09:04
Hey @alainfrisch 

Could you create a JS Fiddle or Code Pen that demonstrates the issue?

Cheers

Oli :)

**Comment by gillez** [comment] 2019-03-06 09:14
I have also seen this bug.  I fixed it in my local Tabulator fork and submitted a pull request.
https://github.com/olifolkerd/tabulator/pull/1697

Oli, you asked me for more details on this bug in that pull request, which I didn't get a chance to provide.  The problem is caused by not having enough rows left in the table *including the offscreen-rows at the bottom* to set the scrollTop position.  In particular, it happens when the "if (position < 0) " condition is true in this code in the function RowManager.prototype._virtualRenderFill

```
if(heightOccupied < self.height){
  position -= Math.ceil((self.height - heightOccupied) / self.vDomRowHeight);
  if(position < 0){
    position = 0;
  }
}
```

To account for this I return a "scrollOffset" and add this to scrollTop position.

Oli, Please could you have another look at my pull request?

Thanks,
Giles

**Comment by alainfrisch** [comment] 2019-03-06 09:59
Here you go:  https://codepen.io/anon/pen/aMpzXw

I've traced a bit, and my interpretation is the following:

  1. scrollToRow first calls _virtualRenderFill, which attempts to put the row at the top.
  2. But _virtualRenderFill will cap the scroll offset, because of the actual height of the holder element (not blank can be displayed at the bottom).
  3. Then scrollToRow adjusts the scrollTop to account for "center"/"bottom", but when scrollTop has been capped, the calculated adjustment is wrong.

**Comment by alainfrisch** [comment] 2019-03-06 10:09
I can confirm  #1697 fixes my issue.

**Comment by olifolkerd** [comment] 2019-03-08 07:10
Hey All,

Thanks for the additional info, i will investigate this further on the weekend.

Cheers

Oli :)

**Comment by answerquest** [comment] 2019-05-14 06:41
just FYI for others also facing this issue and looking for a quick workaround : When I use "top" instead of "center" or "bottom", I don't get this problem. At my end it's ok so no-probs.

 `table.scrollToRow(nextID, "top", true);`

**Comment by mstlaurent-paradigm** [comment] 2019-08-12 12:41
Greetings!

I've encountered the same issue, and was wondering if there was anything I could do to help! I've tried the workaround mentioned above, and I still had the same behaviour.

Thanks!

**Comment by mstlaurent-paradigm** [comment] 2019-08-19 18:32
Hi again!

I've recently upgraded to Tabulator 4.4.1, and this issues seems to be fixed in that version. I didn't investigate what exactly fixed it, but all my use cases now work.

Thanks!

**Comment by alainfrisch** [comment] 2019-08-26 11:55
On my side, I couldn't observe an improvement with 4.4.1, neither in my real use case, nor the reduced case in the codepen above.

**Comment by olifolkerd** [comment] 2019-09-29 13:55
Hey All,

I have pushed a fix for this to the master branch and will include it in a patch release this evening.

There was a glitch in the maths when the row was less than a table height from the bottom of the table,

Cheers

Oli :)

**Closed by olifolkerd** 2019-09-29 13:55 UTC
Labels: bug

**Comment by gillez** [comment] 2019-10-04 09:44
Thanks Oli.  Only just noticed this update.  I'll remove my fix/hack (in the pul request) and try the new version.
l
