### ISSUE TITLE
Placeholder still rendering even after data is loaded. When using ajax.

### ISSUE THREAD

**Issue by proautodinc** [olifolkerd/tabulator#3607] opened 2022-02-19 20:12 UTC
Describe the bug
The placeholder is still showing below the table even when there is data loaded using ajax.
Changing the tabulator version to 5.0.1  it works

Tabulator Info

version 5.1.1
Working Example
https://jsfiddle.net/bxjg7oz6/

To Reproduce

Open fiddle above
Click on Run
Observe that the placeholder "No Data Set" is still visible
Expected behavior
placeholder should not be visible.

Desktop (please complete the following information):

OS: Windows
Browser: reproduced in Chrome, Opera and Brave
Versions 98,  83 and 1.35

**Comment by olifolkerd** [comment] 2022-02-20 07:53
Hey @proautodinc

It all seems to be working fine in your example. the data is loaded correctly.

Can you be mores specific about the issue?

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2022-02-20 08:29
Hey @proautodinc 

Thanks for the hedsup, looks like a regression in the last release. i have pushed a fix to the master branch and will get a patch release out for that today.

Cheers

Oli :)

**Closed by olifolkerd** 2022-02-20 08:29 UTC
Labels: Possible Bug

**Comment by vrecan** [comment] 2022-09-15 00:07
This is still happening for me on 5.3.4
