### ISSUE TITLE
How to support RTL

### ISSUE THREAD

**Issue by technoplusplus** [olifolkerd/tabulator#729] opened 2017-11-21 19:38 UTC
Is there any way to support RTL languages?

**Comment by olifolkerd** [comment] 2017-11-21 21:06
Hey @technoplusplus ,

as long as you have set the ***direction*** to ***rtl*** in your CSS tabulator should be fine. are you having any particular issues with it?

Cheers

Oli

**Comment by technoplusplus** [comment] 2017-11-23 11:13
I tried setting the direction to RTL but we found some many issues :

 

One of the major issues was the scroll width and the alignment of header with the body because as I found 

 

1-You set margin_left to adjust the header with body while scrolling (to avoid scrollbar width) but since we are in RTL mode we found that the header is not well-adjusted with the body and there is a little shift between the headers and body

2-using groups, in RTL when we close all groups (collapse) the group headers stay in LTR mode which is not correct

3-The text doesn’t start from right to left in RTL Mode

4-the horizontal scroll doesn’t work properly when table is empty and you have a lot of columns such as (50 column) in RTL Mode

5-resizing columns is not working properly in RTL Mode

 

Once you set the direction to RTL you will find all of the above problems without any configuration

You just need to have like 40 or 50 columns

Group by columns (say 2 groups)

500 records

**Comment by olifolkerd** [comment] 2017-12-04 18:33
Hey @technoplusplus 

I have added it to the roadmap to improve RTL language support in an upcoming release.

Cheers

Oli

**Comment by B-Esmaili** [comment] 2019-02-11 13:01
any update on this?

**Comment by olifolkerd** [comment] 2019-02-11 13:04
Hey @B-Esmaili 

It is in the roadmap for this to be included in the next release. which should be in a month or two. it will likely be a gradual introduction with an initial offering in 4.3 and refinement over subsequent versions.

Cheers

Oli :)

**Comment by B-Esmaili** [comment] 2019-02-11 13:07
Isn't there any temporary workaround for this issue? i am really stock with it.

**Comment by olifolkerd** [comment] 2019-02-11 14:11
Aside from the suggestions above i dont have any further suggestions at this moment.

Sorry

**Comment by olifolkerd** [comment] 2019-02-13 07:58
@B-Esmaili 

Can i ask what are the key features you are looking for in RTL support? i don't use an RTL language myself so it would really be useful to get a list of things that you consider nessisary.

Cheers

Oli :)

**Comment by B-Esmaili** [comment] 2019-02-14 08:38
1 - Aligning columns from right (which should be done just by setting direction:rtl). but once doing that only text direction changes to rtl still columns align from left and this in turn causes column resizing to not function properly and column headers do not align with the column body.
2 - Branch element should be flipped horizontally to point right to left.

**Comment by coda-apps** [comment] 2020-06-14 07:43
Did this happen in the end? I don't seem to be able to find in to the documentation.
Thanks

**Comment by olifolkerd** [comment] 2020-07-26 13:16
Hey @coda-apps 

The issue is still open, which means it is still on the roadmap.

Im going to have a look at adding this functionality in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-08-02 10:57
Hey All,

You will be happy to hear that i have just pushed the functionality for RTL support onto the 4.8 branch which will be released at the end of the month,

Cheers

Oli :)

**Closed** 2020-08-02 10:57 UTC
Labels: Enhancement

**Comment by coda-apps** [comment] 2020-08-02 13:45
Amazing thanks!

**Comment by olifolkerd** [comment] 2020-09-04 15:03
@mostafaf two days time, this sunday

**Comment by mansourelbash** [comment] 2024-06-12 08:31
tabulatorTable.scrollToColumn not wokring on RTL Pages ,?
