### ISSUE TITLE
getHTML() doesnt bring up columncalc values when no grouping is applied

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#2264] opened 2019-08-02 08:28 UTC
**Describe the bug**
getHTML doesnt bring up columncalc(bottom) values when no grouping is applied. but, When row grouping is applied, it works fine

**Tabulator Info**
version 4.3

**Comment by aklaver** [comment] 2019-08-03 22:06
This is going to need more information:
1) Your table constructor.
2) Your configuration for htmlOutputConfig.
3) Your getHtml() call
4) What state your table is in on screen with regard to grouping.

**Comment by ryhill** [comment] 2019-08-05 18:22
Its very simple table, I took it from the example

I can't seem to get the column caluculations in getHtml
```
	var tabledata = [
	{id:1, name:"Oli Bob", progress:12, location:"United Kingdom", gender:"male", rating:1, col:"red", dob:"14/04/1984", car:1, lucky_no:5, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:2, name:"Mary May", progress:1, location:"Germany", gender:"female", rating:2, col:"blue", dob:"14/05/1982", car:true, lucky_no:10, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:3, name:"Christine Lobowski", progress:42, location:"France", gender:"female", rating:0, col:"green", dob:"22/05/1982", car:"true", lucky_no:12, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:4, name:"Brendon Philips", progress:100, location:"USA", gender:"male", rating:1, col:"orange", dob:"01/08/1980", lucky_no:18, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:5, name:"Margret Marmajuke", progress:16, location:"Canada", gender:"female", rating:5, col:"yellow", dob:"31/01/1999", lucky_no:33, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:6, name:"Frank Harbours", progress:38, location:"Russia", gender:"male", rating:4, col:"red", dob:"12/05/1966", car:1, lucky_no:2, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:7, name:"Jamie Newhart", progress:23, location:"India", gender:"male", rating:3, col:"green", dob:"14/05/1985", car:true, lucky_no:63, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:8, name:"Gemma Jane", progress:60, location:"China", gender:"female", rating:0, col:"red", dob:"22/05/1982", car:"true", lucky_no:72, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:9, name:"Emily Sykes", progress:42, location:"South Korea", gender:"female", rating:1, col:"maroon", dob:"11/11/1970", lucky_no:44, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	{id:10, name:"James Newman", progress:73, location:"Japan", gender:"male", rating:5, col:"red", dob:"22/03/1998", lucky_no:9, lorem:"Lorem ipsum dolor sit amet, elit consectetur adipisicing "},
	];

var table = new Tabulator("#example-table", {
    height:"311px",
    data:tabledata,
     htmlOutputConfig:{
        columnGroups:false, 
        rowGroups:true, 
        columnCalcs:true, 
    },
    columns:[
        {title:"Name", field:"name", width:200},
        {title:"Progress", field:"progress", width:100, sorter:"number", bottomCalc:'sum'},
        {title:"Gender", field:"gender"},
        {title:"Rating", field:"rating", width:80,bottomCalc:'sum'},
        {title:"Favourite Color", field:"col"},
        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date"},
        {title:"Driver", field:"car", align:"center", formatter:"tickCross"},
    ],
});


console.log(table.getHtml(true,true))

```

**Comment by ctlkkc** [comment] 2019-08-05 22:33
This seem the same issue #2246

**Comment by aklaver** [comment] 2019-08-06 18:45
Alright I see where the issue is. From html_table_export.js/generateBodyElements:
```
var rows = visible ? this.table.rowManager.getVisibleRows(true) : this.table.rowManager.getDisplayRows();
...
styleRow = row.type == "calc" ? calcRow : (((i % 2) && evenRow) ? evenRow : oddRow);
```

Except rowManager.getVisibleRows() only gets rows of type 'row' from what I can see. This means the previously fetched calcRow is never used/displayed. Not sure yet how to fix.

**Comment by aklaver** [comment] 2019-08-07 16:38
I did some digging and from what I can tell the problem is merging the data rows with the calc(and/or group) rows. This gets into areas of the code that are still a mystery to me. I will do some more exploring, but I am guessing it is going to take input from @olifolkerd to get things moving.

**Comment by olifolkerd** [comment] 2019-08-11 15:37
Hey @ryhill 

This has been resolved on the 4,4 branch which will be released later today

Cheers

Oli :)

**Closed by olifolkerd** 2019-08-11 15:37 UTC

**Comment by pkirankmr** [comment] 2019-08-12 10:29
Awesome...Thanks for addressing
