### ISSUE TITLE
setData strange behavior on V5

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3448] opened 2021-11-03 14:14 UTC
I have at least two strange behaviors using the "setData" method:
1. Some rows hide after using the "setData" method in grouped tables.
2. Got this error "Uncaught (in promise) TypeError: can't assign to property "innerHTML" on false: not an object" which I cannot replicate in the sample bellow

**Tabulator Info**
- V5.0.7

**Working Example**
[codepen example](https://codepen.io/jaguarito/pen/oNezjoZ?editors=1011)

**To Reproduce the first issue**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. click on the "Set Data" button
2. Rows disappear from the current groups, yet the group header still shows the correct counter
3. if you toggle the group (collapse, expand) the hidden rows appear again

**Expected behavior**
the "setData" method should replace the current data of the table applying the active column definitions to the new data.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Waterfox (latest), Chrome (latest)

**Comment by justin-sleep** [comment] 2021-11-15 19:35
Both issues only seem to appear on tables where groups are enabled.

The `innerHTML` error is thrown by this line: https://github.com/olifolkerd/tabulator/blob/ff43d99f7e0d9b99513d85e7803dc69b8493967f/src/js/modules/GroupRows/Group.js#L550
Something is causing the element to get set to false during a data update. The element is a standard row when the table is initialized:

```html
<div class="tabulator-row tabulator-group tabulator-group-level-0 tabulator-group-visible tabulator-row-odd" role="rowgroup"><div class="tabulator-group-toggle" style="margin-left: 0px;"><div class="tabulator-arrow"></div></div>Foo</div>
```
In the process of running `setData()`, however, the element simply becomes `false`.

It appears that when the data is updated, the first row is hidden. Collapsing the group and expanding it causes the missing row to be displayed again.

[I wrote a minimal example](https://codepen.io/justin-sleep/pen/vYJQZVr) to try to to reproduce both problems, but like @jaguarxii, I couldn't reproduce the false `element` property throwing that error.

That said, I *think* both issues are related, and that fixing the disappearing row might fix the false element problem.

**Comment by olifolkerd** [comment] 2021-12-19 12:24
Hey @jaguarxii 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2021-12-19 12:24 UTC
Labels: Possible Bug
