### ISSUE TITLE
Frozen columns for bootstrap 4 

### ISSUE THREAD

**Issue by prateeks39** [olifolkerd/tabulator#2011] opened 2019-04-24 18:43 UTC
Frozen columns is working but others column overlapping on frozen column only for bootstrap 4.

**Comment by aklaver** [comment] 2019-04-24 20:47
I created a simple jsFiddle:

https://jsfiddle.net/aklaver/tmgh63de/13/

and I cannot replicate using FF 60.6.1esr

You will need to elaborate on what your setup is.

**Comment by prateeks39** [comment] 2019-04-25 01:50
I'm using tabulator-tables in react application. In this for styling I'm using tabulator  saas bootstrap4 (tabulator_bootstrap4.scss ) in node mudules.

**Comment by Rodbjartson** [comment] 2019-04-25 09:27
Version???

**Comment by prateeks39** [comment] 2019-04-25 09:56
i'm using tabulator 4.2.5 and react 16.8.6

**Comment by aklaver** [comment] 2019-04-25 14:05
@prateeks39 Can you create an example on jsFiddle/CodePen to demonstrate?

**Comment by prateeks39** [comment] 2019-04-25 18:30
In you given jsFiddle pls remove refrence(https://unpkg.com/tabulator-tables@4.2.5/dist/css/tabulator.min.css)  and add new refrence (https://unpkg.com/tabulator-tables@4.2.5/dist/css/bootstrap/tabulator_bootstrap4.min.css) and then scroll table horizontally and you will find issue that colums is overlapping on frozen columns.

**Comment by aklaver** [comment] 2019-04-27 15:44
Alright I can confirm this. Also that the behavior changed from  tabulator_bootstrap.css  to tabulator_bootstrap4.css. Some tweaking found that if you go line 675 in tabulator_bootstrap4.css and change background-color to #fff from transparent it will 'work'. The issue being that the columns where frozen but the the unfrozen column data was visible as you slid it 'under' the frozen column.

**Comment by olifolkerd** [comment] 2019-04-27 21:54
Hey Everyone,

Thanks for all the investigation there, i will put a fix in this weekends patch release.

Cheers

Oli :)

**Comment by prateeks39** [comment] 2019-04-28 02:58
Hi oli/aklaver, 
Thanks for your support, it will be helpful for me if you will fix this issue with striped background color with hover effect. So row's looks consistent in color.
Thanks.

**Comment by olifolkerd** [comment] 2019-04-28 10:57
Hey Everyone,

The issue was because the default bootstrap 4 variables use transparency to create different shades of colours on the table, resulting in issues when overlapping cells happen when using frozen columns.

I have tweaked the variables to remove this transparency and pushed a fix to the master branch.

I will include it in this weekends patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2019-04-28 10:57 UTC
Labels: bug
