### ISSUE TITLE
Update Row not working for me.

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#171] opened 2017-02-03 20:32 UTC
Hi again, thanks in advance.

This is my code

![image](https://cloud.githubusercontent.com/assets/5125512/22607502/8e518c6a-ea2e-11e6-912e-a76a49ce3e66.png)

It doesn't update the row, i don't know why :( Any help?

**Comment by olifolkerd** [comment] 2017-02-03 22:51
Hi cemmons.

the issue is your are passing in your updated data as a string not an object. you should be doing the following.

```js
var updRow={};
updRow[field]=oldValue;

$("#producSortingGrid").tabulator("updateRow", id, updRow);

```

**Comment by olifolkerd** [comment] 2017-02-03 22:53
as a general note if you ever do need to construct a JSON string, it is never a good idea to manually type it in, as you could end up with escaped characters causing all sorts of issues. it is best to put the data into an object and then use the ***JSON.stringify()*** built into all browsers to convert it into a string

**Comment by cemmons** [comment] 2017-02-03 23:19
Oh, thanks for the tip on the JSON.stringify,

I changed the code but still is not working.. anything to do with assigning a different index?  

```
 if (value == '' || value <= '0') {
                showError('El valor no puede ser vacio o menor a 1.');
               
                var updRow = {};

                updRow[field] = oldValue;

                $("#productSortingGrid").tabulator("updateRow",id, updRow);
            }
```

**Comment by olifolkerd** [comment] 2017-02-03 23:22
which bit isnt working? the ajax request or updating the row when it has no value?

have you put in any console.log commands to check the values that are being passed to your if statements and to check they are being executed correctly?

**Comment by cemmons** [comment] 2017-02-03 23:32
the part that is not working is the updating part, im debugging the js code and it's getting inside the if correctly, gets to the tabulator and no error in console,  but it doesn't update it.

I'm gonna put that code somewhere else and try there.. to see if any implementation is doing something

**Comment by olifolkerd** [comment] 2017-02-03 23:38
i think you might need to delay the update by a few hundred milliseconds to give the d=cell edit process a chance to updates

```js
setTimeout(function(){
$("#productSortingGrid").tabulator("updateRow",id, updRow);

}, 300);
```

**Comment by cemmons** [comment] 2017-02-04 00:11
Noup, :(

**Comment by olifolkerd** [comment] 2017-02-04 04:13
Ahh, you are running an old version of Tabulator. download the latest commits, a fix was committed for this about three days ago

**Comment by cemmons** [comment] 2017-02-04 04:54
Omg... I made you lost your time  U.U ... next time I'll be sure to have the latest version before posting something..
Thanks anyway, now it's working fine

**Closed** 2017-02-04 09:26 UTC
Labels: question
