### ISSUE TITLE
Is there a way to clone or use a column template across multiple tables?

### ISSUE THREAD

**Issue by rquintana2008** [olifolkerd/tabulator#963] opened 2018-03-14 21:19 UTC
I am splitting data into multiple tables, the format is the same. Can I clone or use the same column template across multiple tables?

Thanks

**Comment by olifolkerd** [comment] 2018-03-14 22:14
Hey @rquintana2008 

You can store you column definitions in a variable and then assign it to a table:

```js
define columns
var colDefs=[
    {title:"Name", field:"name"},
    {title:"Age", field:"age"}
]

//create first table
$("#table1").tabulator({
    columns:colDefs,
})

//create second table
$("#table2").tabulator({
    columns:colDefs,
})
```

Let me know if that helps,

Cheers

Oli :)

**Comment by rquintana2008** [comment] 2018-03-19 19:58
The issues I run into is when I have a function for example:

var tableTemplate = [
    {title:"Project",field:"chipName", headerFilter:true,width:150,
formatter:"link", formatterParams:{url:*function(cell,formatterParams){*
*        var data = cell.getRow().getData();*
*        return "http://" + data.Server + ":" + data.Port*
*    }*}},
    {title:"Ready",field:"ready",formatter:"tickCross"},
    {title:"status",field:"status",},


This is when setting the columnDef's seems to fall appart.
Any suggestions?

Thanks,
-Royce

**Comment by olifolkerd** [comment] 2018-03-20 07:24
Hey @rquintana2008 

Could you explain what you mean by "fall apart", do you get errors in your console, do the tables miss behave?

Cheers

Oli

**Comment by rquintana2008** [comment] 2018-03-20 16:46
Sorry Oli,

So after further debug, I am finding that regardless of the table template,
if I try to load the same template into multiple tables the second table
will fail to display. If I comment out the first $().tabulator(...) call
the second table will load without issue.

Ex:

<h3>Table 1</h3>
<div id="ftc-table" ></div>
<h3>Table 2</h3>
<div id="ban-table" ></div>

.
.
.

var tableTemplate = [
    {title:"Ready",field:"ready",formatter:"tickCross"},
    {title:"status",field:"status",},
    {title:"Start Time",field:"start_time"},
    {title:"Last Update",field:"current_time"},
    {title:"Last Snapshot",field:"last_snapshot"},
    {title:"Errors",field:"error_count"},
    {title:"Restarts",field:"restart_count"},
    {title:"Last Access",field:"last_access"},
    ]

$("#ftc-table").tabulator({
    data:ftcData, //set initial table data
    tooltips:true,
    columns:tableTemplate,
});

$("#ban-table").tabulator({
    data:banData, //set initial table data
    tooltips:true,

    columns:tableTemplate,
});

What I see:

[image: Screen Shot 2018-03-20 at 10.39.08 AM.png]

Thank you for your help, I'll note that it appears since the height of the
table div expands that it has an idea of how many rows should exist.

-Royce

**Comment by olifolkerd** [comment] 2018-03-21 07:12
Have you tried cloning the object before passing it into the second table



```js
$("#ban-table").tabulator({
    data:banData, //set initial table data
    tooltips:true,

    columns:jQuery.extend(true, {}, tableTemplate),
});

```

**Comment by rquintana2008** [comment] 2018-03-22 22:10
Oli,

I have tried this as well and have the same issues. Are you able to
recreate this behavior on your side?

Thanks,
-Royce

**Comment by olifolkerd** [comment] 2018-03-22 22:57
Hey @rquintana2008 

I have had a look through the issue and i have found out what the issue is.

The issue arises because Tabulator resets its columns array as part of the setup which is clearing out the column array before it is passed to the next table (because arrays are passed by reference)

A way around this is to use the line:
```js
 columns:jQuery.extend(true, [], tableTemplate),
```
in both the tables, this prevents the original array from being cleared out.

I will have a look into this for the next release and see if i can sort something out for you.

Let me know if that helps

Cheers

Oli :)

**Comment by rquintana2008** [comment] 2018-03-22 23:01
Oli!

Thanks! that worked perfectly as a workaround, I had not tried cloning in
for the original and the second. This works for me but was not obvious, I
appreciate your help!

-Royce

**Comment by olifolkerd** [comment] 2018-03-22 23:07
I have just pushed a fix for this to the master branch so you will no longer need to clone the array, i will include it on the next patch release.

Cheers

Oli :)

**Closed** 2018-03-24 12:39 UTC
Labels: question
