### ISSUE TITLE
Autocomplete , auto update cell's value

### ISSUE THREAD

**Issue by Dkkemaries** [olifolkerd/tabulator#2906] opened 2020-07-28 06:20 UTC
Hello,

it would be useful to make one small addition  for 'autocomplete' editor . 
Idea  : when we get only one value returned from the searchFunc ,  we can just press 'enter' ( or leave the cell - freetext + autocomplete from the search function ) to update cell with this value . In the current version we need to press 
1. ' down arrow' 
2 . 'enter'

 , but  in situations when we have only one  value -  step 1. is unnecessary .

Here is a problem description:

When we input 'Canad' it is clear that we think about Canada , but if we just press 'enter' we get 'United Kingdom' 
![8kk1b](https://user-images.githubusercontent.com/20822365/88625784-1ac38a00-d0b2-11ea-98ab-d058c29d4c47.png)

here link to my post on stackoverflow : https://stackoverflow.com/questions/63054886/tabulator-autocomplete-issue

Thanks

**Comment by olifolkerd** [comment] 2020-08-02 11:03
Hey @Dkkemaries 

Great idea, i will add a property to the editor to allow auto selection of the first element in the list so it can be a quick enter to select it.

Cheers

Oli :)

**Comment by Dkkemaries** [comment] 2020-09-07 07:59
Hello, what about this autocomplete enhancement? I downloaded 4.8 version , but nothing  has been changed , I still need to press 
1. ' down arrow'
2 . 'enter'

(http://tabulator.info/examples/4.8#editable - same situation ) .

**Comment by olifolkerd** [comment] 2020-09-07 08:20
Hey @Dkkemaries 

This feature hasn't been added to Tabulator yet, which is why the issue is still open.

Tabulator has a large number of users each with different needs which means that not all feature requests can be immediately actioned.

Depending on workload it is likely that this feature will be included in one of the next two releases.

If this is something you are keen to see in the library sooner then please feel free to submit a Pull Request with the feature in, checkout the [Pull Request Guide](http://tabulator.info/community#contribute-pr) for more details.

CHeers

Oli:)

**Comment by Dkkemaries** [comment] 2020-09-07 08:52
Thanks . now I understand. I will wait :)

**Comment by olifolkerd** [comment] 2022-04-10 07:52
Im rebuilding the select editor for the next release and on further reflection i think this would be a bad addition generally as selection of a row changes the text content of the editor which would be a jarring experience.

For this reason and a lack of community engagement on this suggestion since it was added at this point i will not be looking to add it to Tabulator.

Cheers

Oli :)

**Closed by olifolkerd** 2022-04-10 07:52 UTC
Labels: Enhancement
