### ISSUE TITLE
missing support for ajaxMethod

### ISSUE THREAD

**Issue by genius257** [olifolkerd/tabulator#123] opened 2016-12-07 18:44 UTC
currently only GET is available. Here's one solution at line 1360
```
-			type: "GET",
+			type: self.options.ajaxMethod?self.options.ajaxMethod:"GET",
```

**Comment by olifolkerd** [comment] 2016-12-07 22:02
Hey,

Thanks for getting in touch, this is actually a duplicate of another issue, which you can find here:
[https://github.com/olifolkerd/tabulator/issues/106](https://github.com/olifolkerd/tabulator/issues/106)

I would ***strongly*** recommend against doing that as it would be misusing a POST request.

GET requests are intended for retrieving data, POST requests are for creating/updating records and are not supposed to be used for simple data retrieval.

**Closed by olifolkerd** 2016-12-07 22:02 UTC
Labels: duplicate

**Comment by genius257** [comment] 2016-12-07 22:25
Apologies for the duplication, did not realize.
While i gracefully accept your response/login, i still don't see how restricting functionality is a step in the right direction.
Anyway. Thank you for your fast and well formulated response.

**Comment by olifolkerd** [comment] 2016-12-07 22:35
I take your point on board, i will consider it for the next release

**Comment by genius257** [comment] 2016-12-07 22:45
Many thanks

**Comment by olifolkerd** [comment] 2016-12-11 14:38
Due to popular demand Tabulator can now make ajax requests with any HTTP request type.

There are two ways of doing this, if you are defining the request url when building the table using the ***ajaxURL*** option, then you can set the request type using the ***ajaxType*** option:
```js
$("#example-table").tabulator({
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxParams:{key1:"value1", key2:"value2"}, //ajax parameters
    ajaxType:"POST", //ajax HTTP request type
});
```
If you are triggering the request using the ***setData*** function, then you can pass the type in as an optional third argument:
```js
$("#example-table").tabulator("setData","http://www.getmydata.com/now", {}, "POST"); //make a post request
```

Full details on how to use this functionality can be found in the [Ajax Documentation](http://olifolkerd.github.io/tabulator/docs/#ajax)
