### ISSUE TITLE
Sorting symbol in header misplaced when using headerVertical

### ISSUE THREAD

**Issue by harbulot** [olifolkerd/tabulator#3015] opened 2020-09-30 21:33 UTC
**Describe the bug**

In version 4.7, the sorting symbol (triangle) used to be at the top of the header when `headerVertical` was used. In version 4.8, the triangle seems to be vertically centred with the header text, and overlaid on top of that text if the column in narrow.

**Tabulator Info**
- 4.8.2

**Working Example**

Behaviour with version 4.7.2: https://jsfiddle.net/fcwsk0hz/

![image](https://user-images.githubusercontent.com/80994/94740657-f2cefc00-036a-11eb-9bab-9025a0649b45.png)

Behaviour with version 4.8.2: https://jsfiddle.net/bythn81j/

![image](https://user-images.githubusercontent.com/80994/94740897-43465980-036b-11eb-838b-abac926161ee.png)

This is more or less the same as the "Quickstart" example, with a few boolean fields. (The problem is more visible when using `layout: "fitData"`.)

```js
var table = new Tabulator("#example-table", {
    height: 205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout: "fitData",
    data: tabledata, //assign data to table
    columns: [ //Define Table Columns
      {
        title: "Name",
        field: "name",
        width: 150
      },
      {
        title: "Age",
        field: "age",
        hozAlign: "left",
        formatter: "progress"
      },
      {
        title: "Likes Red",
        field: "likesRed",
        formatter: "tickCross",
        headerVertical: true
      },
      {
        title: "Likes Green",
        field: "likesGreen",
        formatter: "tickCross",
        headerVertical: true
      },
      {
        title: "Likes Blue",
        field: "likesBlue",
        formatter: "tickCross",
        headerVertical: true
      },
      {
        title: "Favourite Color",
        field: "col",
      },
    ],
  });
```

This is the result with `layout: "fitColumns"`:

- version 4.7:

![image](https://user-images.githubusercontent.com/80994/94741770-8bb24700-036c-11eb-8df2-3fbace2e4f5d.png)

- version 4.8:

![image](https://user-images.githubusercontent.com/80994/94741588-3f670700-036c-11eb-9833-54002a18532a.png)

**Comment by harbulot** [comment] 2020-10-01 14:25
This seems to be caused by `align-items: center` (not sure if this was intentional):
https://github.com/olifolkerd/tabulator/blame/a53b4de0fd77426557c75e5974cc8187e76605ff/src/scss/tabulator.scss#L163

**Comment by olifolkerd** [comment] 2020-10-01 19:21
Hey @harbulot 

Ahh yes this will be regression caused by a significant change to the way headers were built in the 4.8 release. I clearly forgot to handle vertical column headers in the update

I will look at getting a fix for this into the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-10-25 14:03
Hey @harbulot 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2020-10-25 14:03 UTC
Labels: Bug, Possible Bug
