### ISSUE TITLE
setHeaderFilterValue() Render Problem

### ISSUE THREAD

**Issue by OOnogul** [olifolkerd/tabulator#1721] opened 2019-01-11 15:36 UTC
**Description**
When setHeaderFilterValue() is called with a value on a column that has the following definitions, nothing is changing in header filter input element. But if clicked/focused the value is rendered/shown.

The definition part with the header filter:
```
headerFilter: "select"
headerFilterParams: {values: true}
```

**Tabulator Info**
- Tabulator version 4.1.5

**To Reproduce**
1. Call setHeaderFilterValue() with valid parameters on a column that has select headerfilter.
2. See that there is no change in the text of header filter input element.
3. Click the header filter and see it as rendered.

**Expected behavior**
The value should be visible when its set on header filter as the other columns that is not `headerFilter: "select" `

Browser: Chrome v67.0.3396.87

Thanks in advance.

**Comment by olifolkerd** [comment] 2019-01-12 10:06
Hey @OOnogul 

Thanks for getting in touch, sorry to hear you are having trouble.

Could you create a JS Fiddle or a CodePen that demonstrates how your are using the table and how you are calling the function. It is hard to offer support without seing the code you are using.

Cheers

Oli :)

**Comment by OOnogul** [comment] 2019-01-12 14:37
Yeah of course, I have recreated the problem with a demo in the link below.

https://jsfiddle.net/vmq6eosn/1/

You can see that after constructing the table there is two lines of code that sets the header filter values.
One for a input type header filter, second one is setting a enum type header filter. As you can see after setting headerfilter the value is seen in the filter element.
But in the second one, altough the filter is applied to data, the value is not visible until you click in the header filter input element.

I hope I have been able to express the issue that I have come across. 

Many thanks

**Comment by olifolkerd** [comment] 2019-01-13 15:07
Hey @OOnogul 

Thanks for the fiddle, it was very helpful in isolating the issue. That is definitely a bug, i will look at fixing it for the 4.2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2019-02-09 18:13
The issue was caused by the editor not correctly displaying the initial value of the cell, when used as an editor or header filter.

I have pushed a fix for this to the 4.2 branch and will include it in mondays release.

Cheers

Oli :)

**Closed by olifolkerd** 2019-02-09 18:13 UTC
Labels: bug
