### ISSUE TITLE
Group By functions empty data

### ISSUE THREAD

**Issue by giuliano-marinelli** [olifolkerd/tabulator#2145] opened 2019-06-11 15:10 UTC
**data** attribute of Group By functions is empty (in functions for groupHeader, groupStartOpen, etc).

To solve this, i create a recursive function that iterates the group parameter of the functions by their groupList element, and concat all the rows arrays.

```
function tabulatorGetGroupData(group) {
    var rows = [];
    var groupList = group._group;
    rows = tabulatorGetGroupDataList(groupList);
    return rows;
}

function tabulatorGetGroupDataList(groupList) {
    var rows = groupList.rows;
    for (var i = 0; i < groupList.groupList.length; i++) {
        rows = rows.concat(tabulatorGetGroupDataList(groupList.groupList[i]));
    }
    return rows;
}
```

it can be called at this way:
```
groupHeader: [
   function (value, count, data, group) {
      rows = tabulatorGetGroupData(group);
      for (var i = 0; i < rows.length; i++) {
         console.log(rows[i].data.ATTRIBUTE);
      }
   }
]
```

**Tabulator Info**
v4.2.7

**Comment by KES777** [comment] 2019-06-11 15:39
@giuliano-marinelli  is this duplicate of https://github.com/olifolkerd/tabulator/issues/2143?

**Comment by giuliano-marinelli** [comment] 2019-06-11 21:06
Yes, it is. Sorry.
But the walkaround code can be used.

**Comment by KES777** [comment] 2019-06-12 08:41
despite on the current behavior. May you, please, describe how do you expect it to work?

**Comment by giuliano-marinelli** [comment] 2019-06-14 13:31
It's the same problem than this #2143. How is explained in that post, it's not a bug, instead it's a not contemplated behaviour.

**Comment by raiamit44** [comment] 2019-06-27 14:58
Could you please let me know , how we can use "groupValues" at run time after applying "setGroupBy" ? is there any method like setGroupValues() ?

How we can expand/collapse the each row in case of multilevel grouping during run time on any action ?

How we can save the tabulator grid state (grouping/filtering/sorting/selection states) to memory and reuse it on next login ? I have seen persistenceMode, but it's only for sorting/filter ?

Please let me know, I am stuck on this!

Thanks.

**Comment by KES777** [comment] 2019-06-28 11:16
>how we can use "groupValues" at run time after applying "setGroupBy" ? is there any method like setGroupValues() ?

Probably you should reopen data, so tabulator grid will reinit

>How we can expand/collapse the each row in case of multilevel grouping during run time on any action ?

```
  groupBy : [ 'agreement_id', 'period_id' ],
  groupHeader: [ function( value, count, data, group ){
    data =  group.getSubGroups()[0].getRows()[0].getData();
    var ld =  this.groupManager.table.columnManager.getColumnByField( 'agreement_id' ).lookupData;
    ld =  ld[data.agreement_id];
    if( !ld ) {
      console.log( value );
      alert( 'Идентификатор документа не найден. Позовите программиста' );
      return;
    }

    return ld['docn'] + " " + ld['docdate'];
  },
  rowDblClick: function( e, row ) {
    var url =  row.getTable().options.ajaxURL
      + '?id=' +row.getData()[ 'id' ];
    ajax_query( 'GET', url, null, {
      success: function( data ) {
        row.update( data[0] );
      },
    });
    row._row._nested[1].setData();
  },
  rowClick: function( e, row ) {
    childTableOpts.ajaxURL =
      // "/api/order_details?order_id=" + row.getIndex();
      "/static/order/" +row.getIndex() +"/details_with_package";

    var tableEl =  nestedResourceTable( row, childTableOpts, (postData)=>{
      return {
        order_id         : row.getIndex(),
        service_type_id  : postData.service_type_id,
        resource_type_id : postData.resource_type_id,
        amount           : postData.amount,
      };
    }
```
>How we can save the tabulator grid state (grouping/filtering/sorting/selection states) to memory and reuse it on next login ?

You need to use cookies. This is how I save required value. You can adopt it to your needs


```
   <script type="text/javascript" src="/static/js/js.cookie.js"></script>

    var picker =  $( selector );
    var app_period;
    if( Cookies.get( 'app_period' ) ) {
      val =  Cookies.get( 'app_period' );
      ...
    }

    if( ... ) {
             Cookies.remove('app_period');
             return;
     }
     ...
            Cookies.set( 'app_period', your_value, {
                path: '/', expires: 7,
            });
```

**Closed** 2019-07-17 20:59 UTC
