### ISSUE TITLE
Movable Rows between tables not working on desktop Firefox or any mobile browser.

### ISSUE THREAD

**Issue by cialamo93** [olifolkerd/tabulator#2969] opened 2020-09-04 04:59 UTC
**Describe the bug**
"Movable Rows between tables" is not working on desktop Firefox (version 80.0.1) or in any Android mobile browser. In desktop chrome works just fine. At first I thought it was just my code or my computer but I tried it on the official Tabulator website and still wasn't working. I also tried it in a couple of codepens and also didn't work. When I select a row, I can drag it to the other table, but I can't drop the row on it, it just returns to the original table. It's exactly the same problem on Firefox desktop and mobile browsers. I can drag the rows with no problem, but they won't drop on the new table. I uploaded a gif that shows the problem (video taken in desktop firefox, link below).

**Tabulator Info**
Version 4.7 (also tried with 4.5, 4.0, 3.5 and still didn't work)

**Working Example**
https://codepen.io/shaunhurley/pen/NLZOqo 
*Not my codepen, but it shows the exact problem (rows can be dragged but not dropped on a new table)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

1. Select a row from a table
2. Drag it to the destination table
3. Try to drop the row on the destination table
4. See error (row returns to original table)

**Expected behavior**
The row was expected to drop on a new table

**Screenshots**
https://giphy.com/gifs/m9R6OInnmYr2MvWOCM

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 80

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Pro
 - OS: Android 10
 - Browser: Chrome, Firefox, Edge
 - Version: Newest version on each one

**Comment by olifolkerd** [comment] 2020-09-05 13:44
This is a duplicate of issue #1184

**Closed by olifolkerd** 2020-09-05 13:44 UTC
Labels: Duplicate
