### ISSUE TITLE
Tabulator on iOS/Safari/iPhone Jittery?

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#955] opened 2018-03-11 18:31 UTC
Has anyone noticed any issues/fixes with tabulator that when viewed on an iPhone the tables are very 'jittery' with all the rows/columns shaking a lot.    I have several fairly wide table with a couple frozen columns each on the left hand side and it jitters like a hula dancer!  

Thanks!

**Comment by olifolkerd** [comment] 2018-03-11 22:36
Hey @YendorMc 

I have a few questions for you on this one:

Which version of Tabulator are you using?
Which version of iPhone are you using?
Are your tables wider that the window, or resizing to fit?
do you have an example table constructor/data that i can use to replicate the issue?
are you using a responsive layout mode?
do you have a screenshot/video of the issue?

Cheers

Oli :)

**Comment by YendorMc** [comment] 2018-03-14 13:30
Hi Oli!

Sorry for the delayed response... Here's what I have thus far:
Tabulator v3.4.0
iPhone 7 on iOS 11.2.2
Tables are wider than the div and window right now.
Not using Responsive Layout.  That seems to be only used for hiding columns, which is something I don't want to do in my application. 

Let me sanitize the table constructor, update to the latest v3.4.x and get a video for you.

To illustrate this, go to Tabulator.info>Examples>Frozen Columns and it's behaving very similar to the "Frozen Columns" Example on the iPhones, but will get you my example.

It may be sometime this weekend, though - thanks for the awesome support!

**Comment by olifolkerd** [comment] 2018-03-14 13:32
Hey @YendorMc 

You need to upgrade to a later version of Tabulator, there was a regression in the 3.4 release that caused unpredictable resizing issues in some browsers, this has been fixed in 3.4.3 onwards.

Cheers

Oli

**Comment by YendorMc** [comment] 2018-03-16 20:31
Hi Oli - upgraded to 3.5 (JS only) and closed Safari (iOS) to be sure, but still has the same response.  I will provide some additional details soon.

**Comment by olifolkerd** [comment] 2018-03-16 21:58
Hey @YendorMc 

Thanks for the info, can you make sure you are using 3.4.5 for any testing. 3.5 is in development at the moment and is in no way to be taken as stable, it is there so i can demo requested features as they are added.

Cheers

Oli

**Comment by YendorMc** [comment] 2018-03-21 18:15
Sorry for the lag in getting you feedback.

I had mind-slip on the version... I'm on 3.4.5

Enclosed is an extreme-case example that reproduces the jittering.  Please rename from .txt to .html

[iOS_v2.txt](https://github.com/olifolkerd/tabulator/files/1834655/iOS_v2.txt)

It was pretty solid with 1-2 data elements until I started adding more JSON data.  I tried to make the names entertaining, too :)

Next step is the video.  Will post later today.

**Comment by olifolkerd** [comment] 2018-03-21 19:34
Hey @YendorMc 

Great names! I particularly like Al B Bach and Sue Shee, i may have to use those on a demo in future ;)

I will run that through some tests this weekend and see if i can get to the bottom of the issue

Cheers

Oli :)

**Comment by YendorMc** [comment] 2018-03-22 01:05
Hi Oli,

I sent you a  privileged youtube link of the video at your gmail account:  oliver.folkerd@gmail.com

Let me know if you need/want any other details!

Thanks again for your help!

**Comment by olifolkerd** [comment] 2018-03-22 06:35
Hey @YendorMc 

Thanks for sending over the video, now i understand where you are coming from. That is actually caused by the mobile device not being able to render all the changes fast enough, in that view there are a lot of elements being moved at the same time (the frozen columns are most likely the culprit).

I am looking at putting in additional optimizations to the rendering system in time, but this will likely be in version version 4.0 when i strip out the remaining jquery from Tabulator as that is what is slowing it down.

Cheers

Oli :)

**Closed by olifolkerd** 2018-03-22 06:35 UTC
Labels: question
