### ISSUE TITLE
Scrolling on iOS is jumping when using custom row template

### ISSUE THREAD

**Issue by asmundwego** [olifolkerd/tabulator#4033] opened 2022-11-23 14:22 UTC
**Describe the bug**
On iPhone, the vertical scrolling jumps when using 

**Tabulator Info**
- Tabulator version: 5.1.7

**Working Example**
[jsFiddle](https://jsfiddle.net/jsawe/9zutmev)

**To Reproduce**
Se jsFiddle.
1. Open https://jsfiddle.net/jsawe/9zutmevj/show on an iPhone (or Chrome on desktop in device simulation) 
2. Wait for table to finish initializing
3. Scroll slowly down
4. First part scrolls smoothly, then about one page down, items starts to jump wile scrolling
5. Scrolling furter down the issue is less visible, but some jumping still occurs.

**Expected behavior**
Scrolling should not cause jumping

**Screenshots**
See video. This is from my product where login is needed, but similar behaviour is in the jsFiddle. 

https://user-images.githubusercontent.com/14922923/203569918-df09633b-4969-4949-8203-33d87924c649.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome in device simulator or narrow window.
 - Version any

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Browser: Safari, Chrome

**Additional info**
I suspect it has something to do with the virtual dom that is not calculating right space when removing items at the top or something.

**Comment by olifolkerd** [comment] 2022-12-04 09:24
Hey @asmundwego 

This is essentially a duplicate of #3654 so i will link these two together to track progress.

This happens when the row size is variable of much bigger than expected do to recalculations in the virtual scrolling functionality.

I am aiming to fix this in the next minor release.

Cheers

Oli :)

**Closed by olifolkerd** 2022-12-04 09:24 UTC
Labels: Possible Bug
