### ISSUE TITLE
ajaxLoaderLoading Not displaying default

### ISSUE THREAD

**Issue by JonHaymanFCX** [olifolkerd/tabulator#924] opened 2018-02-26 12:39 UTC
When loading a tables data via AJAX, the default `ajaxLoaderLoading` html doesn't display.

A work around is to specify `ajaxLoaderLoading` in the table options, but this requires I change it on every table.

![tabulator-issue](https://user-images.githubusercontent.com/36848734/36670982-f9643b5c-1af1-11e8-88d3-a3e437b41661.png)

**Comment by olifolkerd** [comment] 2018-03-01 22:05
Hey @JonHaymanFCX 

Looks like you have caught a regression in 3.4.4 caused by an update to the localization system.

I have just pushed a fix to the master branch for this and will include it in this weekends patch release.

Let me know if you spot any other issues.

Cheers

Oli :)

**Closed by olifolkerd** 2018-03-01 22:05 UTC
Labels: bug
