### ISSUE TITLE
Autocolumns created from JSON don't use their localized column names when collapsed in responsive mode

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3068] opened 2020-11-08 22:08 UTC
**Describe the bug**
When autocolumns created from JSON are collapsed in responsiveCollapse mode, they don't show their localized titles

**Tabulator Info**
4.8.4

**Working Example**
http://covid19-schools.cti.gr/table.html
(if not occuring [need to patch/hide the issue soon] then issue will appear again if you edit the .js mentioned below using browser tools to uncomment the two lines that have the word "responsive" in them)

**To Reproduce**
1. Go to the above url
2. Make the window smaller till columns collapse
3. Colapsed columns show English titles instead of Greek ones they had in their headers

**Expected behavior**
Expect the columns to continue showing their Greek titles

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge(Chromium)
 - Version latest

**Additional context**
See tabulator config used at https://covid19-schools.cti.gr/js/table_tabulator.js (search for responsive)

**Comment by olifolkerd** [comment] 2020-11-08 22:13
This is essentially a duplicate of an issue raised earlier this month. It is unrelated to the autocolumns. All columns are not localized when in the responsive collapse formatter.

There is already a PR that fixes this waiting to be merged in. It will in comming in the 4.9 release later this month.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2020-11-15 14:55
I will close this now as the PR is near completion, but you can track progress on PR #3054

**Closed by olifolkerd** 2020-11-15 14:55 UTC
Labels: Possible Bug
