### ISSUE TITLE
AjaxProgressiveLoad:scroll does not show any loader on tabulator holder

### ISSUE THREAD

**Issue by cubecleveland** [olifolkerd/tabulator#3075] opened 2020-11-14 23:49 UTC
Hello,
AjaxProgressiveLoad: scroll is not showing any loader on the table. I am not sure if this is the expected behaviour but if so.. probably should be documented.

We tried to implement our own loader using the AjaxReposnse and AjaxRequesting callbacks but the First ajax response return before the Object of Tabulator is being created....,

**Comment by olifolkerd** [comment] 2020-11-15 11:05
This is the intended behaviour, it is supposed to scroll seamlessly and load silently in the background and not interrupt the user experience.

If users are able to scroll to the bottom of the table before the load has finished then i suggest you either look at reducing the page size of the data you are transferring to allow smaller quicker updates or updating the ***ajaxProgressiveLoadScrollMargin*** to cause the load action to trigger sooner to give yourself more time for data to be loaded into the table.

Cheers

Oli :)

**Closed by olifolkerd** 2020-11-15 11:05 UTC
Labels: Possible Bug

**Comment by cubecleveland** [comment] 2020-11-15 12:57
Amazing. Thanks so much for your always amazing support and this
unbelievable product.



CUBE Workspace
Corporate: 6240 Som Center Rd #130
Solon, OH 44139
T: 216.245.9629
