### ISSUE TITLE
row.getIndex() methode returns null value

### ISSUE THREAD

**Issue by ramyadv** [olifolkerd/tabulator#518] opened 2017-08-15 21:29 UTC
Hi, in  callback function cellClick whenever i am trying to get index of row using row.getIndex() it returns null value, where row is the row object. row.getElement() or other methods are working fine, Please help

I would greatly  appreciate your help.

**Comment by olifolkerd** [comment] 2017-08-15 21:47
Hey,

This is a duplicate of issue #415, in order to use the ***getIndex*** function you must have set a value for the index field of the row data, by default this is the ***id*** filed, but you can change this by setting the ***index*** option on the table.

have a look at issue #415 for full details.

Cheers

Oli

**Closed by olifolkerd** 2017-08-15 21:47 UTC
Labels: duplicate

**Comment by ramyadv** [comment] 2017-08-16 08:32
thank you so much oli, i have set the value for id field in constructor,  now it working .
