### ISSUE TITLE
Nested row groups

### ISSUE THREAD

**Issue by br3nd4nn34l** [olifolkerd/tabulator#410] opened 2017-06-27 14:49 UTC
It would be awesome if row-groups could have multiple nested layers. For example, if there's (country, city) attributes in a row, the most granular you can currently get is to display a (country - city) string as a group.  In this situation it would be great if there was a country group that encapsulated many city groups. Not sure how feasible this would be, but it would be incredibly helpful for viewing large data-sets with lots of nest-able groups.

**Comment by olifolkerd** [comment] 2017-06-27 18:11
This is a duplicate of #238 .

You will be happy to hear this is on the roadmap, and should be available in the next couple of months.

Let me know if you can think of any other suggestions

Cheers

Oli

**Closed by olifolkerd** 2017-06-27 18:11 UTC
Labels: duplicate

**Comment by olifolkerd** [comment] 2017-07-23 10:16
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the Multi-Level Grouping options, you simply pass arrays to the appropriate grouping options:
```js
groupBy:["gender", "color"], //group by gender then favourite color
```

Full information can be found in the [Grouping Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#grouping)

Cheers

Oli

**Comment by br3nd4nn34l** [comment] 2017-07-23 16:08
Awesome - this thing just keeps getting better and better!
