### ISSUE TITLE
Movable Rows Between Tables not working in Firefox

### ISSUE THREAD

**Issue by julienrueter** [olifolkerd/tabulator#3213] opened 2021-02-15 21:38 UTC
Hi,
this function doesn't seem to work in Firefox. Even the demo page showing this functionality http://tabulator.info/examples/4.9#movable-between-tables doesn't work in Firefox.

Firefox version: 85.0.1 (64-Bit)

**Comment by olifolkerd** [comment] 2021-02-15 22:26
This is a duplicate of an existing bug

**Closed by olifolkerd** 2021-02-15 22:26 UTC
