### ISSUE TITLE
Jquery with Jquery wrapper: typeError: Tabulator is not a constructor

### ISSUE THREAD

**Issue by edwinro** [olifolkerd/tabulator#2442] opened 2019-10-18 13:42 UTC
**Describe the bug**
Jquery and the jquery_wrapper , as described in http://tabulator.info/docs/4.4/jquery, is used.

Since version  4.3.0  a  "TypeError: Tabulator is not a constructor" error is thrown when trying to display a simple table. The table itself is not shown anymore. Older versions work fine.

**Tabulator Info**

The bug is Reproducable in versions 4.3.0 and 4.4.3
NOT Reproducable in version 3.4.6  and 4.2.7 

Tabel setup: 

   $("#example-table-1").tabulator({
            columns:[
                {title:"Name", field:"name"},
                {title:"Age", field:"age"},
            ],
        });

**Working Example**

https://codepen.io/edwinro/pen/zYYKepV

**To Reproduce**

Open the codepen link.  The different versions can be commented / un-commented in the head section.

The table is not visible anymore in versions  4.3.0 and 4.4.3. The "TypeError: Tabulator is not a constructor" error is seen in the browser console .

**Expected behavior**
The table should be visible

**Desktop :**
 - OS:Windows 
 - Browser: Firefox and Chrome
 - Version 
    Chrome: Version 77.0.3865.120 (Official Build) (64-bit)
      Firefox :69.0.3 (64-bit)

**Smartphone:**
Not tested

**Comment by olifolkerd** [comment] 2019-11-06 19:26
Hey @edwinro 

Thanks for the headsup, i will investigate this further.

Cheers

Oli :)

**Comment by olifolkerd** [comment] 2019-11-11 19:22
Hey @edwinro 

Looking into this further it looks like it was a regression in a PR i accepted a few months back. It managed to slip through, so apologies there.

I have pushed a fix for this to the 4.5 branch which will be released in the next few weeks.

Cheers

Oli :)

**Closed by olifolkerd** 2019-11-11 19:22 UTC
Labels: bug

**Comment by edwinro** [comment] 2019-11-12 22:02
Thank you @olifolkerd 

Cheers,
Edwin
