### ISSUE TITLE
editor:"select" ,complete row gets hidden when we select any option from select field 

### ISSUE THREAD

**Issue by anilkumar27** [olifolkerd/tabulator#2860] opened 2020-06-25 13:39 UTC
complete row of the selected cell or all rows above the selected cell gets hidden after the selecting any option from select dropdown. This happens only for the first time when we select.

**jsfiddle:**   [https://jsfiddle.net/anilyadav27/20q5dcbn/20/](url)

**Error in browser console is  as below :**

    core.js:5873 ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'invalid' of undefined
    TypeError: Cannot set property 'invalid' of undefined
    at Edit.clearEdited (tabulator.js:14298)
    at Cell.delete (tabulator.js:7491)
    at Row.deleteCells (tabulator.js:6543)
    at Row.wipe (tabulator.js:6549)
    at tabulator.js:3566
    at Array.forEach (<anonymous>)
    at RowManager._wipeElements (tabulator.js:3564)
    at RowManager._setDataActual (tabulator.js:3521)
    at tabulator.js:3491
    at new ZoneAwarePromise (zone-evergreen.js:872)
    at resolvePromise (zone-evergreen.js:793)
    at new ZoneAwarePromise (zone-evergreen.js:875)
    at RowManager.setData (tabulator.js:3485)
    at Tabulator._setData (tabulator.js:9049)
    at Tabulator.replaceData (tabulator.js:9174)
    at table-preview.component.ts:384
    at ZoneDelegate.invoke (zone-evergreen.js:365)
    at Object.onInvoke (core.js:40910)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:124) 

its failing in latest code added in 47version.

    Edit.prototype.clearEdited = function (cell) {
		var editIndex;

		if (cell.modules.edit && cell.modules.edit.edited) {
			cell.modules.validate.invalid = false;

			editIndex = this.editedCells.indexOf(cell);

			if (editIndex > -1) {
				this.editedCells.splice(editIndex, 1);
			}
		}
	};

**Comment by vec2k4** [comment] 2020-06-25 19:07
I think this is related to #2857 

To quick fix it, I have added a check to `tabulator.js` so the code looks like
```javascript
Edit.prototype.clearEdited = function (cell) {
	var editIndex;

	if (cell.modules.edit && cell.modules.edit.edited) {

		if (cell.modules.validate && cell.modules.validate.invalid) {
			cell.modules.validate.invalid = false;
		}

		editIndex = this.editedCells.indexOf(cell);

		if (editIndex > -1) {
			this.editedCells.splice(editIndex, 1);
		}
	}
};
```

At least for me that fixes the bug, although I'm unsure if this change is the right way to do it.

**Comment by anilkumar27** [comment] 2020-06-26 04:52
hey @vec2k4 ,

updated the url.

**jsfiddle** : [https://jsfiddle.net/anilyadav27/20q5dcbn/20/](https://jsfiddle.net/anilyadav27/20q5dcbn/20/)

**Comment by olifolkerd** [comment] 2020-06-27 17:28
Hey @anilkumar27 

This issue has the same root cause as #2857 i have pushed a fix ofr it to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Closed by olifolkerd** 2020-06-27 17:28 UTC
Labels: Duplicate, Possible Bug

**Comment by anilkumar27** [comment] 2020-07-02 05:37
hey @olifolkerd ,

Verified with latest 4.7.1 versions, this issue is fixed and working fine .

Cheers :)
