### ISSUE TITLE
Column Headers with multiple lines instead of ellipsis?

### ISSUE THREAD

**Issue by jflifecycle** [olifolkerd/tabulator#3541] opened 2022-01-17 19:45 UTC
I can make my data fit easily but I cannot figure out how to make a column header use more than one line. I have some columns with long names and small numerical values. 

Like having a column header "Median Homeowner Age" which has narrow values like 44, 33 etc. but I have 10 other columns I need to fit. I don't want to ellipsize the column headers because I want to know what the data is for. I'm not hard up for vertical space but is there really no way to make a title multiple lines? I've messed with the CSS but it just explodes and overlaps and there's no documentation on formatting header text to have more than one line.

**Comment by muffinimal** [comment] 2022-01-17 20:21
I think you should better post this at StackOverflow?

I'm no expert using Tabulator, but couldn't you just use the Column width setting? Or maybe use headerVertical?

**Comment by jflifecycle** [comment] 2022-01-17 20:25
I feel like multiline headers is a small ask and the inability to do it in Tabulator seems rather ridiculous.

**Comment by jflifecycle** [comment] 2022-01-17 20:27
I feel like multiline headers is a small ask and the inability to do it in Tabulator seems rather ridiculous.

I can't use column width because then it ellipsizes it "Median H...", and I can't vertically because it looks bad and is harder to read.

This is a line.
This is a second line.

See how easy that was? Why can't I do that in tabulator?

**Comment by 500Foods** [comment] 2022-01-17 20:37
If you add a <br> in the column title, does that help?  As in:  
Median<br>Homeowner<br>Age

**Comment by olifolkerd** [comment] 2022-01-17 20:40
This is a duplicate of #988 and is answered there

**Closed by olifolkerd** 2022-01-17 20:40 UTC

**Comment by jflifecycle** [comment] 2022-01-17 21:07
No it isn't. If you follow those instructions it overflows to the first row and doesn't resize the header. Now I have this:
![image](https://user-images.githubusercontent.com/92054377/149836926-abcfb486-0361-4a6b-9280-5ca55221756c.png)

I added a plain table below to show I can have multiline titles with literally zero effort. Tabulator requires undocumented css hacks, and cell level element styles. What's the expected way to do this?

**Comment by 500Foods** [comment] 2022-01-17 21:19
Odd. When I added the `<br>` tags the height increased automatically to adjust.  Might be that you have some CSS that is preventing this from happening?  I guess that's why he likes people to post jsfiddles - so it can be clear what the issue is without any surprises. He also suggested some CSS as you've noted. But that might also be limited if you've somehow got some CSS that fixes the height at 48px or whatever. So two options?  Better than none.  I agree documentation for this kind of thing could be better though.
